=== RedhawkSDR/core-framework/redhawk/src/xml/dtd/deviceconfiguration.dtd
<!--
This file is protected by Copyright. Please refer to the COPYRIGHT file 
distributed with this source distribution.

This file is part of REDHAWK core.

REDHAWK core is free software: you can redistribute it and/or modify it under 
the terms of the GNU Lesser General Public License as published by the Free 
Software Foundation, either version 3 of the License, or (at your option) any 
later version.

REDHAWK core is distributed in the hope that it will be useful, but WITHOUT ANY 
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR 
A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more 
details.

You should have received a copy of the GNU Lesser General Public License along 
with this program.  If not, see http://www.gnu.org/licenses/.
-->

<!ELEMENT deviceconfiguration
	( description?
	, devicemanagersoftpkg
	, componentfiles?
	, partitioning?
	, connections?
	, domainmanager
	, filesystemnames?
	)>
<!ATTLIST deviceconfiguration
	id		ID	#REQUIRED
	name		CDATA	#IMPLIED>

<!ELEMENT description (#PCDATA)>

<!ELEMENT devicemanagersoftpkg
	( localfile
	)>

<!ELEMENT componentfiles 
	( componentfile+
	)>

<!ELEMENT componentfile
	( localfile 
	)>
<!ATTLIST componentfile
	id 		ID	#REQUIRED
	type		CDATA	#IMPLIED>

<!ELEMENT localfile EMPTY>
<!ATTLIST localfile
	name		CDATA	#REQUIRED>

<!ELEMENT partitioning 
	( componentplacement
	)*>

<!ELEMENT componentplacement 
	( componentfileref
	, deployondevice?
	, compositepartofdevice?
	, devicepkgfile?
	, componentinstantiation+
	)>

<!ELEMENT componentfileref  EMPTY>
<!ATTLIST componentfileref
	refid		CDATA	#REQUIRED>

<!ELEMENT deployondevice  EMPTY>
<!ATTLIST deployondevice
	refid		CDATA	#REQUIRED>

<!ELEMENT compositepartofdevice  EMPTY>
<!ATTLIST compositepartofdevice
	refid		CDATA	#REQUIRED>

<!ELEMENT devicepkgfile 
	(localfile
	)>
<!ATTLIST devicepkgfile
	type		CDATA	#IMPLIED>

<!ELEMENT componentinstantiation
	( usagename?
	 ,componentproperties?
         ,affinity?
         ,loggingconfig?
         ,deployerrequires?
	)>
<!ATTLIST componentinstantiation
    id  ID  #REQUIRED
    startorder CDATA #IMPLIED>

<!ELEMENT usagename (#PCDATA)>

<!ELEMENT loggingconfig (#PCDATA)>
<!ATTLIST loggingconfig 
          level CDATA #IMPLIED>

<!ELEMENT affinity
	( simpleref
	| simplesequenceref
	| structref
	| structsequenceref
	)+ >

<!ELEMENT deployerrequires
	( requires
	)+ >

<!ELEMENT componentproperties 
	( simpleref
	| simplesequenceref
	| structref
	| structsequenceref
	)+ >

<!ELEMENT devicethatloadedthiscomponentref EMPTY>
<!ATTLIST devicethatloadedthiscomponentref 
	refid		CDATA	#REQUIRED>

<!ELEMENT deviceusedbythiscomponentref EMPTY>
<!ATTLIST deviceusedbythiscomponentref 
	refid		CDATA	#REQUIRED
	usesrefid	CDATA	#REQUIRED>

<!ELEMENT requires EMPTY>
<!ATTLIST requires
	id		CDATA	#REQUIRED
	value		CDATA	#REQUIRED>

<!ELEMENT simpleref EMPTY>
<!ATTLIST simpleref
	refid		CDATA	#REQUIRED
	value		CDATA	#REQUIRED>
		
<!ELEMENT simplesequenceref
	(values
	)>
<!ATTLIST simplesequenceref
	refid		CDATA	#REQUIRED>

<!ELEMENT structref
	( (simpleref | simplesequenceref)+
	)>
<!ATTLIST structref
	refid		CDATA	#REQUIRED>

<!ELEMENT structsequenceref
	( structvalue+
	)>
<!ATTLIST structsequenceref
	refid		CDATA	#REQUIRED>

<!ELEMENT structvalue
	( (simpleref | simplesequenceref)+
	)>
		
<!ELEMENT values
	( value+ 
	)>
		
<!ELEMENT value (#PCDATA)>

<!ELEMENT componentinstantiationref EMPTY>
<!ATTLIST componentinstantiationref 
	refid	CDATA	#REQUIRED>

<!ELEMENT domainmanager
	( namingservice
	| stringifiedobjectref
	)>

<!ELEMENT findby
	( namingservice
	| stringifiedobjectref
	| domainfinder
	)>

<!ELEMENT namingservice EMPTY>
<!ATTLIST namingservice
	name		CDATA	#REQUIRED>

<!ELEMENT stringifiedobjectref (#PCDATA)>

<!ELEMENT domainfinder EMPTY>
<!ATTLIST domainfinder
	type		CDATA	#REQUIRED
	name		CDATA	#IMPLIED>

<!ELEMENT filesystemnames
	(filesystemname+
	)>

<!ELEMENT filesystemname EMPTY>
<!ATTLIST filesystemname
	mountname	CDATA	#REQUIRED
	deviceid	CDATA	#REQUIRED>

<!ELEMENT connections
      ( connectinterface*
      )>

<!ELEMENT connectinterface
	( usesport
	, ( providesport
	  | componentsupportedinterface
	  | findby
	  )
	)>

<!ATTLIST connectinterface
	id		ID	#IMPLIED>

<!ELEMENT usesport
	( usesidentifier
	, (componentinstantiationref
	   | devicethatloadedthiscomponentref
	   | deviceusedbythiscomponentref
	   | findby
	   )
	)>

<!ELEMENT usesidentifier (#PCDATA)>

<!ELEMENT providesport
	( providesidentifier
	, ( componentinstantiationref
	  | devicethatloadedthiscomponentref
	  | deviceusedbythiscomponentref
	  | findby
	  )
	)>

<!ELEMENT providesidentifier (#PCDATA)>

<!ELEMENT componentsupportedinterface
	( supportedidentifier
	, ( componentinstantiationref
	  | findby
	  )
	)>

<!ELEMENT supportedidentifier (#PCDATA)>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dev/nodes/test_DuplicateTestDevice_node/DeviceManager.dcd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
This file is protected by Copyright. Please refer to the COPYRIGHT file 
distributed with this source distribution.

This file is part of REDHAWK core.

REDHAWK core is free software: you can redistribute it and/or modify it under 
the terms of the GNU Lesser General Public License as published by the Free 
Software Foundation, either version 3 of the License, or (at your option) any 
later version.

REDHAWK core is distributed in the hope that it will be useful, but WITHOUT ANY 
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR 
A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more 
details.

You should have received a copy of the GNU Lesser General Public License along 
with this program.  If not, see http://www.gnu.org/licenses/.
-->

<!DOCTYPE deviceconfiguration PUBLIC '-//JTRS//DTD SCA V2.2.2 DCD//EN' 'deviceconfiguration.dtd'>
<deviceconfiguration name="BasicTestDevice_node" id="DCE:65f84ea9-cbe9-42cc-bc2e-6807f7ff9b8c">
    <devicemanagersoftpkg>
        <localfile name="/mgr/DeviceManager.spd.xml"/>
    </devicemanagersoftpkg>
    <componentfiles>
        <!--Device Definitions--> 
        <componentfile type="SPD" id="BasicTestDevice1_c6e250b8-5223-11db-9fc4-000d56d8556e">
            <localfile name="/devices/BasicTestDevice/BasicTestDevice.spd.xml"/>
        </componentfile>
    </componentfiles>
    <partitioning>
        <componentplacement>
            <componentfileref refid="BasicTestDevice1_c6e250b8-5223-11db-9fc4-000d56d8556e"/>
            <componentinstantiation id="DCE:8f3478e3-626e-45c3-bd01-0a8117dbe59b">
                <!--componentinstantiation id="DCE:cdffec5c-5223-11db-9502-000d56d8556e"-->
                <usagename>BasicTestDevice1</usagename> 
            </componentinstantiation>
        </componentplacement>
        <componentplacement>
            <componentfileref refid="BasicTestDevice1_c6e250b8-5223-11db-9fc4-000d56d8556e"/>
            <componentinstantiation id="DCE:fd5c549f-d97c-4665-bce7-d26f4d9680f8">
                <!--componentinstantiation id="DCE:cdffec5c-5223-11db-9502-000d56d8556e"-->
                <usagename>BasicTestDevice1</usagename> 
            </componentinstantiation>
        </componentplacement>
    </partitioning>
    <domainmanager>
        <namingservice name="DomainName1/DomainManager"/>
    </domainmanager>
</deviceconfiguration>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dev/nodes/test_BasicService_node/DeviceManager.dcd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
This file is protected by Copyright. Please refer to the COPYRIGHT file 
distributed with this source distribution.

This file is part of REDHAWK core.

REDHAWK core is free software: you can redistribute it and/or modify it under 
the terms of the GNU Lesser General Public License as published by the Free 
Software Foundation, either version 3 of the License, or (at your option) any 
later version.

REDHAWK core is distributed in the hope that it will be useful, but WITHOUT ANY 
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR 
A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more 
details.

You should have received a copy of the GNU Lesser General Public License along 
with this program.  If not, see http://www.gnu.org/licenses/.
-->

<!DOCTYPE deviceconfiguration PUBLIC '-//JTRS//DTD SCA V2.2.2 DCD//EN' 'deviceconfiguration.dtd'>
<deviceconfiguration name="BasicService_node" id="DCE:65f84ea9-cbe9-42cc-bc2e-6807f7ff9b10">
    <devicemanagersoftpkg>
        <localfile name="/mgr/DeviceManager.spd.xml"/>
    </devicemanagersoftpkg>
    <componentfiles>
        <!--Device Definitions--> 
        <componentfile type="SPD" id="BasicService1_c6e250b8-5223-11db-9fc4-000d56d8556e">
            <localfile name="/services/BasicService/BasicService.spd.xml"/>
        </componentfile>
    </componentfiles>
    <partitioning>
        <componentplacement>
            <componentfileref refid="BasicService1_c6e250b8-5223-11db-9fc4-000d56d8556e"/>
            <componentinstantiation id="DCE:8f3478e3-626e-45c3-bd01-0a8117dbe59b">
                <usagename>BasicService1</usagename> 
                <componentproperties>
                    <simpleref refid="PARAM5" value="Hello World"/>
                </componentproperties>
            </componentinstantiation>
        </componentplacement>
    </partitioning>
    <domainmanager>
        <namingservice name="DomainName1/DomainManager"/>
    </domainmanager>
</deviceconfiguration>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dev/nodes/test_PortTestDevice_node/DeviceManager.dcd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
This file is protected by Copyright. Please refer to the COPYRIGHT file 
distributed with this source distribution.

This file is part of REDHAWK core.

REDHAWK core is free software: you can redistribute it and/or modify it under 
the terms of the GNU Lesser General Public License as published by the Free 
Software Foundation, either version 3 of the License, or (at your option) any 
later version.

REDHAWK core is distributed in the hope that it will be useful, but WITHOUT ANY 
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR 
A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more 
details.

You should have received a copy of the GNU Lesser General Public License along 
with this program.  If not, see http://www.gnu.org/licenses/.
-->

<!DOCTYPE deviceconfiguration PUBLIC '-//JTRS//DTD SCA V2.2.2 DCD//EN' 'deviceconfiguration.dtd'>
<!-- Created with REDHAWK IDE-->
<!-- Powered by Eclipse -->
<deviceconfiguration name="PortTestDevice_node" id="DCE:33708d3b-beed-40a3-b490-334cdd6af80a">
    <devicemanagersoftpkg>
    	<localfile name="/mgr/DeviceManager.spd.xml" />
    </devicemanagersoftpkg>
    <componentfiles>
        <componentfile type="SPD" id="PortTestDevice1_c6e250b8-5223-11db-9fc4-000d56d8556e">
            <localfile name="/devices/PortTestDevice/PortTestDevice.spd.xml"/>
        </componentfile>        
    </componentfiles>
    <partitioning>
        <componentplacement>
            <componentfileref refid="PortTestDevice1_c6e250b8-5223-11db-9fc4-000d56d8556e"/>
            <componentinstantiation id="DCE:322fb9b2-de57-42a2-ad03-217bcb244262">
                <usagename>PortTestDevice1</usagename> 
            </componentinstantiation>
        </componentplacement>
        <componentplacement>
            <componentfileref refid="PortTestDevice1_c6e250b8-5223-11db-9fc4-000d56d8556e"/>
            <componentinstantiation id="DCE:47dc45d8-19b5-4b7e-bcd4-b165babe5b84">
                <usagename>PortTestDevice2</usagename> 
            </componentinstantiation>
        </componentplacement>
    </partitioning>
    <connections>
        <connectinterface>
            <usesport>
                <usesidentifier>resource_out</usesidentifier>
                <componentinstantiationref refid="DCE:322fb9b2-de57-42a2-ad03-217bcb244262"/>
            </usesport>
            <providesport>
                <providesidentifier>resource_in</providesidentifier>
                <componentinstantiationref refid="DCE:47dc45d8-19b5-4b7e-bcd4-b165babe5b84"/>
            </providesport>
        </connectinterface>
    </connections>
    <domainmanager>
        <namingservice name="DomainName1/DomainManager"/>
    </domainmanager>
</deviceconfiguration>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dev/nodes/node_exec_params/node_exec_params/DeviceManager.false-false.dcd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE deviceconfiguration PUBLIC "-//JTRS//DTD SCA V2.2.2 DCD//EN" "deviceconfiguration.dtd">
<deviceconfiguration id="DCE:294f1fef-a09d-4e75-a68e-86be04e90082" name="node_exec_params">
  <devicemanagersoftpkg>
    <localfile name="/mgr/DeviceManager.spd.xml"/>
  </devicemanagersoftpkg>
  <componentfiles>
    <componentfile id="py_dev_exec_params_676bc4ea-ebd1-462c-8b3e-ebf23ef23773" type="SPD">
      <localfile name="/devices/py_dev_exec_params/py_dev_exec_params.spd.xml"/>
    </componentfile>
  </componentfiles>
  <partitioning>
    <componentplacement>
      <componentfileref refid="py_dev_exec_params_676bc4ea-ebd1-462c-8b3e-ebf23ef23773"/>
      <componentinstantiation id="node_exec_params:py_dev_exec_params_1">
        <usagename>py_dev_exec_params_1</usagename>
        <componentproperties>
          <simpleref refid="config_prop_normal" value="prop_ok_normal"/>
          <simpleref refid="exec_read_only" value="cmd_ok_read_only"/>
          <simpleref refid="exec_read_only_empty" value=""/>
          <simpleref refid="exec_read_only_number" value="12345"/>
          <simpleref refid="exec_read_only_bool" value="fAlSe"/>
          <simpleref refid="exec_read_only_empty_number" value=""/>
          <simpleref refid="exec_cmd" value="cmd_ok"/>
          <simpleref refid="exec_cmd_empty" value=""/>
        </componentproperties>
      </componentinstantiation>
    </componentplacement>
  </partitioning>
  <domainmanager>
    <namingservice name="REDHAWK_DEV/REDHAWK_DEV"/>
  </domainmanager>
</deviceconfiguration>
