=== RedhawkSDR/core-framework/redhawk/src/xml/dtd/deviceconfiguration.dtd
<!--
This file is protected by Copyright. Please refer to the COPYRIGHT file 
distributed with this source distribution.

This file is part of REDHAWK core.

REDHAWK core is free software: you can redistribute it and/or modify it under 
the terms of the GNU Lesser General Public License as published by the Free 
Software Foundation, either version 3 of the License, or (at your option) any 
later version.

REDHAWK core is distributed in the hope that it will be useful, but WITHOUT ANY 
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR 
A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more 
details.

You should have received a copy of the GNU Lesser General Public License along 
with this program.  If not, see http://www.gnu.org/licenses/.
-->

<!ELEMENT deviceconfiguration
	( description?
	, devicemanagersoftpkg
	, componentfiles?
	, partitioning?
	, connections?
	, domainmanager
	, filesystemnames?
	)>
<!ATTLIST deviceconfiguration
	id		ID	#REQUIRED
	name		CDATA	#IMPLIED>

<!ELEMENT description (#PCDATA)>

<!ELEMENT devicemanagersoftpkg
	( localfile
	)>

<!ELEMENT componentfiles 
	( componentfile+
	)>

<!ELEMENT componentfile
	( localfile 
	)>
<!ATTLIST componentfile
	id 		ID	#REQUIRED
	type		CDATA	#IMPLIED>

<!ELEMENT localfile EMPTY>
<!ATTLIST localfile
	name		CDATA	#REQUIRED>

<!ELEMENT partitioning 
	( componentplacement
	)*>

<!ELEMENT componentplacement 
	( componentfileref
	, deployondevice?
	, compositepartofdevice?
	, devicepkgfile?
	, componentinstantiation+
	)>

<!ELEMENT componentfileref  EMPTY>
<!ATTLIST componentfileref
	refid		CDATA	#REQUIRED>

<!ELEMENT deployondevice  EMPTY>
<!ATTLIST deployondevice
	refid		CDATA	#REQUIRED>

<!ELEMENT compositepartofdevice  EMPTY>
<!ATTLIST compositepartofdevice
	refid		CDATA	#REQUIRED>

<!ELEMENT devicepkgfile 
	(localfile
	)>
<!ATTLIST devicepkgfile
	type		CDATA	#IMPLIED>

<!ELEMENT componentinstantiation
	( usagename?
	 ,componentproperties?
         ,affinity?
         ,loggingconfig?
         ,deployerrequires?
	)>
<!ATTLIST componentinstantiation
    id  ID  #REQUIRED
    startorder CDATA #IMPLIED>

<!ELEMENT usagename (#PCDATA)>

<!ELEMENT loggingconfig (#PCDATA)>
<!ATTLIST loggingconfig 
          level CDATA #IMPLIED>

<!ELEMENT affinity
	( simpleref
	| simplesequenceref
	| structref
	| structsequenceref
	)+ >

<!ELEMENT deployerrequires
	( requires
	)+ >

<!ELEMENT componentproperties 
	( simpleref
	| simplesequenceref
	| structref
	| structsequenceref
	)+ >

<!ELEMENT devicethatloadedthiscomponentref EMPTY>
<!ATTLIST devicethatloadedthiscomponentref 
	refid		CDATA	#REQUIRED>

<!ELEMENT deviceusedbythiscomponentref EMPTY>
<!ATTLIST deviceusedbythiscomponentref 
	refid		CDATA	#REQUIRED
	usesrefid	CDATA	#REQUIRED>

<!ELEMENT requires EMPTY>
<!ATTLIST requires
	id		CDATA	#REQUIRED
	value		CDATA	#REQUIRED>

<!ELEMENT simpleref EMPTY>
<!ATTLIST simpleref
	refid		CDATA	#REQUIRED
	value		CDATA	#REQUIRED>
		
<!ELEMENT simplesequenceref
	(values
	)>
<!ATTLIST simplesequenceref
	refid		CDATA	#REQUIRED>

<!ELEMENT structref
	( (simpleref | simplesequenceref)+
	)>
<!ATTLIST structref
	refid		CDATA	#REQUIRED>

<!ELEMENT structsequenceref
	( structvalue+
	)>
<!ATTLIST structsequenceref
	refid		CDATA	#REQUIRED>

<!ELEMENT structvalue
	( (simpleref | simplesequenceref)+
	)>
		
<!ELEMENT values
	( value+ 
	)>
		
<!ELEMENT value (#PCDATA)>

<!ELEMENT componentinstantiationref EMPTY>
<!ATTLIST componentinstantiationref 
	refid	CDATA	#REQUIRED>

<!ELEMENT domainmanager
	( namingservice
	| stringifiedobjectref
	)>

<!ELEMENT findby
	( namingservice
	| stringifiedobjectref
	| domainfinder
	)>

<!ELEMENT namingservice EMPTY>
<!ATTLIST namingservice
	name		CDATA	#REQUIRED>

<!ELEMENT stringifiedobjectref (#PCDATA)>

<!ELEMENT domainfinder EMPTY>
<!ATTLIST domainfinder
	type		CDATA	#REQUIRED
	name		CDATA	#IMPLIED>

<!ELEMENT filesystemnames
	(filesystemname+
	)>

<!ELEMENT filesystemname EMPTY>
<!ATTLIST filesystemname
	mountname	CDATA	#REQUIRED
	deviceid	CDATA	#REQUIRED>

<!ELEMENT connections
      ( connectinterface*
      )>

<!ELEMENT connectinterface
	( usesport
	, ( providesport
	  | componentsupportedinterface
	  | findby
	  )
	)>

<!ATTLIST connectinterface
	id		ID	#IMPLIED>

<!ELEMENT usesport
	( usesidentifier
	, (componentinstantiationref
	   | devicethatloadedthiscomponentref
	   | deviceusedbythiscomponentref
	   | findby
	   )
	)>

<!ELEMENT usesidentifier (#PCDATA)>

<!ELEMENT providesport
	( providesidentifier
	, ( componentinstantiationref
	  | devicethatloadedthiscomponentref
	  | deviceusedbythiscomponentref
	  | findby
	  )
	)>

<!ELEMENT providesidentifier (#PCDATA)>

<!ELEMENT componentsupportedinterface
	( supportedidentifier
	, ( componentinstantiationref
	  | findby
	  )
	)>

<!ELEMENT supportedidentifier (#PCDATA)>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dev/nodes/test_affinity_node_socket/DeviceManager.dcd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE deviceconfiguration PUBLIC "-//JTRS//DTD SCA V2.2.2 DCD//EN" "deviceconfiguration.dtd">
<deviceconfiguration id="DCE:d4cbc8bd-d205-43b3-b35d-486c3e70bda0" name="test_affinity_node_socket">
  <devicemanagersoftpkg>
    <localfile name="/mgr/DeviceManager.spd.xml"/>
  </devicemanagersoftpkg>
  <componentfiles>
    <componentfile id="JavaTestDevice_50da4918-82fa-4085-a225-a6ca91cf7bc6" type="SPD">
      <localfile name="/devices/JavaTestDevice/JavaTestDevice.spd.xml"/>
    </componentfile>
    <componentfile id="GPP_7d34f027-5742-400d-b966-7dae5e0e7cae" type="SPD">
      <localfile name="/devices/GPP/GPP.spd.xml"/>
    </componentfile>
    <componentfile id="S1_f849a468-2ecf-47b0-8877-c54b38b9bfd0" type="SPD">
      <localfile name="/services/S1/S1.spd.xml"/>
    </componentfile>
  </componentfiles>
  <partitioning>
    <componentplacement>
      <componentfileref refid="JavaTestDevice_50da4918-82fa-4085-a225-a6ca91cf7bc6"/>
      <componentinstantiation id="test_affinity_node:JavaTest_Device_1">
        <usagename>JavaTestDevice_1</usagename>
      <affinity>
        <simpleref refid="affinity::exec_directive_class" value="cpu"/>
        <simpleref refid="affinity::exec_directive_value" value="8,9,10"/>
      </affinity>
      </componentinstantiation>
    </componentplacement>
    <componentplacement>
      <componentfileref refid="GPP_7d34f027-5742-400d-b966-7dae5e0e7cae"/>
      <componentinstantiation id="test_affinity_node:GPP_1">
        <usagename>GPP_1</usagename>
        <componentproperties>
          <structref refid="thresholds">
            <simpleref refid="cpu_idle" value="2"/>
            <simpleref refid="mem_free" value="100"/>
            <simpleref refid="nic_usage" value="900"/>
          </structref>
          <structref refid="affinity">
            <simpleref refid="affinity::blacklist_cpus" value="0"/>
            <simpleref refid="affinity::force_override" value="false"/>
            <simpleref refid="affinity::exec_directive_class" value="socket"/>
            <simpleref refid="affinity::exec_directive_value" value="0"/>
            <simpleref refid="affinity::deploy_per_socket" value="true"/>
            <simpleref refid="affinity::disabled" value="false"/>
          </structref>
        </componentproperties>
      <affinity>
        <simpleref refid="affinity::exec_directive_class" value="socket"/>
        <simpleref refid="affinity::exec_directive_value" value="0"/>
      </affinity>
      </componentinstantiation>
    </componentplacement>
    <componentplacement>
      <componentfileref refid="S1_f849a468-2ecf-47b0-8877-c54b38b9bfd0"/>
      <componentinstantiation id="test_affinity_node:S1_1">
        <usagename>S1_1</usagename>
      <affinity>
        <simpleref refid="affinity::exec_directive_class" value="socket"/>
        <simpleref refid="affinity::exec_directive_value" value="0"/>
      </affinity>
      </componentinstantiation>
    </componentplacement>
  </partitioning>
  <domainmanager>
    <namingservice name="REDHAWK_DEV/REDHAWK_DEV"/>
  </domainmanager>
</deviceconfiguration>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dev/nodes/SimpleDevMgr/DeviceManager.dcd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
This file is protected by Copyright. Please refer to the COPYRIGHT file 
distributed with this source distribution.

This file is part of REDHAWK core.

REDHAWK core is free software: you can redistribute it and/or modify it under 
the terms of the GNU Lesser General Public License as published by the Free 
Software Foundation, either version 3 of the License, or (at your option) any 
later version.

REDHAWK core is distributed in the hope that it will be useful, but WITHOUT ANY 
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR 
A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more 
details.

You should have received a copy of the GNU Lesser General Public License along 
with this program.  If not, see http://www.gnu.org/licenses/.
-->

<!DOCTYPE deviceconfiguration PUBLIC "-//JTRS//DTD SCA V2.2.2 DCD//EN" "deviceconfiguration.dtd">
<!-- Created with REDHAWK IDE-->
<!-- Powered by Eclipse -->
<deviceconfiguration name="SimpleDevMgr" id="DCE:cbdaf8db-097a-49cc-9fa3-e4c34b077485">
    <devicemanagersoftpkg>
    	<localfile name="/mgr/DeviceManager.spd.xml">
    	</localfile>
    </devicemanagersoftpkg>
    <componentfiles>
    	<componentfile type="SPD" id="SimpleDevice_938e5cd6-0d37-46ef-a2a8-348f17dbcbe3">
    		<localfile name="/devices/SimpleDevice/SimpleDevice.spd.xml">
    		</localfile>
    	</componentfile>
    </componentfiles>
    <partitioning>
		<componentplacement>
	    	<componentfileref refid="SimpleDevice_938e5cd6-0d37-46ef-a2a8-348f17dbcbe3">
    		</componentfileref>
	     	<componentinstantiation id="DCE:a3c74ad2-61ea-4ade-8b55-61c36a54f17d">
	     		<usagename>SimpleDevice_1</usagename>
	     	</componentinstantiation>
    	</componentplacement>
    </partitioning>
    <domainmanager>
    	<namingservice name="REDHAWK_DEV/REDHAWK_DEV">
    	</namingservice>
    </domainmanager>
</deviceconfiguration>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dev/nodes/dev_kill_devmgr_node/DeviceManager.dcd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
This file is protected by Copyright. Please refer to the COPYRIGHT file
distributed with this source distribution.

This file is part of REDHAWK core.

REDHAWK core is free software: you can redistribute it and/or modify it under
the terms of the GNU Lesser General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version.

REDHAWK core is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more
details.

You should have received a copy of the GNU Lesser General Public License along
with this program.  If not, see http://www.gnu.org/licenses/.
-->
<!DOCTYPE deviceconfiguration PUBLIC "-//JTRS//DTD SCA V2.2.2 DCD//EN" "deviceconfiguration.dtd">
<deviceconfiguration id="DCE:1a0cafac-270b-4997-befc-c7a1308e0fa2" name="dev_kill_devmgr_node">
  <devicemanagersoftpkg>
    <localfile name="/mgr/DeviceManager.spd.xml"/>
  </devicemanagersoftpkg>
  <componentfiles>
    <componentfile id="dev_kill_devmgr_ee1f4f5c-4457-496d-ab18-05ed7e6d30a6" type="SPD">
      <localfile name="/devices/dev_kill_devmgr/dev_kill_devmgr.spd.xml"/>
    </componentfile>
  </componentfiles>
  <partitioning>
    <componentplacement>
      <componentfileref refid="dev_kill_devmgr_ee1f4f5c-4457-496d-ab18-05ed7e6d30a6"/>
      <componentinstantiation id="dev_kill_devmgr_node:dev_kill_devmgr_1">
        <usagename>dev_kill_devmgr_1</usagename>
      </componentinstantiation>
    </componentplacement>
  </partitioning>
  <domainmanager>
    <namingservice name="REDHAWK_DEV/REDHAWK_DEV"/>
  </domainmanager>
</deviceconfiguration>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dev/nodes/log_test_cpp_node/DeviceManager.dcd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE deviceconfiguration PUBLIC "-//JTRS//DTD SCA V2.2.2 DCD//EN" "deviceconfiguration.dtd">
<deviceconfiguration id="DCE:e354ccc3-49a7-4c1f-a683-df3534624558" name="log_test_cpp_node">
  <devicemanagersoftpkg>
    <localfile name="/mgr/DeviceManager.spd.xml"/>
  </devicemanagersoftpkg>
  <componentfiles>
    <componentfile id="log_test_cpp_1cf048bd-af8b-4719-bb2a-1e26b3a4dd95" type="SPD">
      <localfile name="/devices/log_test_cpp/log_test_cpp.spd.xml"/>
    </componentfile>
  </componentfiles>
  <partitioning>
    <componentplacement>
      <componentfileref refid="log_test_cpp_1cf048bd-af8b-4719-bb2a-1e26b3a4dd95"/>
      <componentinstantiation id="log_test_cpp_node:log_test_cpp_1">
        <usagename>log_test_cpp_1</usagename>
      </componentinstantiation>
    </componentplacement>
    <componentplacement>
      <componentfileref refid="log_test_cpp_1cf048bd-af8b-4719-bb2a-1e26b3a4dd95"/>
      <componentinstantiation id="log_test_cpp_node:log_test_cpp_2">
        <usagename>log_test_cpp_2</usagename>
      </componentinstantiation>
    </componentplacement>
  </partitioning>
  <domainmanager>
    <namingservice name="REDHAWK_DEV/REDHAWK_DEV"/>
  </domainmanager>
</deviceconfiguration>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/parser_tests/affinity.dcd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE deviceconfiguration PUBLIC "-//JTRS//DTD SCA V2.2.2 DCD//EN" "deviceconfiguration.dtd">
<deviceconfiguration id="affinity_parse_1" name="test_affinity_node_socket">
  <devicemanagersoftpkg>
    <localfile name="/mgr/DeviceManager.spd.xml"/>
  </devicemanagersoftpkg>
  <componentfiles>
    <componentfile id="GPP_File_1" type="SPD">
      <localfile name="/devices/GPP/GPP.spd.xml"/>
    </componentfile>
  </componentfiles>
  <partitioning>
    <componentplacement>
      <componentfileref refid="GPP_File_1"/>
      <componentinstantiation id="test_affinity_node:GPP_1">
        <usagename>GPP_1</usagename>
        <componentproperties>
          <structref refid="thresholds">
            <simpleref refid="cpu_idle" value="2"/>
            <simpleref refid="mem_free" value="100"/>
            <simpleref refid="nic_usage" value="900"/>
          </structref>
          <structref refid="affinity">
            <simpleref refid="affinity::blacklist_cpus" value="0"/>
            <simpleref refid="affinity::force_override" value="false"/>
            <simpleref refid="affinity::exec_directive_class" value="socket"/>
            <simpleref refid="affinity::exec_directive_value" value="0"/>
            <simpleref refid="affinity::deploy_per_socket" value="true"/>
            <simpleref refid="affinity::disabled" value="false"/>
          </structref>
        </componentproperties>
      <affinity>
        <simpleref refid="affinity::exec_directive_class" value="socket"/>
        <simpleref refid="affinity::exec_directive_value" value="0"/>
      </affinity>
      </componentinstantiation>
    </componentplacement>
  </partitioning>
  <domainmanager>
    <namingservice name="REDHAWK_DEV/REDHAWK_DEV"/>
  </domainmanager>
</deviceconfiguration>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dev/nodes/test_NicAllocation_node/DeviceManager.dcd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE deviceconfiguration PUBLIC "-//JTRS//DTD SCA V2.2.2 DCD//EN" "deviceconfiguration.dtd">
<deviceconfiguration id="DCE:abfb329b-3d6e-49d8-bb86-b170da53f1ab" name="test_NicAllocation_node">
  <devicemanagersoftpkg>
    <localfile name="/mgr/DeviceManager.spd.xml"/>
  </devicemanagersoftpkg>
  <componentfiles>
    <componentfile id="NicExecDevice_6f4afa68-38fe-4a7f-a497-abfccea86553" type="SPD">
      <localfile name="/devices/NicExecDevice/NicExecDevice.spd.xml"/>
    </componentfile>
  </componentfiles>
  <partitioning>
    <componentplacement>
      <componentfileref refid="NicExecDevice_6f4afa68-38fe-4a7f-a497-abfccea86553"/>
      <componentinstantiation id="test_NicAllocation_node:NicExecDevice_1">
        <usagename>NicExecDevice_1</usagename>
        <componentproperties>
          <simplesequenceref refid="nic_list">
            <values>
              <value>eth0</value>
              <value>eth1</value>
              <value>eth2</value>
            </values>
          </simplesequenceref>
        </componentproperties>
      </componentinstantiation>
    </componentplacement>
  </partitioning>
  <domainmanager>
    <namingservice name="REDHAWK_DEV/REDHAWK_DEV"/>
  </domainmanager>
</deviceconfiguration>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dev/nodes/log_test_java_node/DeviceManager.dcd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE deviceconfiguration PUBLIC "-//JTRS//DTD SCA V2.2.2 DCD//EN" "deviceconfiguration.dtd">
<deviceconfiguration id="DCE:6d36c876-3513-4a65-a133-318e56d3e323" name="log_test_java_node">
  <devicemanagersoftpkg>
    <localfile name="/mgr/DeviceManager.spd.xml"/>
  </devicemanagersoftpkg>
  <componentfiles>
    <componentfile id="log_test_java_7d5780dd-b830-4be5-9ed5-b97e8b329f52" type="SPD">
      <localfile name="/devices/log_test_java/log_test_java.spd.xml"/>
    </componentfile>
  </componentfiles>
  <partitioning>
    <componentplacement>
      <componentfileref refid="log_test_java_7d5780dd-b830-4be5-9ed5-b97e8b329f52"/>
      <componentinstantiation id="log_test_java_node:log_test_java_1">
        <usagename>log_test_java_1</usagename>
      </componentinstantiation>
    </componentplacement>
    <componentplacement>
      <componentfileref refid="log_test_java_7d5780dd-b830-4be5-9ed5-b97e8b329f52"/>
      <componentinstantiation id="log_test_java_node:log_test_java_2">
        <usagename>log_test_java_2</usagename>
      </componentinstantiation>
    </componentplacement>
  </partitioning>
  <domainmanager>
    <namingservice name="REDHAWK_DEV/REDHAWK_DEV"/>
  </domainmanager>
</deviceconfiguration>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dev/nodes/test_HardFail_nodeB/DeviceManager.dcd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
This file is protected by Copyright. Please refer to the COPYRIGHT file 
distributed with this source distribution.

This file is part of REDHAWK core.

REDHAWK core is free software: you can redistribute it and/or modify it under 
the terms of the GNU Lesser General Public License as published by the Free 
Software Foundation, either version 3 of the License, or (at your option) any 
later version.

REDHAWK core is distributed in the hope that it will be useful, but WITHOUT ANY 
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR 
A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more 
details.

You should have received a copy of the GNU Lesser General Public License along 
with this program.  If not, see http://www.gnu.org/licenses/.
-->

<!DOCTYPE deviceconfiguration PUBLIC '-//JTRS//DTD SCA V2.2.2 DCD//EN' 'deviceconfiguration.dtd'>
<deviceconfiguration name="HardFail_nodeB" id="DCE:f8428d15-180b-4579-932c-9d85d5763054">
    <devicemanagersoftpkg>
        <localfile name="/mgr/DeviceManager.spd.xml"/>
    </devicemanagersoftpkg>
    <componentfiles>
        <!--Device Definitions--> 
        <componentfile type="SPD" id="BasicTestDevice1_c6e250b8-5223-11db-9fc4-000d56d8556e">
            <localfile name="/devices/BasicTestDevice/BasicTestDevice.spd.xml"/>
        </componentfile>
    </componentfiles>
    <partitioning>
        <componentplacement>
            <componentfileref refid="BasicTestDevice1_c6e250b8-5223-11db-9fc4-000d56d8556e"/>
            <componentinstantiation id="DCE:a91535f6-212a-4768-a292-7727025a8729">
            <!--componentinstantiation id="DCE:8f3478e3-626e-45c3-bd01-0a8117dbe59b"-->
            <!--componentinstantiation id="DCE:cdffec5c-5223-11db-9502-000d56d8556e"-->
                <usagename>BasicTestDevice2</usagename> 
		<componentproperties>
		    <simpleref refid="DCE:6b298d70-6735-43f2-944d-06f754cd4eb9" value="BasicTestDevice1_no_default_prop"/>
		    <simpleref refid="DCE:456310b2-7d2f-40f5-bfef-9fdf4f3560ea" value="BasicTestDevice1_default_prop"/>
		    <simpleref refid="DCE:c03e148f-e9f9-4d70-aa00-6e23d33fa648" value="path/to/some/config/file"/>
		    <simpleref refid="DCE:6f5881b3-433e-434b-8204-d39c89ff4be2" value="DefaultValueNoGood"/>
		    <simpleref refid="DCE:716ea1c4-059a-4b18-8b66-74804bd8d435" value="OverloadedTheImplementationSpecific"/>
		    <structref refid="DCE:ffe634c9-096d-425b-86cc-df1cce50612f">
			<simpleref refid="item1" value="the new value"/>
			<simpleref refid="item2" value="400"/>
			<simpleref refid="item3" value="1.414"/>
		    </structref>
		</componentproperties>
            </componentinstantiation>
        </componentplacement>
    </partitioning>
    <domainmanager>
        <namingservice name="DomainName1/DomainManager"/>
    </domainmanager>
</deviceconfiguration>
