=== RedhawkSDR/core-framework/redhawk/src/xml/dtd/properties.dtd
<!--
This file is protected by Copyright. Please refer to the COPYRIGHT file 
distributed with this source distribution.

This file is part of REDHAWK core.

REDHAWK core is free software: you can redistribute it and/or modify it under 
the terms of the GNU Lesser General Public License as published by the Free 
Software Foundation, either version 3 of the License, or (at your option) any 
later version.

REDHAWK core is distributed in the hope that it will be useful, but WITHOUT ANY 
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR 
A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more 
details.

You should have received a copy of the GNU Lesser General Public License along 
with this program.  If not, see http://www.gnu.org/licenses/.
-->

<!ELEMENT properties
     	 ( description?
     	 , 	( simple
		| simplesequence
		| test
		| struct
		| structsequence)*
       )> 

<!ELEMENT simple 
	( description?
	, value?
	, units?
	, range?
	, enumerations?
	, kind*
	, action?
	)>

<!-- Support non-SCA compliant longlong -->
<!ATTLIST simple
	id	ID							#REQUIRED
	type	( boolean	| char	| double | float
		| short	| long	| longlong | objref | octet
		| string	| ulong | ulonglong	| ushort | utctime )		#REQUIRED
	name	CDATA							#IMPLIED
	complex ( false | true ) "false"
	commandline ( false | true ) "false"
	optional ( false | true ) "false"
	mode	( readonly	| readwrite | writeonly)	"readwrite">

<!ELEMENT description (#PCDATA)>

<!ELEMENT value (#PCDATA)>

<!ELEMENT units (#PCDATA)>

<!ELEMENT range EMPTY>
<!ATTLIST range
	min		CDATA	#REQUIRED
	max		CDATA	#REQUIRED>

<!ELEMENT enumerations
	( enumeration+
	)>

<!ELEMENT enumeration EMPTY>
<!ATTLIST enumeration
	label		CDATA	#REQUIRED
	value		CDATA	#IMPLIED>

<!ELEMENT kind EMPTY>
<!ATTLIST kind
	kindtype	(allocation | property | configure | test | execparam | factoryparam | event | message) 
"configure">

<!ELEMENT action EMPTY>
<!ATTLIST action
	type	( eq  | ne | gt  |  lt | ge | le | external ) "external">

<!ELEMENT simplesequence 
	( description?
	, values?
	, units?
	, range?
	, kind*
	, action?
	)>
<!ATTLIST simplesequence
	id	ID						#REQUIRED
	type  ( boolean | char   | double | float
	      | short  | long | longlong   | objref | octet
	      | string | ulong | ulonglong | ushort | utctime )		#REQUIRED
	name	CDATA						#IMPLIED
	complex ( false | true ) "false"
	optional ( false | true ) "false"
	mode	(readonly | readwrite | writeonly)	"readwrite">

<!ELEMENT values
	( value+ 
	)>

<!ELEMENT test 
	( description
      , inputValue?
	, resultValue
	)>
<!ATTLIST test
	id		CDATA #REQUIRED>

<!ELEMENT inputValue
	( simple+
	)>

<!ELEMENT resultValue
	( simple+
	)>

<!ELEMENT struct 
	( description?
	, (simple | simplesequence)+
	, configurationkind*
	)>
<!ATTLIST struct
	id		ID	#REQUIRED
	name		CDATA	#IMPLIED
	mode		(readonly | readwrite | writeonly)  "readwrite">

<!ELEMENT configurationkind EMPTY>
<!ATTLIST configurationkind
	kindtype	(allocation | property | configure | test | factoryparam | event | message  )
"configure">

<!ELEMENT structsequence
	( description?
	, struct
	, structvalue*
	, configurationkind*
	)>
<!ATTLIST structsequence
	id       	ID	#REQUIRED
	name		CDATA	#IMPLIED
	mode		(readonly | readwrite | writeonly)  "readwrite">
		
<!ELEMENT structvalue
	( (simpleref | simplesequenceref)+	        
	)>
		
<!ELEMENT simpleref EMPTY>
<!ATTLIST simpleref
	refid 	CDATA	#REQUIRED
	value 	CDATA	#REQUIRED>

<!ELEMENT simplesequenceref
        ( values
        )>
<!ATTLIST simplesequenceref
        refid   CDATA   #REQUIRED>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dev/devices/nocmdline_dev/nocmdline_dev.prf.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE properties PUBLIC "-//JTRS//DTD SCA V2.2.2 PRF//EN" "properties.dtd">
<properties>
  <simple id="DCE:cdc5ee18-7ceb-4ae6-bf4c-31f983179b4d" mode="readonly" name="device_kind" type="string">
    <description>This specifies the device kind</description>
    <kind kindtype="allocation"/>
    <action type="eq"/>
  </simple>
  <simple id="DCE:0f99b2e4-9903-4631-9846-ff349d18ecfb" mode="readonly" name="device_model" type="string">
    <description> This specifies the specific device</description>
    <kind kindtype="allocation"/>
    <action type="eq"/>
  </simple>
  <simple id="testprop" mode="readwrite" type="string">
    <kind kindtype="property"/>
    <action type="external"/>
  </simple>
</properties>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dom/components/TestComplexProps/TestComplexProps.prf.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
This file is protected by Copyright. Please refer to the COPYRIGHT file
distributed with this source distribution.

This file is part of REDHAWK core.

REDHAWK core is free software: you can redistribute it and/or modify it under
the terms of the GNU Lesser General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version.

REDHAWK core is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more
details.

You should have received a copy of the GNU Lesser General Public License along
with this program.  If not, see http://www.gnu.org/licenses/.
-->
<!DOCTYPE properties PUBLIC "-//JTRS//DTD SCA V2.2.2 PRF//EN" "properties.dtd">
<properties>
  <simple id="complexBooleanProp" mode="readwrite" type="boolean" complex="true">
    <value>0+j1</value>
    <kind kindtype="property"/>
    <action type="external"/>
  </simple>
  <simple id="complexULongProp" mode="readwrite" type="ulong" complex="true">
    <value>4+j5</value>
    <kind kindtype="property"/>
    <action type="external"/>
  </simple>
  <simple id="complexShortProp" mode="readwrite" type="short" complex="true">
    <value>4+j5</value>
    <kind kindtype="property"/>
    <action type="external"/>
  </simple>
  <simple id="complexFloatProp" mode="readwrite" type="float" complex="true">
    <value>4+j5</value>
    <kind kindtype="property"/>
    <action type="external"/>
  </simple>
  <simple id="complexOctetProp" mode="readwrite" type="octet" complex="true">
    <value>4+j5</value>
    <kind kindtype="property"/>
    <action type="external"/>
  </simple>
  <simple id="complexUShort" mode="readwrite" type="ushort" complex="true">
    <value>4+j5</value>
    <kind kindtype="property"/>
    <action type="external"/>
  </simple>
  <simple id="complexDouble" mode="readwrite" type="double" complex="true">
    <value>4+j5</value>
    <kind kindtype="property"/>
    <action type="external"/>
  </simple>
  <simple id="complexLong" mode="readwrite" type="long" complex="true">
    <value>4+j5</value>
    <kind kindtype="property"/>
    <action type="external"/>
  </simple>
  <simple id="complexLongLong" mode="readwrite" type="longlong" complex="true">
    <value>4+j5</value>
    <kind kindtype="property"/>
    <action type="external"/>
  </simple>
  <simple id="complexULongLong" mode="readwrite" type="ulonglong" complex="true">
    <value>4+j5</value>
    <kind kindtype="property"/>
    <action type="external"/>
  </simple>

  <simplesequence id="complexFloatSequence" mode="readwrite" type="float" complex="true">
    <values>
      <value>6+j7</value>
      <value>4+j5</value>
      <value>8+j9</value>
    </values>
    <kind kindtype="property"/>
    <action type="external"/>
  </simplesequence>
  <struct id="FloatStruct" mode="readwrite">
    <simple id="FloatStructMember" mode="readwrite" type="float">
      <value>6</value>
      <kind kindtype="property"/>
      <action type="external"/>
    </simple>
    <configurationkind kindtype="property"/>
  </struct>
 
  <struct id="complexFloatStruct" mode="readwrite">
    <simple id="complexFloatStructMember" mode="readwrite" type="float" complex="true">
      <value>6+j7</value>
      <kind kindtype="property"/>
      <action type="external"/>
    </simple>
    <simplesequence id="complexFloatStruct::complex_float_seq" name="complex_float_seq" type="float" complex="true">
      <values>
        <value>3+j4</value>
      </values>
    </simplesequence>
    <configurationkind kindtype="property"/>
  </struct>
  <structsequence id="FloatStructSequence" mode="readwrite">
    <struct id="FloatStructSequenceMember">
      <simple id="FloatStructSequenceMemberMemember" type="float">
        <value>6</value>
      </simple>
      <simplesequence id="FloatStructSequence::float_seq" name="float_seq" type="float">
        <values>
          <value>3</value>
        </values>
      </simplesequence>
    </struct>
    <configurationkind kindtype="property"/>
  </structsequence>
  <structsequence id="complexFloatStructSequence" mode="readwrite">
    <struct id="complexFloatStructSequenceMember">
      <simple id="complexFloatStructSequenceMemberMemember" type="float" complex="true"/>
      <simplesequence id="complexFloatStructSequence::complex_float_seq" name="complex_float_seq" type="float" complex="true"/>
    </struct>
    <structvalue>
      <simpleref refid="complexFloatStructSequenceMemberMemember" value="9+j4"/>
      <simplesequenceref refid="complexFloatStructSequence::complex_float_seq">
        <values>
          <value>6+j5</value>
        </values>
      </simplesequenceref>
    </structvalue>
    <configurationkind kindtype="property"/>
  </structsequence>
</properties>

=== RedhawkSDR/core-framework/codegenTesting/sdr/dom/components/EnumTest/EnumTest.prf.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
This file is protected by Copyright. Please refer to the COPYRIGHT file
distributed with this source distribution.

This file is part of REDHAWK codegenTesting.

REDHAWK codegenTesting is free software: you can redistribute it and/or modify it under
the terms of the GNU Lesser General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version.

REDHAWK codegenTesting is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more
details.

You should have received a copy of the GNU Lesser General Public License along
with this program.  If not, see http://www.gnu.org/licenses/.
-->
<!DOCTYPE properties PUBLIC "-//JTRS//DTD SCA V2.2.2 PRF//EN" "properties.dtd">
<properties>
  <simple id="floatenum" mode="readwrite" type="float">
    <value>0.0</value>
    <enumerations>
      <enumeration label="DEFAULT" value="0.0"/>
      <enumeration label="OTHER" value="1.0"/>
    </enumerations>
    <kind kindtype="property"/>
    <action type="external"/>
  </simple>
  <simple id="stringenum" mode="readwrite" type="string">
    <value>start</value>
    <enumerations>
      <enumeration label="START" value="start"/>
      <enumeration label="STOPPED" value="stopped"/>
    </enumerations>
    <kind kindtype="property"/>
    <action type="external"/>
  </simple>
  <struct id="structprop" mode="readwrite">
    <simple id="structprop::number" name="number" type="long">
      <enumerations>
        <enumeration label="ZERO" value="0"/>
        <enumeration label="ONE" value="1"/>
        <enumeration label="TWO" value="2"/>
      </enumerations>
    </simple>
    <simple id="structprop::alpha" name="alpha" type="string">
      <enumerations>
        <enumeration label="ABC" value="abc"/>
        <enumeration label="DEF" value="def"/>
      </enumerations>
    </simple>
    <configurationkind kindtype="property"/>
  </struct>
  <structsequence id="structseq" mode="readwrite">
    <struct id="structseq_struct">
      <simple id="structseq::number" name="number" type="long">
        <value>0</value>
        <enumerations>
          <enumeration label="POSITIVE" value="1"/>
          <enumeration label="ZERO" value="0"/>
          <enumeration label="NEGATIVE" value="-1"/>
        </enumerations>
      </simple>
      <simple id="structseq::text" name="text" type="string">
        <value>body</value>
        <enumerations>
          <enumeration label="HEADER" value="header"/>
          <enumeration label="BODY" value="body"/>
          <enumeration label="FOOTER" value="footer"/>
        </enumerations>
      </simple>
    </struct>
    <configurationkind kindtype="property"/>
  </structsequence>
</properties>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dom/components/TestCppProps/TestCppProps.prf.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
This file is protected by Copyright. Please refer to the COPYRIGHT file 
distributed with this source distribution.

This file is part of REDHAWK core.

REDHAWK core is free software: you can redistribute it and/or modify it under 
the terms of the GNU Lesser General Public License as published by the Free 
Software Foundation, either version 3 of the License, or (at your option) any 
later version.

REDHAWK core is distributed in the hope that it will be useful, but WITHOUT ANY 
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR 
A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more 
details.

You should have received a copy of the GNU Lesser General Public License along 
with this program.  If not, see http://www.gnu.org/licenses/.
-->

<!DOCTYPE properties PUBLIC "-//JTRS//DTD SCA V2.2.2 PRF//EN" "properties.dtd">
<properties>
  <simple id="DCE:9d1e3621-27ca-4cd0-909d-90b7448b8f71" mode="readwrite" name="prop_long" type="long">
    <kind kindtype="configure"/>
    <action type="external"/>
  </simple>
  <simple id="DCE:4e7c1977-5f53-4061-bae7-cb8c1072f4b7" mode="readwrite" name="prop_str" type="string">
    <value>default value</value>
    <kind kindtype="configure"/>
    <action type="external"/>
  </simple>
  <simple id="simple_utctime" mode="readwrite" type="utctime">
    <value>2017:2:1::12:01:00.123</value>
    <kind kindtype="property"/>
    <action type="external"/>
  </simple>
  <simple id="reset_utctime" mode="readwrite" type="boolean">
    <value>false</value>
    <kind kindtype="property"/>
    <action type="external"/>
  </simple>
  <simplesequence id="seq_utctime" mode="readwrite" type="utctime">
      <values>
        <value>2010:2:1::12:01:00.123</value>
        <value>2011:2:1::12:01:00.123</value>
      </values>
    <kind kindtype="property"/>
    <action type="external"/>
  </simplesequence>
  <simplesequence id="DCE:f877b9ee-a682-43a6-ba21-5ea980167f55" mode="readwrite" name="seq_oct" type="short">
    <kind kindtype="configure"/>
    <action type="external"/>
  </simplesequence>
  <structsequence id="DCE:e415de60-68cb-403e-812e-76f114731bb4" mode="readwrite" name="prop_foo">
    <struct id="">
      <simple id="item_bool" mode="readwrite" type="boolean">
        <kind kindtype="configure"/>
        <action type="external"/>
      </simple>
      <simple id="item_string" mode="readwrite" type="string">
        <kind kindtype="configure"/>
        <action type="external"/>
      </simple>
      <configurationkind kindtype="configure"/>
    </struct>
    <structvalue>
      <simpleref refid="item_bool" value="false"/>
      <simpleref refid="item_string" value="First"/>
    </structvalue>
    <structvalue>
      <simpleref refid="item_bool" value="true"/>
      <simpleref refid="item_string" value="Second"/>
    </structvalue>
    <configurationkind kindtype="configure"/>
  </structsequence> 
  <simple id="readOnly" mode="readonly" name="readOnly" type="string">
    <value>empty</value>
    <kind kindtype="property"/>
    <action type="external"/>
  </simple>
</properties>
