=== RedhawkSDR/core-framework/redhawk/src/xml/dtd/properties.dtd
<!--
This file is protected by Copyright. Please refer to the COPYRIGHT file 
distributed with this source distribution.

This file is part of REDHAWK core.

REDHAWK core is free software: you can redistribute it and/or modify it under 
the terms of the GNU Lesser General Public License as published by the Free 
Software Foundation, either version 3 of the License, or (at your option) any 
later version.

REDHAWK core is distributed in the hope that it will be useful, but WITHOUT ANY 
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR 
A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more 
details.

You should have received a copy of the GNU Lesser General Public License along 
with this program.  If not, see http://www.gnu.org/licenses/.
-->

<!ELEMENT properties
     	 ( description?
     	 , 	( simple
		| simplesequence
		| test
		| struct
		| structsequence)*
       )> 

<!ELEMENT simple 
	( description?
	, value?
	, units?
	, range?
	, enumerations?
	, kind*
	, action?
	)>

<!-- Support non-SCA compliant longlong -->
<!ATTLIST simple
	id	ID							#REQUIRED
	type	( boolean	| char	| double | float
		| short	| long	| longlong | objref | octet
		| string	| ulong | ulonglong	| ushort | utctime )		#REQUIRED
	name	CDATA							#IMPLIED
	complex ( false | true ) "false"
	commandline ( false | true ) "false"
	optional ( false | true ) "false"
	mode	( readonly	| readwrite | writeonly)	"readwrite">

<!ELEMENT description (#PCDATA)>

<!ELEMENT value (#PCDATA)>

<!ELEMENT units (#PCDATA)>

<!ELEMENT range EMPTY>
<!ATTLIST range
	min		CDATA	#REQUIRED
	max		CDATA	#REQUIRED>

<!ELEMENT enumerations
	( enumeration+
	)>

<!ELEMENT enumeration EMPTY>
<!ATTLIST enumeration
	label		CDATA	#REQUIRED
	value		CDATA	#IMPLIED>

<!ELEMENT kind EMPTY>
<!ATTLIST kind
	kindtype	(allocation | property | configure | test | execparam | factoryparam | event | message) 
"configure">

<!ELEMENT action EMPTY>
<!ATTLIST action
	type	( eq  | ne | gt  |  lt | ge | le | external ) "external">

<!ELEMENT simplesequence 
	( description?
	, values?
	, units?
	, range?
	, kind*
	, action?
	)>
<!ATTLIST simplesequence
	id	ID						#REQUIRED
	type  ( boolean | char   | double | float
	      | short  | long | longlong   | objref | octet
	      | string | ulong | ulonglong | ushort | utctime )		#REQUIRED
	name	CDATA						#IMPLIED
	complex ( false | true ) "false"
	optional ( false | true ) "false"
	mode	(readonly | readwrite | writeonly)	"readwrite">

<!ELEMENT values
	( value+ 
	)>

<!ELEMENT test 
	( description
      , inputValue?
	, resultValue
	)>
<!ATTLIST test
	id		CDATA #REQUIRED>

<!ELEMENT inputValue
	( simple+
	)>

<!ELEMENT resultValue
	( simple+
	)>

<!ELEMENT struct 
	( description?
	, (simple | simplesequence)+
	, configurationkind*
	)>
<!ATTLIST struct
	id		ID	#REQUIRED
	name		CDATA	#IMPLIED
	mode		(readonly | readwrite | writeonly)  "readwrite">

<!ELEMENT configurationkind EMPTY>
<!ATTLIST configurationkind
	kindtype	(allocation | property | configure | test | factoryparam | event | message  )
"configure">

<!ELEMENT structsequence
	( description?
	, struct
	, structvalue*
	, configurationkind*
	)>
<!ATTLIST structsequence
	id       	ID	#REQUIRED
	name		CDATA	#IMPLIED
	mode		(readonly | readwrite | writeonly)  "readwrite">
		
<!ELEMENT structvalue
	( (simpleref | simplesequenceref)+	        
	)>
		
<!ELEMENT simpleref EMPTY>
<!ATTLIST simpleref
	refid 	CDATA	#REQUIRED
	value 	CDATA	#REQUIRED>

<!ELEMENT simplesequenceref
        ( values
        )>
<!ATTLIST simplesequenceref
        refid   CDATA   #REQUIRED>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dev/devices/CrashableExecutableDevice/CrashableExecutableDevice.prf.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
This file is protected by Copyright. Please refer to the COPYRIGHT file 
distributed with this source distribution.

This file is part of REDHAWK core.

REDHAWK core is free software: you can redistribute it and/or modify it under 
the terms of the GNU Lesser General Public License as published by the Free 
Software Foundation, either version 3 of the License, or (at your option) any 
later version.

REDHAWK core is distributed in the hope that it will be useful, but WITHOUT ANY 
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR 
A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more 
details.

You should have received a copy of the GNU Lesser General Public License along 
with this program.  If not, see http://www.gnu.org/licenses/.
-->

<!DOCTYPE properties PUBLIC '-//JTRS//DTD SCA V2.2.2 PRF//EN' 'properties.dtd'>
<properties>
    <!-- Provide a processor_name and os_name matching property -->
    <simple id="DCE:4a23ad60-0b25-4121-a630-68803a498f75"
            name="os_name"
            mode="readonly"
            type="string">
        <description>
            SCA required property describing the Operating Syste
        </description>
        <value>Linux</value>
        <kind kindtype="allocation"/>
        <action type="eq"/>
    </simple>
    <simple id="DCE:fefb9c66-d14a-438d-ad59-2cfd1adb272b"
            name="processor_name"
            mode="readonly"
            type="string">
        <description>
            SCA required property describing the CPU type
        </description>
        <value>x86</value>
        <kind kindtype="allocation"/>
        <action type="eq"/>
    </simple>
    <!-- DeviceKind extension -->
    <simple id="DCE:7f36cdfb-f828-4e4f-b84f-446e17f1a85b"
            name="DeviceKind"
            mode="readonly"
            type="string">
        <description>
            The type of this device...see D.4.1.17
        </description>
        <value>CrashableExecutableDevice</value>
        <kind kindtype="allocation"/>
        <action type="eq"/>
    </simple>
    <!-- Allocatable capacity -->
    <simple id="DCE:5636c210-0346-4df7-a5a3-8fd34c5540a8"
            name="BogoMipsCapacity"
            mode="readonly"
            type="long">
        <description>
            Amount of BogoMips provided by the machine.
        </description>
	<units>bogomips</units>
        <kind kindtype="allocation"/>
    </simple>
    <simple id="crashEnabled" mode="readwrite" type="boolean">
        <value>false</value>
        <kind kindtype="configure"/>
        <action type="external"/>
    </simple>
</properties>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dom/components/time_cp_now/time_cp_now.prf.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE properties PUBLIC "-//JTRS//DTD SCA V2.2.2 PRF//EN" "properties.dtd">
<properties>
  <simple id="rightnow" mode="readwrite" type="utctime">
    <value>now</value>
    <kind kindtype="property"/>
    <action type="external"/>
  </simple>
  <simple id="simple1970" mode="readwrite" type="utctime">
    <value>1970:01:01::00:00:00</value>
    <kind kindtype="property"/>
    <action type="external"/>
  </simple>
  <simplesequence id="simpleSeqDefNow" mode="readwrite" type="utctime">
    <values>
      <value>now</value>
    </values>
    <kind kindtype="property"/>
    <action type="external"/>
  </simplesequence>
  <simplesequence id="simpleSeqNoDef" mode="readwrite" type="utctime">
    <kind kindtype="property"/>
    <action type="external"/>
  </simplesequence>
  <simplesequence id="simpleSeq1970" mode="readwrite" type="utctime">
    <values>
      <value>1970:01:01::00:00:00</value>
    </values>
    <kind kindtype="property"/>
    <action type="external"/>
  </simplesequence>
</properties>

=== RedhawkSDR/core-framework/codegenTesting/sdr/dom/components/rf_ctrl/rf_ctrl.prf.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE properties PUBLIC "-//JTRS//DTD SCA V2.2.2 PRF//EN" "properties.dtd">
<properties>
  <simple id="get_rfinfo" mode="readonly" type="string">
    <kind kindtype="property"/>
    <action type="external"/>
  </simple>
  <simple id="set_rfinfo" mode="readonly" type="string">
    <kind kindtype="property"/>
    <action type="external"/>
  </simple>
  <simple id="get_available_rf" mode="readonly" type="string">
    <kind kindtype="property"/>
    <action type="external"/>
  </simple>
  <simple id="set_available_rf" mode="readonly" type="string">
    <kind kindtype="property"/>
    <action type="external"/>
  </simple>
  <simple id="get_current_rf" mode="readonly" type="string">
    <kind kindtype="property"/>
    <action type="external"/>
  </simple>
  <simple id="set_current_rf" mode="readonly" type="string">
    <kind kindtype="property"/>
    <action type="external"/>
  </simple>
  <simple id="bad_connection" mode="readonly" type="string">
    <kind kindtype="property"/>
    <action type="external"/>
  </simple>
  <simple id="get_tunertype" mode="readonly" type="string">
    <kind kindtype="property"/>
    <action type="external"/>
  </simple>
  <simple id="get_tunerdevicecontrol" mode="readonly" type="string">
    <kind kindtype="property"/>
    <action type="external"/>
  </simple>
  <simple id="get_tunergroupid" mode="readwrite" type="string">
    <kind kindtype="property"/>
    <action type="external"/>
  </simple>
  <simple id="get_tunerrfflowid" mode="readwrite" type="string">
    <kind kindtype="property"/>
    <action type="external"/>
  </simple>
  <simple id="get_tunerstatus" mode="readwrite" type="string">
    <kind kindtype="property"/>
    <action type="external"/>
  </simple>
  <simple id="set_tunercenterfrequency" mode="readwrite" type="string">
    <kind kindtype="property"/>
    <action type="external"/>
  </simple>
  <simple id="get_tunercenterfrequency" mode="readwrite" type="string">
    <kind kindtype="property"/>
    <action type="external"/>
  </simple>
  <simple id="set_tunerbandwidth" mode="readwrite" type="string">
    <kind kindtype="property"/>
    <action type="external"/>
  </simple>
  <simple id="get_tunerbandwidth" mode="readwrite" type="string">
    <kind kindtype="property"/>
    <action type="external"/>
  </simple>
  <simple id="set_tuneragcenable" mode="readwrite" type="string">
    <kind kindtype="property"/>
    <action type="external"/>
  </simple>
  <simple id="get_tuneragcenable" mode="readwrite" type="string">
    <kind kindtype="property"/>
    <action type="external"/>
  </simple>
  <simple id="set_tunergain" mode="readwrite" type="string">
    <kind kindtype="property"/>
    <action type="external"/>
  </simple>
  <simple id="get_tunergain" mode="readwrite" type="string">
    <kind kindtype="property"/>
    <action type="external"/>
  </simple>
  <simple id="set_tunerreferencesource" mode="readwrite" type="string">
    <kind kindtype="property"/>
    <action type="external"/>
  </simple>
  <simple id="get_tunerreferencesource" mode="readwrite" type="string">
    <kind kindtype="property"/>
    <action type="external"/>
  </simple>
  <simple id="set_tunerenable" mode="readwrite" type="string">
    <kind kindtype="property"/>
    <action type="external"/>
  </simple>
  <simple id="get_tunerenable" mode="readwrite" type="string">
    <kind kindtype="property"/>
    <action type="external"/>
  </simple>
  <simple id="set_tuneroutputsamplerate" mode="readwrite" type="string">
    <kind kindtype="property"/>
    <action type="external"/>
  </simple>
  <simple id="get_tuneroutputsamplerate" mode="readwrite" type="string">
    <kind kindtype="property"/>
    <action type="external"/>
  </simple>
  <simple id="get_gpsinfo" mode="readwrite" type="string">
    <kind kindtype="property"/>
    <action type="external"/>
  </simple>
  <simple id="set_gpsinfo" mode="readwrite" type="string">
    <kind kindtype="property"/>
    <action type="external"/>
  </simple>
  <simple id="get_gps_timepos" mode="readwrite" type="string">
    <kind kindtype="property"/>
    <action type="external"/>
  </simple>
  <simple id="set_gps_timepos" mode="readwrite" type="string">
    <kind kindtype="property"/>
    <action type="external"/>
  </simple>
  <simple id="get_nav_packet" mode="readwrite" type="string">
    <kind kindtype="property"/>
    <action type="external"/>
  </simple>
  <simple id="set_nav_packet" mode="readwrite" type="string">
    <kind kindtype="property"/>
    <action type="external"/>
  </simple>
</properties>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dev/devices/ExecutableDevice/ExecutableDevice.prf.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
This file is protected by Copyright. Please refer to the COPYRIGHT file 
distributed with this source distribution.

This file is part of REDHAWK core.

REDHAWK core is free software: you can redistribute it and/or modify it under 
the terms of the GNU Lesser General Public License as published by the Free 
Software Foundation, either version 3 of the License, or (at your option) any 
later version.

REDHAWK core is distributed in the hope that it will be useful, but WITHOUT ANY 
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR 
A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more 
details.

You should have received a copy of the GNU Lesser General Public License along 
with this program.  If not, see http://www.gnu.org/licenses/.
-->

<!DOCTYPE properties PUBLIC '-//JTRS//DTD SCA V2.2.2 PRF//EN' 'properties.dtd'>
<properties>
    <!-- Provide a processor_name and os_name matching property -->
    <!-- See section D2.1.6.8 and Attachment 2 to Appendix D -->
    <simple id="DCE:4a23ad60-0b25-4121-a630-68803a498f75"
            name="os_name"
            mode="readonly"
            type="string">
        <description>
            SCA required property describing the Operating System
        </description>
        <value>Linux</value>
        <kind kindtype="allocation"/>
        <action type="eq"/>
    </simple>
    <simple id="DCE:fefb9c66-d14a-438d-ad59-2cfd1adb272b"
            name="processor_name"
            mode="readonly"
            type="string">
        <description>
            SCA required property describing the CPU type
        </description>
        <value>x86</value>
        <kind kindtype="allocation"/>
        <action type="eq"/>
    </simple>
    <simple id="LD_LIBRARY_PATH" mode="readonly" type="string">
        <kind kindtype="configure"/>
        <action type="external"/>
    </simple>
    <simple id="PYTHONPATH" mode="readonly" type="string">
        <kind kindtype="configure"/>
        <action type="external"/>
    </simple>
    <simple id="CLASSPATH" mode="readonly" type="string">
        <kind kindtype="configure"/>
        <action type="external"/>
    </simple>
</properties>

=== RedhawkSDR/core-framework/throughput/streams/bulkio/writer/writer.prf.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
This file is protected by Copyright. Please refer to the COPYRIGHT file
distributed with this source distribution.

This file is part of REDHAWK throughput.

REDHAWK throughput is free software: you can redistribute it and/or modify it under
the terms of the GNU Lesser General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version.

REDHAWK throughput is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more
details.

You should have received a copy of the GNU Lesser General Public License along
with this program.  If not, see http://www.gnu.org/licenses/.
-->
<!DOCTYPE properties PUBLIC "-//JTRS//DTD SCA V2.2.2 PRF//EN" "properties.dtd">
<properties>
  <simple id="transfer_length" mode="readwrite" type="ulong">
    <value>1024</value>
    <kind kindtype="property"/>
    <action type="external"/>
  </simple>
  <simple id="total_packets" mode="readonly" type="ulong">
    <value>0</value>
    <kind kindtype="property"/>
    <action type="external"/>
  </simple>
  <simple id="average_time" mode="readonly" type="double">
    <value>0.0</value>
    <kind kindtype="property"/>
    <action type="external"/>
  </simple>
</properties>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dev/devices/dev_alloc_cpp/dev_alloc_cpp.prf.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE properties PUBLIC "-//JTRS//DTD SCA V2.2.2 PRF//EN" "properties.dtd">
<properties>
  <simple id="DCE:cdc5ee18-7ceb-4ae6-bf4c-31f983179b4d" mode="readonly" name="device_kind" type="string">
    <description>This specifies the device kind</description>
    <kind kindtype="allocation"/>
    <action type="eq"/>
  </simple>
  <simple id="DCE:0f99b2e4-9903-4631-9846-ff349d18ecfb" mode="readonly" name="device_model" type="string">
    <description> This specifies the specific device</description>
    <kind kindtype="allocation"/>
    <action type="eq"/>
  </simple>
  <struct id="s_prop" mode="readwrite">
    <simple id="s_prop::a" type="string"/>
    <simple id="s_prop::b" type="short"/>
    <simplesequence id="abc" type="double"/>
    <configurationkind kindtype="allocation"/>
  </struct>
  <simplesequence id="se_prop" mode="readwrite" type="float">
    <kind kindtype="allocation"/>
    <action type="external"/>
  </simplesequence>
  <simple id="si_prop" mode="readwrite" type="short">
    <kind kindtype="allocation"/>
    <action type="external"/>
  </simple>
  <structsequence id="sq_prop" mode="readwrite">
    <struct id="sq_prop_s">
      <simple id="sq_prop::a" type="float"/>
      <simple id="sq_prop::b" type="string"/>
    </struct>
    <configurationkind kindtype="allocation"/>
  </structsequence>
</properties>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dev/devices/NicExecDevice/NicExecDevice.prf.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
This file is protected by Copyright. Please refer to the COPYRIGHT file 
distributed with this source distribution.

This file is part of REDHAWK core.

REDHAWK core is free software: you can redistribute it and/or modify it under 
the terms of the GNU Lesser General Public License as published by the Free 
Software Foundation, either version 3 of the License, or (at your option) any 
later version.

REDHAWK core is distributed in the hope that it will be useful, but WITHOUT ANY 
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR 
A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more 
details.

You should have received a copy of the GNU Lesser General Public License along 
with this program.  If not, see http://www.gnu.org/licenses/.
-->
<!DOCTYPE properties PUBLIC "-//JTRS//DTD SCA V2.2.2 PRF//EN" "properties.dtd">
<properties>
  <simple id="DCE:cdc5ee18-7ceb-4ae6-bf4c-31f983179b4d" mode="readonly" name="device_kind" type="string">
    <description>This specifies the device kind</description>
    <value>GPP</value>
    <kind kindtype="allocation"/>
    <action type="eq"/>
  </simple>
  <simple id="DCE:0f99b2e4-9903-4631-9846-ff349d18ecfb" mode="readonly" name="device_model" type="string">
    <description> This specifies the specific device</description>
    <value>NicExecDevice</value>
    <kind kindtype="allocation"/>
    <action type="eq"/>
  </simple>
  <simple id="DCE:9B445600-6C7F-11d4-A226-0050DA314CD6" mode="readonly" name="processor_name" type="string">
    <description>SCA required property describing the CPU type</description>
    <value>x86_64</value>
    <kind kindtype="allocation"/>
    <action type="eq"/>
  </simple>
  <simple id="DCE:80BF17F0-6C7F-11d4-A226-0050DA314CD6" mode="readonly" name="os_name" type="string">
    <description>SCA required property describing the Operating System Name</description>
    <value>Linux</value>
    <kind kindtype="allocation"/>
    <action type="eq"/>
  </simple>
  <simple id="DCE:0f3a9a37-a342-43d8-9b7f-78dc6da74192" mode="readonly" name="os_version" type="string">
    <description>SCA required property describing the Operating System Version</description>
    <kind kindtype="allocation"/>
    <action type="eq"/>
  </simple>
  <simplesequence id="nic_list" mode="readonly" type="string">
    <kind kindtype="property"/>
    <action type="external"/>
  </simplesequence>
  <struct id="nic_allocation" mode="readwrite">
    <simple id="nic_allocation::identifier" name="identifier" type="string">
      <description>Uniquely identifies the allocation.  Used for updates and deallocations.

Required

</description>
      <value></value>
    </simple>
    <simple id="nic_allocation::interface" name="interface" type="string">
      <description>Requires this specific interface.

Optional</description>
      <value></value>
    </simple>
    <configurationkind kindtype="allocation"/>
  </struct>
  <structsequence id="nic_allocation_status" mode="readonly">
    <struct id="nic_allocation_status_struct">
      <simple id="nic_allocation_status::identifier" name="identifier" type="string">
        <description>Uniquely identifies the allocation. </description>
      </simple>
      <simple id="nic_allocation_status::interface" name="interface" type="string">
        <description>The allocated interface</description>
      </simple>
    </struct>
    <configurationkind kindtype="property"/>
  </structsequence>
</properties>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dev/devices/CppTestDevice/CppTestDevice.prf.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
This file is protected by Copyright. Please refer to the COPYRIGHT file
distributed with this source distribution.

This file is part of REDHAWK core.

REDHAWK core is free software: you can redistribute it and/or modify it under
the terms of the GNU Lesser General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version.

REDHAWK core is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more
details.

You should have received a copy of the GNU Lesser General Public License along
with this program.  If not, see http://www.gnu.org/licenses/.
-->
<!DOCTYPE properties PUBLIC "-//JTRS//DTD SCA V2.2.2 PRF//EN" "properties.dtd">
<properties>
  <simple id="DCE:cdc5ee18-7ceb-4ae6-bf4c-31f983179b4d" mode="readonly" name="device_kind" type="string">
    <description>This specifies the device kind</description>
    <value>TestDevice</value>
    <kind kindtype="configure"/>
    <kind kindtype="allocation"/>
    <action type="eq"/>
  </simple>
  <simple id="DCE:0f99b2e4-9903-4631-9846-ff349d18ecfb" mode="readonly" name="device_model" type="string">
    <description> This specifies the specific device</description>
    <value>CppTestDevice</value>
    <kind kindtype="configure"/>
    <kind kindtype="allocation"/>
    <action type="eq"/>
  </simple>
  <simple id="disk_space" mode="readonly" name="disk_space" type="longlong">
    <value>100000000000</value>
    <units>bytes</units>
    <kind kindtype="configure"/>
    <kind kindtype="allocation"/>
    <action type="external"/>
  </simple>
  <simple id="load_average" mode="readonly" name="load_average" type="float">
    <value>0.0</value>
    <kind kindtype="configure"/>
    <kind kindtype="allocation"/>
    <action type="external"/>
  </simple>
  <simple id="memory_capacity" mode="readonly" name="memory_capacity" type="longlong">
    <value>2147483648</value>
    <units>bytes</units>
    <kind kindtype="configure"/>
    <action type="external"/>
  </simple>
  <simple id="shared_memory" mode="readonly" name="shared_memory" type="long">
    <value>33554432</value>
    <units>bytes</units>
    <kind kindtype="configure"/>
    <action type="external"/>
  </simple>
  <struct id="memory_allocation" mode="readwrite" name="memory_allocation">
    <simple id="capacity" name="capacity" type="long">
      <units>bytes</units>
    </simple>
    <simple id="contiguous" name="contiguous" type="boolean">
      <value>true</value>
    </simple>
    <simple id="memory_type" name="memory_type" type="long">
      <value>0</value>
      <enumerations>
        <enumeration label="PRIVATE" value="0"/>
        <enumeration label="SHARED" value="1"/>
      </enumerations>
    </simple>
    <configurationkind kindtype="allocation"/>
  </struct>
</properties>
