=== RedhawkSDR/core-framework/redhawk/src/xml/dtd/properties.dtd
<!--
This file is protected by Copyright. Please refer to the COPYRIGHT file 
distributed with this source distribution.

This file is part of REDHAWK core.

REDHAWK core is free software: you can redistribute it and/or modify it under 
the terms of the GNU Lesser General Public License as published by the Free 
Software Foundation, either version 3 of the License, or (at your option) any 
later version.

REDHAWK core is distributed in the hope that it will be useful, but WITHOUT ANY 
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR 
A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more 
details.

You should have received a copy of the GNU Lesser General Public License along 
with this program.  If not, see http://www.gnu.org/licenses/.
-->

<!ELEMENT properties
     	 ( description?
     	 , 	( simple
		| simplesequence
		| test
		| struct
		| structsequence)*
       )> 

<!ELEMENT simple 
	( description?
	, value?
	, units?
	, range?
	, enumerations?
	, kind*
	, action?
	)>

<!-- Support non-SCA compliant longlong -->
<!ATTLIST simple
	id	ID							#REQUIRED
	type	( boolean	| char	| double | float
		| short	| long	| longlong | objref | octet
		| string	| ulong | ulonglong	| ushort | utctime )		#REQUIRED
	name	CDATA							#IMPLIED
	complex ( false | true ) "false"
	commandline ( false | true ) "false"
	optional ( false | true ) "false"
	mode	( readonly	| readwrite | writeonly)	"readwrite">

<!ELEMENT description (#PCDATA)>

<!ELEMENT value (#PCDATA)>

<!ELEMENT units (#PCDATA)>

<!ELEMENT range EMPTY>
<!ATTLIST range
	min		CDATA	#REQUIRED
	max		CDATA	#REQUIRED>

<!ELEMENT enumerations
	( enumeration+
	)>

<!ELEMENT enumeration EMPTY>
<!ATTLIST enumeration
	label		CDATA	#REQUIRED
	value		CDATA	#IMPLIED>

<!ELEMENT kind EMPTY>
<!ATTLIST kind
	kindtype	(allocation | property | configure | test | execparam | factoryparam | event | message) 
"configure">

<!ELEMENT action EMPTY>
<!ATTLIST action
	type	( eq  | ne | gt  |  lt | ge | le | external ) "external">

<!ELEMENT simplesequence 
	( description?
	, values?
	, units?
	, range?
	, kind*
	, action?
	)>
<!ATTLIST simplesequence
	id	ID						#REQUIRED
	type  ( boolean | char   | double | float
	      | short  | long | longlong   | objref | octet
	      | string | ulong | ulonglong | ushort | utctime )		#REQUIRED
	name	CDATA						#IMPLIED
	complex ( false | true ) "false"
	optional ( false | true ) "false"
	mode	(readonly | readwrite | writeonly)	"readwrite">

<!ELEMENT values
	( value+ 
	)>

<!ELEMENT test 
	( description
      , inputValue?
	, resultValue
	)>
<!ATTLIST test
	id		CDATA #REQUIRED>

<!ELEMENT inputValue
	( simple+
	)>

<!ELEMENT resultValue
	( simple+
	)>

<!ELEMENT struct 
	( description?
	, (simple | simplesequence)+
	, configurationkind*
	)>
<!ATTLIST struct
	id		ID	#REQUIRED
	name		CDATA	#IMPLIED
	mode		(readonly | readwrite | writeonly)  "readwrite">

<!ELEMENT configurationkind EMPTY>
<!ATTLIST configurationkind
	kindtype	(allocation | property | configure | test | factoryparam | event | message  )
"configure">

<!ELEMENT structsequence
	( description?
	, struct
	, structvalue*
	, configurationkind*
	)>
<!ATTLIST structsequence
	id       	ID	#REQUIRED
	name		CDATA	#IMPLIED
	mode		(readonly | readwrite | writeonly)  "readwrite">
		
<!ELEMENT structvalue
	( (simpleref | simplesequenceref)+	        
	)>
		
<!ELEMENT simpleref EMPTY>
<!ATTLIST simpleref
	refid 	CDATA	#REQUIRED
	value 	CDATA	#REQUIRED>

<!ELEMENT simplesequenceref
        ( values
        )>
<!ATTLIST simplesequenceref
        refid   CDATA   #REQUIRED>

=== RedhawkSDR/core-framework/redhawk/src/control/sdr/dommgr/DomainManager.prf.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
This file is protected by Copyright. Please refer to the COPYRIGHT file 
distributed with this source distribution.

This file is part of REDHAWK core.

REDHAWK core is free software: you can redistribute it and/or modify it under 
the terms of the GNU Lesser General Public License as published by the Free 
Software Foundation, either version 3 of the License, or (at your option) any 
later version.

REDHAWK core is distributed in the hope that it will be useful, but WITHOUT ANY 
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR 
A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more 
details.

You should have received a copy of the GNU Lesser General Public License along 
with this program.  If not, see http://www.gnu.org/licenses/.
-->

<!DOCTYPE properties PUBLIC "-//JTRS//DTD SCA V2.2.2 PRF//EN" "properties.dtd">
<properties>
    <description>These are the properties to configure the domain manager</description>

    <simple id="LOGGING_CONFIG_URI" mode="readonly" name="LOGGING_CONFIG_URI" type="string">
        <description>
	A URI on the SCA FileManager that points to a log4j configuration file used
	for the domain manager and the entire domain. 
	</description>
        <kind kindtype="execparam"/>
        <kind kindtype="configure"/>
    </simple>
    <simple id="DMD_FILE" mode="readwrite" name="DMD_FILE" type="string">
        <description>
        Path to the Domain Manager Descriptor (DMD) XML file..
        </description>
        <kind kindtype="execparam"/>
        <action type="external"/>
    </simple>
    <simple id="DOMAIN_NAME" mode="readwrite" name="DOMAIN_NAME" type="string">
        <description>
        The name of the domain to which this domain manager will be bound.
        </description>
        <kind kindtype="execparam"/>
        <action type="external"/>
    </simple>
    <simple id="PERSISTENCE" mode="readonly" name="PERSISTENCE" type="boolean" commandline="true">
        <description>
        Enable CORBA persistence for the domain manager.
        </description>
        <value>true</value>
        <kind kindtype="property"/>
        <action type="external"/>
    </simple>
    <simple id="DB_URL" mode="readwrite" name="DB_URL" type="string">
        <description>
        The URL to a database for domain persistence information.
        </description>
        <kind kindtype="execparam"/>
        <action type="external"/>
    </simple>
    <simple id="FORCE_REBIND" mode="readwrite" name="FORCE_REBIND" type="boolean">
        <description>
        Replace any existing name binding for the domain manager.
        </description>
        <value>false</value>
        <kind kindtype="execparam"/>
        <action type="external"/>
    </simple>
    <simple id="COMPONENT_BINDING_TIMEOUT" mode="readwrite" name="component_binding_timeout" type="ulong">
        <description>
        The amount of time, in seconds, to wait for a component to bind to the name service after being launched.
        </description>
        <value>60</value>
        <units>seconds</units>
        <kind kindtype="configure"/>
        <action type="external"/>
    </simple>

    <struct id="client_wait_times" mode="readwrite" name="client_wait_times">
      <simple id="client_wait_times::devices" name="devices" type="ulong">
        <value>10000</value>
        <units>milliseconds</units>
      </simple>
      <simple id="client_wait_times::services" mode="readwrite" name="services" type="ulong">
        <value>10000</value>
        <units>milliseconds</units>
        <kind kindtype="property"/>
        <action type="external"/>
      </simple>
      <simple id="client_wait_times::managers" mode="readwrite" name="managers" type="ulong">
        <value>10000</value>
        <units>milliseconds</units>
        <kind kindtype="property"/>
        <action type="external"/>
      </simple>
      <configurationkind kindtype="property"/>
    </struct>

    <simple id="REDHAWK_VERSION" mode="readonly" name="REDHAWK_VERSION" type="string">
        <description>
            Current version of REDHAWK that this Domain Manager is running
        </description>
        <kind kindtype="configure"/>
        <action type="external"/>
    </simple>
</properties>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dev/devices/EventPortTestDevice/EventPortTestDevice.prf.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
This file is protected by Copyright. Please refer to the COPYRIGHT file 
distributed with this source distribution.

This file is part of REDHAWK core.

REDHAWK core is free software: you can redistribute it and/or modify it under 
the terms of the GNU Lesser General Public License as published by the Free 
Software Foundation, either version 3 of the License, or (at your option) any 
later version.

REDHAWK core is distributed in the hope that it will be useful, but WITHOUT ANY 
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR 
A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more 
details.

You should have received a copy of the GNU Lesser General Public License along 
with this program.  If not, see http://www.gnu.org/licenses/.
-->

<!DOCTYPE properties PUBLIC '-//JTRS//DTD SCA V2.2.2 PRF//EN' 'properties.dtd'>
<!-- Created with REDHAWK IDE-->
<!-- Powered by Eclipse -->
<properties>
    <!-- Provide a processor_name and os_name matching property -->
    <simple id="DCE:4a23ad60-0b25-4121-a630-68803a498f75"
            name="os_name"
            mode="readonly"
            type="string">
        <description>
            SCA required property describing the Operating System
        </description>
        <value>Linux</value>
        <kind kindtype="allocation"/>
        <action type="eq"/>
    </simple>
    <simple id="DCE:fefb9c66-d14a-438d-ad59-2cfd1adb272b"
            name="processor_name"
            mode="readonly"
            type="string">
        <description>
            SCA required property describing the CPU type
        </description>
        <value>x86</value>
        <kind kindtype="allocation"/>
        <action type="eq"/>
    </simple>
    <simple id="DCE:8dcef419-b440-4bcf-b893-cab79b6024fb"
            name="memCapacity"
            mode="readonly"
            type="long">
        <description>
            Amount of RAM in the GPP not allocated to an application
        </description>
	<units>bytes</units>
        <kind kindtype="allocation"/>
    </simple>
    <simple id="DCE:5636c210-0346-4df7-a5a3-8fd34c5540a8"
            name="BogoMipsCapacity"
            mode="readonly"
            type="long">
        <description>
            Amount of BogoMips provided by the machine.
        </description>
	<units>bogomips</units>
        <kind kindtype="allocation"/>
    </simple>
</properties>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dom/components/ticket_462_ac/ticket_462_ac.prf.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
This file is protected by Copyright. Please refer to the COPYRIGHT file
distributed with this source distribution.

This file is part of REDHAWK core.

REDHAWK core is free software: you can redistribute it and/or modify it under
the terms of the GNU Lesser General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version.

REDHAWK core is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more
details.

You should have received a copy of the GNU Lesser General Public License along
with this program.  If not, see http://www.gnu.org/licenses/.
-->
<!DOCTYPE properties PUBLIC "-//JTRS//DTD SCA V2.2.2 PRF//EN" "properties.dtd">
<properties>
  <simple id="my_simple" mode="readwrite" type="string">
    <kind kindtype="configure"/>
    <action type="external"/>
  </simple>
  <simplesequence id="my_seq" mode="readwrite" type="string">
    <kind kindtype="configure"/>
    <action type="external"/>
  </simplesequence>
  <struct id="basic_struct" mode="readwrite">
    <simple id="some_simple" type="string"/>
    <configurationkind kindtype="configure"/>
  </struct>
</properties>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dev/devices/start_event_device/start_event_device.prf.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
This file is protected by Copyright. Please refer to the COPYRIGHT file
distributed with this source distribution.

This file is part of REDHAWK core.

REDHAWK core is free software: you can redistribute it and/or modify it under
the terms of the GNU Lesser General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version.

REDHAWK core is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more
details.

You should have received a copy of the GNU Lesser General Public License along
with this program.  If not, see http://www.gnu.org/licenses/.
-->
<!DOCTYPE properties PUBLIC "-//JTRS//DTD SCA V2.2.2 PRF//EN" "properties.dtd">
<properties>
  <simple id="DCE:cdc5ee18-7ceb-4ae6-bf4c-31f983179b4d" mode="readonly" name="device_kind" type="string">
    <description>This specifies the device kind</description>
    <value>start_event_device</value>
    <kind kindtype="allocation"/>
    <action type="eq"/>
  </simple>
  <simple id="DCE:0f99b2e4-9903-4631-9846-ff349d18ecfb" mode="readonly" name="device_model" type="string">
    <description> This specifies the specific device</description>
    <kind kindtype="allocation"/>
    <action type="eq"/>
  </simple>
  <struct id="state_change" mode="readwrite">
    <simple id="state_change::identifier" name="identifier" type="string"/>
    <simple id="state_change::event" name="event" type="string"/>
    <configurationkind kindtype="message"/>
  </struct>
  <struct id="failures" mode="readwrite">
    <simple id="failures::start" name="start" type="boolean">
      <value>false</value>
    </simple>
    <simple id="failures::stop" name="stop" type="boolean">
      <value>false</value>
    </simple>
    <configurationkind kindtype="property"/>
  </struct>
</properties>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dom/components/TestAllPropTypes/TestAllPropTypes.prf.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
This file is protected by Copyright. Please refer to the COPYRIGHT file 
distributed with this source distribution.

This file is part of REDHAWK core.

REDHAWK core is free software: you can redistribute it and/or modify it under 
the terms of the GNU Lesser General Public License as published by the Free 
Software Foundation, either version 3 of the License, or (at your option) any 
later version.

REDHAWK core is distributed in the hope that it will be useful, but WITHOUT ANY 
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR 
A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more 
details.

You should have received a copy of the GNU Lesser General Public License along 
with this program.  If not, see http://www.gnu.org/licenses/.
-->

<!DOCTYPE properties PUBLIC "-//JTRS//DTD SCA V2.2.2 PRF//EN" "properties.dtd">
<properties>
  <simple id="simple_string" mode="readwrite" type="string">
    <kind kindtype="configure"/>
    <action type="external"/>
  </simple>
  <simple id="simple_boolean" mode="readwrite" type="boolean">
    <kind kindtype="configure"/>
    <action type="external"/>
  </simple>
  <simple id="simple_ulong" mode="readwrite" type="ulong">
    <kind kindtype="configure"/>
    <action type="external"/>
  </simple>
  <simple id="simple_objref" mode="readwrite" type="objref">
    <kind kindtype="configure"/>
    <action type="external"/>
  </simple>
  <simple id="simple_short" mode="readwrite" type="short">
    <kind kindtype="configure"/>
    <action type="external"/>
  </simple>
  <simple id="simple_float" mode="readwrite" type="float">
    <kind kindtype="configure"/>
    <action type="external"/>
  </simple>
  <simple id="simple_octet" mode="readwrite" type="octet">
    <kind kindtype="configure"/>
    <action type="external"/>
  </simple>
  <simple id="simple_char" mode="readwrite" type="char">
    <kind kindtype="configure"/>
    <action type="external"/>
  </simple>
  <simple id="simple_ushort" mode="readwrite" type="ushort">
    <kind kindtype="configure"/>
    <action type="external"/>
  </simple>
  <simple id="simple_double" mode="readwrite" type="double">
    <kind kindtype="configure"/>
    <action type="external"/>
  </simple>
  <simple id="simple_long" mode="readwrite" type="long">
    <kind kindtype="configure"/>
    <action type="external"/>
  </simple>
  <simple id="simple_longlong" mode="readwrite" type="longlong">
    <kind kindtype="configure"/>
    <action type="external"/>
  </simple>
  <simple id="simple_ulonglong" mode="readwrite" type="ulonglong">
    <kind kindtype="configure"/>
    <action type="external"/>
  </simple>
  <simple id="simple_utctime" mode="readwrite" type="utctime">
    <kind kindtype="property"/>
    <action type="external"/>
  </simple>
  <simplesequence id="simple_sequence_string" mode="readwrite" type="string">
    <kind kindtype="configure"/>
    <action type="external"/>
  </simplesequence>
  <simplesequence id="simple_sequence_boolean" mode="readwrite" type="boolean">
    <kind kindtype="configure"/>
    <action type="external"/>
  </simplesequence>
  <simplesequence id="simple_sequence_ulong" mode="readwrite" type="ulong">
    <kind kindtype="configure"/>
    <action type="external"/>
  </simplesequence>
  <simplesequence id="simple_sequence_objref" mode="readwrite" type="objref">
    <kind kindtype="configure"/>
    <action type="external"/>
  </simplesequence>
  <simplesequence id="simple_sequence_short" mode="readwrite" type="short">
    <kind kindtype="configure"/>
    <action type="external"/>
  </simplesequence>
  <simplesequence id="simple_sequence_float" mode="readwrite" type="float">
    <kind kindtype="configure"/>
    <action type="external"/>
  </simplesequence>
  <simplesequence id="simple_sequence_octet" mode="readwrite" type="octet">
    <kind kindtype="configure"/>
    <action type="external"/>
  </simplesequence>
  <simplesequence id="simple_sequence_char" mode="readwrite" type="char">
    <kind kindtype="configure"/>
    <action type="external"/>
  </simplesequence>
  <simplesequence id="simple_sequence_ushort" mode="readwrite" type="ushort">
    <kind kindtype="configure"/>
    <action type="external"/>
  </simplesequence>
  <simplesequence id="simple_sequence_double" mode="readwrite" type="double">
    <kind kindtype="configure"/>
    <action type="external"/>
  </simplesequence>
  <simplesequence id="simple_sequence_long" mode="readwrite" type="long">
    <kind kindtype="configure"/>
    <action type="external"/>
  </simplesequence>
  <simplesequence id="simple_sequence_longlong" mode="readwrite" type="longlong">
    <kind kindtype="configure"/>
    <action type="external"/>
  </simplesequence>
  <simplesequence id="simple_sequence_ulonglong" mode="readwrite" type="ulonglong">
    <kind kindtype="configure"/>
    <action type="external"/>
  </simplesequence>
  <simplesequence id="simple_sequence_utctime" mode="readwrite" type="utctime">
    <kind kindtype="property"/>
    <action type="external"/>
  </simplesequence>
  <struct id="struct_vars" mode="readwrite">
    <simple id="struct_string" type="string"/>
    <simple id="struct_boolean" mode="readwrite" type="boolean">
      <kind kindtype="configure"/>
      <action type="external"/>
    </simple>
    <simple id="struct_ulong" mode="readwrite" type="ulong">
      <kind kindtype="configure"/>
      <action type="external"/>
    </simple>
    <simple id="struct_objref" mode="readwrite" type="objref">
      <kind kindtype="configure"/>
      <action type="external"/>
    </simple>
    <simple id="struct_short" mode="readwrite" type="short">
      <kind kindtype="configure"/>
      <action type="external"/>
    </simple>
    <simple id="struct_float" mode="readwrite" type="float">
      <kind kindtype="configure"/>
      <action type="external"/>
    </simple>
    <simple id="struct_octet" mode="readwrite" type="octet">
      <kind kindtype="configure"/>
      <action type="external"/>
    </simple>
    <simple id="struct_char" mode="readwrite" type="char">
      <kind kindtype="configure"/>
      <action type="external"/>
    </simple>
    <simple id="struct_ushort" mode="readwrite" type="ushort">
      <kind kindtype="configure"/>
      <action type="external"/>
    </simple>
    <simple id="struct_double" mode="readwrite" type="double">
      <kind kindtype="configure"/>
      <action type="external"/>
    </simple>
    <simple id="struct_long" mode="readwrite" type="long">
      <kind kindtype="configure"/>
      <action type="external"/>
    </simple>
    <simple id="struct_longlong" mode="readwrite" type="longlong">
      <kind kindtype="configure"/>
      <action type="external"/>
    </simple>
    <simple id="struct_ulonglong" mode="readwrite" type="ulonglong">
      <kind kindtype="configure"/>
      <action type="external"/>
    </simple>
    <configurationkind kindtype="configure"/>
  </struct>
  <structsequence id="struct_seq" mode="readwrite">
    <struct id="struct_seq_vars">
      <simple id="struct_seq_string" type="string"/>
      <simple id="struct_seq_boolean" mode="readwrite" type="boolean">
        <kind kindtype="configure"/>
        <action type="external"/>
      </simple>
      <simple id="struct_seq_ulong" mode="readwrite" type="ulong">
        <kind kindtype="configure"/>
        <action type="external"/>
      </simple>
      <simple id="struct_seq_objref" mode="readwrite" type="objref">
        <kind kindtype="configure"/>
        <action type="external"/>
      </simple>
      <simple id="struct_seq_short" mode="readwrite" type="short">
        <kind kindtype="configure"/>
        <action type="external"/>
      </simple>
      <simple id="struct_seq_float" mode="readwrite" type="float">
        <kind kindtype="configure"/>
        <action type="external"/>
      </simple>
      <simple id="struct_seq_octet" mode="readwrite" type="octet">
        <kind kindtype="configure"/>
        <action type="external"/>
      </simple>
      <simple id="struct_seq_char" mode="readwrite" type="char">
        <kind kindtype="configure"/>
        <action type="external"/>
      </simple>
      <simple id="struct_seq_ushort" mode="readwrite" type="ushort">
        <kind kindtype="configure"/>
        <action type="external"/>
      </simple>
      <simple id="struct_seq_double" mode="readwrite" type="double">
        <kind kindtype="configure"/>
        <action type="external"/>
      </simple>
      <simple id="struct_seq_long" mode="readwrite" type="long">
        <kind kindtype="configure"/>
        <action type="external"/>
      </simple>
      <simple id="struct_seq_longlong" mode="readwrite" type="longlong">
        <kind kindtype="configure"/>
        <action type="external"/>
      </simple>
      <simple id="struct_seq_ulonglong" mode="readwrite" type="ulonglong">
        <kind kindtype="configure"/>
        <action type="external"/>
      </simple>
    </struct>
    <configurationkind kindtype="configure"/>
  </structsequence>
</properties>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dev/devices/BasicUsesDevice/BasicUsesDevice.prf.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
This file is protected by Copyright. Please refer to the COPYRIGHT file 
distributed with this source distribution.

This file is part of REDHAWK core.

REDHAWK core is free software: you can redistribute it and/or modify it under 
the terms of the GNU Lesser General Public License as published by the Free 
Software Foundation, either version 3 of the License, or (at your option) any 
later version.

REDHAWK core is distributed in the hope that it will be useful, but WITHOUT ANY 
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR 
A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more 
details.

You should have received a copy of the GNU Lesser General Public License along 
with this program.  If not, see http://www.gnu.org/licenses/.
-->

<!DOCTYPE properties PUBLIC '-//JTRS//DTD SCA V2.2.2 PRF//EN' 'properties.dtd'>
<properties>
    <simple id="DCE:6b298d70-6735-43f2-944d-06f754cd4eb9" name="no_default_prop" mode="readwrite" type="string">
        <description>A configure property with no default value.</description>
        <kind kindtype="configure"/>
    </simple>
    <simple id="DCE:456310b2-7d2f-40f5-bfef-9fdf4f3560ea" name="default_prop" mode="readwrite" type="string">
        <description>A configure property with a default value.</description>
        <value>default</value>
        <kind kindtype="configure"/>
    </simple>
    <simple id="number_connections" name="number_connections" mode="readwrite" type="short">
        <description>number of connections that the component has</description>
        <value>0</value>
        <kind kindtype="configure"/>
    </simple>
    <!-- Provide a variety of matching allocation properties. -->
    <simple id="DCE:7f36cdfb-f828-4e4f-b84f-446e17f1a85b"
            name="DeviceKind"
            mode="readonly"
            type="string"
            >
        <description>
            The type of this device...see D.4.1.17
        </description>
        <value>BasicUsesDevice</value>
        <kind kindtype="allocation"/>
        <action type="eq"/>
    </simple>
    <simple id="DCE:64303822-4c67-4c04-9a5c-bf670f27cf39"
            name="RunsAs"
            mode="readonly"
            type="string"
            >
        <value>root</value>
        <kind kindtype="allocation"/>
        <action type="ne"/>
    </simple>
    <!-- Provide two external capacities that can be allocated -->
    <simple id="DCE:8cad8ca5-c155-4d1d-ae40-e194aa1d855f"
            name="bandwidthCapacity"
            mode="readonly"
            type="long">
        <description>
            Amount of bandwidth available in the NIC
        </description>
	<units>bps</units>
        <kind kindtype="allocation"/>
    </simple>
</properties>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dev/devices/writeonly_java/writeonly_java.prf.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE properties PUBLIC "-//JTRS//DTD SCA V2.2.2 PRF//EN" "properties.dtd">
<properties>
  <simple id="DCE:cdc5ee18-7ceb-4ae6-bf4c-31f983179b4d" mode="readonly" name="device_kind" type="string">
    <description>This specifies the device kind</description>
    <kind kindtype="allocation"/>
    <action type="eq"/>
  </simple>
  <simple id="DCE:0f99b2e4-9903-4631-9846-ff349d18ecfb" mode="readonly" name="device_model" type="string">
    <description> This specifies the specific device</description>
    <kind kindtype="allocation"/>
    <action type="eq"/>
  </simple>
  <simple id="foo" mode="writeonly" type="string">
    <value>something</value>
    <kind kindtype="allocation"/>
    <action type="external"/>
  </simple>
  <simplesequence id="foo_seq" mode="writeonly" type="string">
    <values>
      <value>abc</value>
    </values>
    <kind kindtype="allocation"/>
    <action type="external"/>
  </simplesequence>
  <struct id="foo_struct" mode="writeonly">
    <simple id="abc" type="string">
      <value>def</value>
    </simple>
    <configurationkind kindtype="allocation"/>
  </struct>
  <structsequence id="foo_struct_seq" mode="writeonly">
    <struct id="ghi">
      <simple id="jkl" type="string"/>
    </struct>
    <structvalue>
      <simpleref refid="jkl" value=""/>
      <simpleref refid="jkl" value="mno"/>
    </structvalue>
    <configurationkind kindtype="allocation"/>
  </structsequence>
</properties>
