=== RedhawkSDR/core-framework/redhawk/src/xml/dtd/softwareassembly.dtd
<!--
This file is protected by Copyright. Please refer to the COPYRIGHT file 
distributed with this source distribution.

This file is part of REDHAWK core.

REDHAWK core is free software: you can redistribute it and/or modify it under 
the terms of the GNU Lesser General Public License as published by the Free 
Software Foundation, either version 3 of the License, or (at your option) any 
later version.

REDHAWK core is distributed in the hope that it will be useful, but WITHOUT ANY 
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR 
A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more 
details.

You should have received a copy of the GNU Lesser General Public License along 
with this program.  If not, see http://www.gnu.org/licenses/.
-->

<!ELEMENT softwareassembly
	( description?
	, componentfiles
	, partitioning
	, assemblycontroller
	, connections?
	, externalports?
	, externalproperties?
	, options?
	, usesdevicedependencies?
	)>
<!ATTLIST softwareassembly
	id		ID	#REQUIRED
	name		CDATA	#IMPLIED
	version		CDATA	#IMPLIED>

<!ELEMENT description (#PCDATA)>

<!ELEMENT componentfiles 
	( componentfile+
	)>

<!ELEMENT componentfile
	( localfile 
	)>
<!ATTLIST componentfile
	id		ID	#REQUIRED
	type		CDATA	#IMPLIED>

<!ELEMENT localfile EMPTY>
<!ATTLIST localfile
	name		CDATA	#REQUIRED>

<!ELEMENT partitioning 
	( componentplacement
	|  hostcollocation
	)*>

<!ELEMENT componentplacement 
	( componentfileref
	, componentinstantiation+
	)>

<!ELEMENT componentfileref  EMPTY>
<!ATTLIST componentfileref
	refid		CDATA	#REQUIRED>

<!ELEMENT componentinstantiation
	( usagename?
	, componentproperties?
        , affinity?
        , loggingconfig?
	, findcomponent?
	, devicerequires?
	)>
<!ATTLIST componentinstantiation
	id		ID 	#REQUIRED
	startorder	CDATA	#IMPLIED>

<!ELEMENT usagename (#PCDATA)>

<!ELEMENT loggingconfig (#PCDATA)>
<!ATTLIST loggingconfig 
          level CDATA #IMPLIED >

<!ELEMENT affinity
	( simpleref
	| simplesequenceref
	| structref
	| structsequenceref
	)+ >

<!ELEMENT devicerequires
	( requires
	)+ >

<!ELEMENT componentproperties 
	( simpleref
	| simplesequenceref
	| structref
	| structsequenceref
	)+ >

<!ELEMENT findcomponent
	( componentresourcefactoryref
	| namingservice
	)>

<!ELEMENT componentresourcefactoryref
	( resourcefactoryproperties?
	)>
<!ATTLIST componentresourcefactoryref 
	refid		CDATA	#REQUIRED>

<!ELEMENT devicethatloadedthiscomponentref EMPTY>
<!ATTLIST devicethatloadedthiscomponentref 
	refid		CDATA	#REQUIRED>

<!ELEMENT deviceusedbythiscomponentref EMPTY>
<!ATTLIST deviceusedbythiscomponentref 
	refid		CDATA	#REQUIRED
	usesrefid	CDATA	#REQUIRED>

<!ELEMENT deviceusedbyapplication EMPTY>
<!ATTLIST deviceusedbyapplication
	usesrefid	CDATA	#REQUIRED>

<!ELEMENT resourcefactoryproperties 
	( simpleref
	| simplesequenceref
	| structref
	| structsequenceref
	)+ >

<!ELEMENT requires EMPTY>
<!ATTLIST requires
	id		CDATA	#REQUIRED
	value		CDATA	#REQUIRED>

<!ELEMENT simpleref EMPTY>
<!ATTLIST simpleref
	refid		CDATA	#REQUIRED
	value		CDATA	#REQUIRED>
		
<!ELEMENT simplesequenceref
	(values
	)>
<!ATTLIST simplesequenceref
	refid		CDATA	#REQUIRED>

<!ELEMENT structref
	( (simpleref | simplesequenceref)+       
	)>
<!ATTLIST structref
	refid		CDATA	#REQUIRED>

<!ELEMENT structsequenceref
	( structvalue+
	)>
<!ATTLIST structsequenceref
	refid		CDATA	#REQUIRED>

<!ELEMENT structvalue
	( (simpleref | simplesequenceref)+
	)>
		
<!ELEMENT values
	( value+ 
	)>
		
<!ELEMENT value (#PCDATA)>

<!ELEMENT componentinstantiationref EMPTY>
<!ATTLIST componentinstantiationref 
	refid		CDATA	#REQUIRED>

<!ELEMENT findby
	( namingservice
	| stringifiedobjectref
	| domainfinder
	)>

<!ELEMENT namingservice EMPTY>
<!ATTLIST namingservice
	name 		CDATA	#REQUIRED>

<!ELEMENT stringifiedobjectref (#PCDATA)>

<!ELEMENT domainfinder EMPTY>
<!ATTLIST domainfinder
	type		CDATA	#REQUIRED
	name		CDATA	#IMPLIED>

<!ELEMENT hostcollocation
	( componentplacement+
        , usesdeviceref*
        , reservation*
	)>

<!ATTLIST hostcollocation
	id		ID	#IMPLIED
	name		CDATA	#IMPLIED>

<!ELEMENT usesdeviceref EMPTY>
<!ATTLIST usesdeviceref
	refid		CDATA	#REQUIRED>

<!ELEMENT reservation EMPTY>
<!ATTLIST reservation
    kind        CDATA   #REQUIRED
    value       CDATA   #REQUIRED>

<!ELEMENT assemblycontroller
	( componentinstantiationref
	)>

<!ELEMENT connections
	( connectinterface*
	)>

<!ELEMENT connectinterface
	( usesport
	, ( providesport
	  | componentsupportedinterface
	  | findby
	  )
	)>
<!ATTLIST connectinterface
	id 		ID	#IMPLIED>

<!ELEMENT usesport
	( usesidentifier
	, (componentinstantiationref
	   | devicethatloadedthiscomponentref
	   | deviceusedbythiscomponentref
	   | deviceusedbyapplication
	   | findby
	   )
	)>

<!ELEMENT usesidentifier (#PCDATA)>

<!ELEMENT providesport
	( providesidentifier
	, ( componentinstantiationref
	  | devicethatloadedthiscomponentref
	  | deviceusedbythiscomponentref
	  | deviceusedbyapplication
	  | findby 
        )
	)>

<!ELEMENT providesidentifier (#PCDATA)>

<!ELEMENT componentsupportedinterface
	( supportedidentifier
	, ( componentinstantiationref
	  | devicethatloadedthiscomponentref
	  | deviceusedbythiscomponentref
	  | deviceusedbyapplication
	  | findby
	  )
	)>

<!ELEMENT supportedidentifier (#PCDATA)>

<!ELEMENT externalports 
	(port+
	)>

<!ELEMENT port
	( description?
	, (usesidentifier | providesidentifier | supportedidentifier)
	, componentinstantiationref
	)>
<!ATTLIST port
	externalname 		CDATA	#IMPLIED>

<!ELEMENT externalproperties
	(property+
	)>

<!ELEMENT property EMPTY>
<!ATTLIST property
	comprefid			CDATA	#REQUIRED
	propid				CDATA	#REQUIRED
	externalpropid		CDATA	#IMPLIED>

<!ELEMENT options
    (option+
    )>
<!ATTLIST option
    name                CDATA   #REQUIRED
    value               CDATA   #REQUIRED>

<!ELEMENT usesdevicedependencies
	(usesdevice+
	)>

<!ELEMENT usesdevice
	( propertyref
	  | simpleref
	  | simplesequenceref
	  | structref
	  | structsequenceref
	)+ >
<!ATTLIST usesdevice
	id			CDATA	#REQUIRED
	type		CDATA	#IMPLIED>

<!ELEMENT propertyref EMPTY>
<!ATTLIST propertyref
	refid		CDATA	#REQUIRED
	value		CDATA	#REQUIRED>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dom/waveforms/logger_py_w/logger_py_w.sad.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE softwareassembly PUBLIC "-//JTRS//DTD SCA V2.2.2 SAD//EN" "softwareassembly.dtd">
<softwareassembly id="DCE:1f44ec52-bcfb-4ea3-ac6f-dc316b308aab" name="logger_py_w">
  <componentfiles>
    <componentfile id="logger_dd4afdb2-7405-4d7a-8fd1-cf54668b6c14" type="SPD">
      <localfile name="/components/logger_py/logger_py.spd.xml"/>
    </componentfile>
  </componentfiles>
  <partitioning>
    <componentplacement>
      <componentfileref refid="logger_dd4afdb2-7405-4d7a-8fd1-cf54668b6c14"/>
      <componentinstantiation id="logger_py_1" startorder="0">
        <usagename>logger_py_1</usagename>
        <findcomponent>
          <namingservice name="logger_py_1"/>
        </findcomponent>
      </componentinstantiation>
    </componentplacement>
    <componentplacement>
      <componentfileref refid="logger_dd4afdb2-7405-4d7a-8fd1-cf54668b6c14"/>
      <componentinstantiation id="logger_py_2" startorder="1">
        <usagename>logger_py_2</usagename>
        <findcomponent>
          <namingservice name="logger_py_2"/>
        </findcomponent>
      </componentinstantiation>
    </componentplacement>
  </partitioning>
  <assemblycontroller>
    <componentinstantiationref refid="logger_py_1"/>
  </assemblycontroller>
</softwareassembly>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dom/waveforms/NicAllocWave/NicAllocWavePy.sad.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
This file is protected by Copyright. Please refer to the COPYRIGHT file
distributed with this source distribution.

This file is part of REDHAWK core.

REDHAWK core is free software: you can redistribute it and/or modify it under
the terms of the GNU Lesser General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version.

REDHAWK core is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more
details.

You should have received a copy of the GNU Lesser General Public License along
with this program.  If not, see http://www.gnu.org/licenses/.
-->
<!DOCTYPE softwareassembly PUBLIC "-//JTRS//DTD SCA V2.2.2 SAD//EN" "softwareassembly.dtd">
<softwareassembly id="DCE:791b9520-bb9b-4701-837d-6712d48fc5e9" name="NicAllocWavePy">
  <componentfiles>
    <componentfile id="NicAllocPy_0a4e2150-4499-45ee-ba5b-af4fa4d8b546" type="SPD">
      <localfile name="/components/NicAlloc/NicAllocPy.spd.xml"/>
    </componentfile>
  </componentfiles>
  <partitioning>
    <componentplacement>
      <componentfileref refid="NicAllocPy_0a4e2150-4499-45ee-ba5b-af4fa4d8b546"/>
      <componentinstantiation id="NicAllocPy_1" startorder="0">
        <usagename>NicAllocPy_1</usagename>
        <findcomponent>
          <namingservice name="NicAllocPy_1"/>
        </findcomponent>
      </componentinstantiation>
    </componentplacement>
  </partitioning>
  <assemblycontroller>
    <componentinstantiationref refid="NicAllocPy_1"/>
  </assemblycontroller>
</softwareassembly>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dom/waveforms/CommandWrapperStartOrderTests/CommandWrapperWithOrder.sad.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
This file is protected by Copyright. Please refer to the COPYRIGHT file 
distributed with this source distribution.

This file is part of REDHAWK core.

REDHAWK core is free software: you can redistribute it and/or modify it under 
the terms of the GNU Lesser General Public License as published by the Free 
Software Foundation, either version 3 of the License, or (at your option) any 
later version.

REDHAWK core is distributed in the hope that it will be useful, but WITHOUT ANY 
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR 
A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more 
details.

You should have received a copy of the GNU Lesser General Public License along 
with this program.  If not, see http://www.gnu.org/licenses/.
-->

<!DOCTYPE softwareassembly PUBLIC "-//JTRS//DTD SCA V2.2.2 SAD//EN" "softwareassembly.dtd">
<softwareassembly id="DCE:e6b136d5-6bf2-48ee-b2ec-52ceb9b80194" name="CommandWrapperWithOrder">
	<componentfiles>
		<componentfile id="CommandWrapperStartCounter_bfbfc18d-206a-4432-8a71-e219882abff2" type="SPD">
			<localfile name="/components/CommandWrapperStartCounter/CommandWrapperStartCounter.spd.xml" />
		</componentfile>
	</componentfiles>
	<partitioning>
		<componentplacement>
			<componentfileref refid="CommandWrapperStartCounter_bfbfc18d-206a-4432-8a71-e219882abff2" />
			<componentinstantiation id="myid1">
				<usagename>CWSC1</usagename>
				<findcomponent>
					<namingservice name="CWSC1" />
				</findcomponent>
			</componentinstantiation>
		</componentplacement>
		<componentplacement>
			<componentfileref refid="CommandWrapperStartCounter_bfbfc18d-206a-4432-8a71-e219882abff2" />
			<componentinstantiation id="myid2" startorder="1">
				<usagename>CWSC2</usagename>
				<findcomponent>
					<namingservice name="CWSC2" />
				</findcomponent>
			</componentinstantiation>
		</componentplacement>
		<componentplacement>
			<componentfileref refid="CommandWrapperStartCounter_bfbfc18d-206a-4432-8a71-e219882abff2" />
			<componentinstantiation id="myid3" startorder="2">
				<usagename>CWSC3</usagename>
				<findcomponent>
					<namingservice name="CWSC3" />
				</findcomponent>
			</componentinstantiation>
		</componentplacement>
		<componentplacement>
			<componentfileref refid="CommandWrapperStartCounter_bfbfc18d-206a-4432-8a71-e219882abff2" />
			<componentinstantiation id="myid4" startorder="3">
				<usagename>CWSC4</usagename>
				<findcomponent>
					<namingservice name="CWSC4" />
				</findcomponent>
			</componentinstantiation>
		</componentplacement>
	</partitioning>
	<assemblycontroller>
		<componentinstantiationref refid="myid1" />
	</assemblycontroller>
</softwareassembly>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dom/waveforms/NicAllocWave/NicAllocWaveCpp.sad.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
This file is protected by Copyright. Please refer to the COPYRIGHT file
distributed with this source distribution.

This file is part of REDHAWK core.

REDHAWK core is free software: you can redistribute it and/or modify it under
the terms of the GNU Lesser General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version.

REDHAWK core is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more
details.

You should have received a copy of the GNU Lesser General Public License along
with this program.  If not, see http://www.gnu.org/licenses/.
-->
<!DOCTYPE softwareassembly PUBLIC "-//JTRS//DTD SCA V2.2.2 SAD//EN" "softwareassembly.dtd">
<softwareassembly id="DCE:c5cc84c9-5ebc-4f52-99d4-44cb8d626dc7" name="NicAllocWaveCpp">
  <componentfiles>
    <componentfile id="NicAllocCpp_0a4e2150-4499-45ee-ba5b-af4fa4d8b546" type="SPD">
      <localfile name="/components/NicAlloc/NicAllocCpp.spd.xml"/>
    </componentfile>
  </componentfiles>
  <partitioning>
    <componentplacement>
      <componentfileref refid="NicAllocCpp_0a4e2150-4499-45ee-ba5b-af4fa4d8b546"/>
      <componentinstantiation id="NicAllocCpp_1" startorder="0">
        <usagename>NicAllocCpp_1</usagename>
        <findcomponent>
          <namingservice name="NicAllocCpp_1"/>
        </findcomponent>
      </componentinstantiation>
    </componentplacement>
  </partitioning>
  <assemblycontroller>
    <componentinstantiationref refid="NicAllocCpp_1"/>
  </assemblycontroller>
</softwareassembly>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dom/waveforms/CommandWrapperWithRelativePaths/CommandWrapper.sad.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
This file is protected by Copyright. Please refer to the COPYRIGHT file 
distributed with this source distribution.

This file is part of REDHAWK core.

REDHAWK core is free software: you can redistribute it and/or modify it under 
the terms of the GNU Lesser General Public License as published by the Free 
Software Foundation, either version 3 of the License, or (at your option) any 
later version.

REDHAWK core is distributed in the hope that it will be useful, but WITHOUT ANY 
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR 
A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more 
details.

You should have received a copy of the GNU Lesser General Public License along 
with this program.  If not, see http://www.gnu.org/licenses/.
-->

<!DOCTYPE softwareassembly PUBLIC '-//JTRS//DTD SCA V2.2.2 SAD//EN' 'softwareassembly.dtd'>
<softwareassembly id="DCE:8ea0dcee-a953-11de-9d50-001cc4ed247c" name="CommandWrapperWithRelativePaths">
    <componentfiles>
        <componentfile id="CommandWrapper_592b8bd6-b011-4468-9417-705af45e907b" type="SPD">
            <localfile name="/components/CommandWrapperWithRelativePaths/CommandWrapper.spd.xml"/>
        </componentfile>
    </componentfiles>
    <partitioning>
        <componentplacement>
            <componentfileref refid="CommandWrapper_592b8bd6-b011-4468-9417-705af45e907b"/>
            <componentinstantiation id="DCE:a39e37bc-280e-406f-9952-5beee6575fb4">
                <usagename>CommandWrapper1</usagename> 
                <findcomponent>
                    <namingservice name="CommandWrapper1"/>
                </findcomponent>
            </componentinstantiation>
        </componentplacement>
    </partitioning>
    <assemblycontroller>
        <componentinstantiationref refid="DCE:a39e37bc-280e-406f-9952-5beee6575fb4"/>
    </assemblycontroller>
    <connections>
    </connections>
</softwareassembly>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dom/waveforms/ticket_cf_1066_wf/ticket_cf_1066_wf.sad.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE softwareassembly PUBLIC "-//JTRS//DTD SCA V2.2.2 SAD//EN" "softwareassembly.dtd">
<softwareassembly id="DCE:c845059e-6b18-46d9-b31e-3406fc510336" name="ticket_cf_1066_wf">
  <componentfiles>
    <componentfile id="ticket_cf_1066_comp_31d0e725-b829-48cc-a9b8-415f5c0d486b" type="SPD">
      <localfile name="/components/ticket_cf_1066_comp/ticket_cf_1066_comp.spd.xml"/>
    </componentfile>
  </componentfiles>
  <partitioning>
    <componentplacement>
      <componentfileref refid="ticket_cf_1066_comp_31d0e725-b829-48cc-a9b8-415f5c0d486b"/>
      <componentinstantiation id="ticket_cf_1066_comp_1" startorder="0">
        <usagename>ticket_cf_1066_comp_1</usagename>
        <componentproperties>
          <simpleref refid="simple_prop" value="This is a string"/>
          <simplesequenceref refid="seq_prop">
            <values>
              <value>9</value>
              <value>8</value>
              <value>7</value>
            </values>
          </simplesequenceref>
          <structref refid="struct_prop">
            <simpleref refid="prop_two" value="string override"/>
          </structref>
          <structsequenceref refid="struct_seq_prop">
            <structvalue>
              <simpleref refid="prop_five" value="1"/>
              <simpleref refid="prop_six" value="123.0"/>
            </structvalue>
            <structvalue>
              <simpleref refid="prop_four" value="anotherString"/>
              <simpleref refid="prop_six" value="345.0"/>
            </structvalue>
            <structvalue>
              <simpleref refid="prop_four" value="string_override"/>
              <simpleref refid="prop_five" value="3"/>
              <simpleref refid="prop_six" value="678.0"/>
            </structvalue>
            <structvalue>
              <simpleref refid="prop_six" value="987.0"/>
            </structvalue>
          </structsequenceref>
        </componentproperties>
        <findcomponent>
          <namingservice name="ticket_cf_1066_comp_1"/>
        </findcomponent>
      </componentinstantiation>
    </componentplacement>
  </partitioning>
  <assemblycontroller>
    <componentinstantiationref refid="ticket_cf_1066_comp_1"/>
  </assemblycontroller>
</softwareassembly>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dom/waveforms/SimpleWaveform/SimpleWaveform.sad.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
This file is protected by Copyright. Please refer to the COPYRIGHT file 
distributed with this source distribution.

This file is part of REDHAWK core.

REDHAWK core is free software: you can redistribute it and/or modify it under 
the terms of the GNU Lesser General Public License as published by the Free 
Software Foundation, either version 3 of the License, or (at your option) any 
later version.

REDHAWK core is distributed in the hope that it will be useful, but WITHOUT ANY 
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR 
A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more 
details.

You should have received a copy of the GNU Lesser General Public License along 
with this program.  If not, see http://www.gnu.org/licenses/.
-->

<!DOCTYPE softwareassembly PUBLIC "-//JTRS//DTD SCA V2.2.2 SAD//EN" "softwareassembly.dtd">
<softwareassembly id="DCE:3f029894-0464-4cf5-a50b-84a06229bc3d" name="SimpleWaveform">
  <componentfiles>
    <componentfile id="SimpleComponent_4da30adb-29ac-451b-adcd-59e67cfe49ef" type="SPD">
      <localfile name="/components/SimpleComponent/SimpleComponent.spd.xml"/>
    </componentfile>
  </componentfiles>
  <partitioning>
    <componentplacement>
      <componentfileref refid="SimpleComponent_4da30adb-29ac-451b-adcd-59e67cfe49ef"/>
      <componentinstantiation id="DCE:6a4bb53b-258a-4a17-a05c-be58c7030e01">
        <usagename>SimpleComponent_1</usagename>
        <componentproperties>
            <simpleref refid="DCE:c709f95e-6b05-439a-9db9-dba95e70888e" value="new execparam value"/>
            <simpleref refid="DCE:6ea8108d-76ea-4532-9255-01684ad68429" value="new configured value"/>
            <simpleref refid="DCE:07350439-e917-45ef-b71f-a-bad-id" value="some bad id"/>
            <simpleref refid="DCE:10add64d-1160-4de0-885b-46a991f52f1d" value="255"/>
        </componentproperties>
        <findcomponent>
          <namingservice name="SimpleComponent_1"/>
        </findcomponent>
      </componentinstantiation>
    </componentplacement>
  </partitioning>
  <assemblycontroller>
    <componentinstantiationref refid="DCE:6a4bb53b-258a-4a17-a05c-be58c7030e01"/>
  </assemblycontroller>
</softwareassembly>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dom/waveforms/loggingconfig/TestCpp/TestCpp_props.sad.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
This file is protected by Copyright. Please refer to the COPYRIGHT file 
distributed with this source distribution.

This file is part of REDHAWK core.

REDHAWK core is free software: you can redistribute it and/or modify it under 
the terms of the GNU Lesser General Public License as published by the Free 
Software Foundation, either version 3 of the License, or (at your option) any 
later version.

REDHAWK core is distributed in the hope that it will be useful, but WITHOUT ANY 
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR 
A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more 
details.

You should have received a copy of the GNU Lesser General Public License along 
with this program.  If not, see http://www.gnu.org/licenses/.
-->

<!DOCTYPE softwareassembly PUBLIC '-//JTRS//DTD SCA V2.2.2 SAD//EN' 'softwareassembly.dtd'>
<softwareassembly id="testcpp-props-wave" name="testcpp-props-wave" version="1.0">
    <componentfiles>
        <componentfile id="testcpp_file_1" type="SPD">
            <localfile name="/components/C2/C2.spd.xml"/>
        </componentfile>
    </componentfiles>
    <partitioning>
        <componentplacement>
            <componentfileref refid="testcpp_file_1"/>
            <componentinstantiation id="testcpp-props-wave:C2_1">
                <usagename>C2_1</usagename>
                <componentproperties>
                  <simpleref refid="LOGGING_CONFIG_URI" value="sca://logcfg/log.props.c2" />
                </componentproperties>
                <findcomponent>
                    <namingservice name="C2_1"/>
                </findcomponent>
            </componentinstantiation>
        </componentplacement>
    </partitioning>
    <assemblycontroller>
        <componentinstantiationref refid="testcpp-props-wave:C2_1"/>
    </assemblycontroller>
    <connections>
    </connections>
</softwareassembly>
