=== RedhawkSDR/core-framework/redhawk/src/xml/dtd/softwareassembly.dtd
<!--
This file is protected by Copyright. Please refer to the COPYRIGHT file 
distributed with this source distribution.

This file is part of REDHAWK core.

REDHAWK core is free software: you can redistribute it and/or modify it under 
the terms of the GNU Lesser General Public License as published by the Free 
Software Foundation, either version 3 of the License, or (at your option) any 
later version.

REDHAWK core is distributed in the hope that it will be useful, but WITHOUT ANY 
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR 
A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more 
details.

You should have received a copy of the GNU Lesser General Public License along 
with this program.  If not, see http://www.gnu.org/licenses/.
-->

<!ELEMENT softwareassembly
	( description?
	, componentfiles
	, partitioning
	, assemblycontroller
	, connections?
	, externalports?
	, externalproperties?
	, options?
	, usesdevicedependencies?
	)>
<!ATTLIST softwareassembly
	id		ID	#REQUIRED
	name		CDATA	#IMPLIED
	version		CDATA	#IMPLIED>

<!ELEMENT description (#PCDATA)>

<!ELEMENT componentfiles 
	( componentfile+
	)>

<!ELEMENT componentfile
	( localfile 
	)>
<!ATTLIST componentfile
	id		ID	#REQUIRED
	type		CDATA	#IMPLIED>

<!ELEMENT localfile EMPTY>
<!ATTLIST localfile
	name		CDATA	#REQUIRED>

<!ELEMENT partitioning 
	( componentplacement
	|  hostcollocation
	)*>

<!ELEMENT componentplacement 
	( componentfileref
	, componentinstantiation+
	)>

<!ELEMENT componentfileref  EMPTY>
<!ATTLIST componentfileref
	refid		CDATA	#REQUIRED>

<!ELEMENT componentinstantiation
	( usagename?
	, componentproperties?
        , affinity?
        , loggingconfig?
	, findcomponent?
	, devicerequires?
	)>
<!ATTLIST componentinstantiation
	id		ID 	#REQUIRED
	startorder	CDATA	#IMPLIED>

<!ELEMENT usagename (#PCDATA)>

<!ELEMENT loggingconfig (#PCDATA)>
<!ATTLIST loggingconfig 
          level CDATA #IMPLIED >

<!ELEMENT affinity
	( simpleref
	| simplesequenceref
	| structref
	| structsequenceref
	)+ >

<!ELEMENT devicerequires
	( requires
	)+ >

<!ELEMENT componentproperties 
	( simpleref
	| simplesequenceref
	| structref
	| structsequenceref
	)+ >

<!ELEMENT findcomponent
	( componentresourcefactoryref
	| namingservice
	)>

<!ELEMENT componentresourcefactoryref
	( resourcefactoryproperties?
	)>
<!ATTLIST componentresourcefactoryref 
	refid		CDATA	#REQUIRED>

<!ELEMENT devicethatloadedthiscomponentref EMPTY>
<!ATTLIST devicethatloadedthiscomponentref 
	refid		CDATA	#REQUIRED>

<!ELEMENT deviceusedbythiscomponentref EMPTY>
<!ATTLIST deviceusedbythiscomponentref 
	refid		CDATA	#REQUIRED
	usesrefid	CDATA	#REQUIRED>

<!ELEMENT deviceusedbyapplication EMPTY>
<!ATTLIST deviceusedbyapplication
	usesrefid	CDATA	#REQUIRED>

<!ELEMENT resourcefactoryproperties 
	( simpleref
	| simplesequenceref
	| structref
	| structsequenceref
	)+ >

<!ELEMENT requires EMPTY>
<!ATTLIST requires
	id		CDATA	#REQUIRED
	value		CDATA	#REQUIRED>

<!ELEMENT simpleref EMPTY>
<!ATTLIST simpleref
	refid		CDATA	#REQUIRED
	value		CDATA	#REQUIRED>
		
<!ELEMENT simplesequenceref
	(values
	)>
<!ATTLIST simplesequenceref
	refid		CDATA	#REQUIRED>

<!ELEMENT structref
	( (simpleref | simplesequenceref)+       
	)>
<!ATTLIST structref
	refid		CDATA	#REQUIRED>

<!ELEMENT structsequenceref
	( structvalue+
	)>
<!ATTLIST structsequenceref
	refid		CDATA	#REQUIRED>

<!ELEMENT structvalue
	( (simpleref | simplesequenceref)+
	)>
		
<!ELEMENT values
	( value+ 
	)>
		
<!ELEMENT value (#PCDATA)>

<!ELEMENT componentinstantiationref EMPTY>
<!ATTLIST componentinstantiationref 
	refid		CDATA	#REQUIRED>

<!ELEMENT findby
	( namingservice
	| stringifiedobjectref
	| domainfinder
	)>

<!ELEMENT namingservice EMPTY>
<!ATTLIST namingservice
	name 		CDATA	#REQUIRED>

<!ELEMENT stringifiedobjectref (#PCDATA)>

<!ELEMENT domainfinder EMPTY>
<!ATTLIST domainfinder
	type		CDATA	#REQUIRED
	name		CDATA	#IMPLIED>

<!ELEMENT hostcollocation
	( componentplacement+
        , usesdeviceref*
        , reservation*
	)>

<!ATTLIST hostcollocation
	id		ID	#IMPLIED
	name		CDATA	#IMPLIED>

<!ELEMENT usesdeviceref EMPTY>
<!ATTLIST usesdeviceref
	refid		CDATA	#REQUIRED>

<!ELEMENT reservation EMPTY>
<!ATTLIST reservation
    kind        CDATA   #REQUIRED
    value       CDATA   #REQUIRED>

<!ELEMENT assemblycontroller
	( componentinstantiationref
	)>

<!ELEMENT connections
	( connectinterface*
	)>

<!ELEMENT connectinterface
	( usesport
	, ( providesport
	  | componentsupportedinterface
	  | findby
	  )
	)>
<!ATTLIST connectinterface
	id 		ID	#IMPLIED>

<!ELEMENT usesport
	( usesidentifier
	, (componentinstantiationref
	   | devicethatloadedthiscomponentref
	   | deviceusedbythiscomponentref
	   | deviceusedbyapplication
	   | findby
	   )
	)>

<!ELEMENT usesidentifier (#PCDATA)>

<!ELEMENT providesport
	( providesidentifier
	, ( componentinstantiationref
	  | devicethatloadedthiscomponentref
	  | deviceusedbythiscomponentref
	  | deviceusedbyapplication
	  | findby 
        )
	)>

<!ELEMENT providesidentifier (#PCDATA)>

<!ELEMENT componentsupportedinterface
	( supportedidentifier
	, ( componentinstantiationref
	  | devicethatloadedthiscomponentref
	  | deviceusedbythiscomponentref
	  | deviceusedbyapplication
	  | findby
	  )
	)>

<!ELEMENT supportedidentifier (#PCDATA)>

<!ELEMENT externalports 
	(port+
	)>

<!ELEMENT port
	( description?
	, (usesidentifier | providesidentifier | supportedidentifier)
	, componentinstantiationref
	)>
<!ATTLIST port
	externalname 		CDATA	#IMPLIED>

<!ELEMENT externalproperties
	(property+
	)>

<!ELEMENT property EMPTY>
<!ATTLIST property
	comprefid			CDATA	#REQUIRED
	propid				CDATA	#REQUIRED
	externalpropid		CDATA	#IMPLIED>

<!ELEMENT options
    (option+
    )>
<!ATTLIST option
    name                CDATA   #REQUIRED
    value               CDATA   #REQUIRED>

<!ELEMENT usesdevicedependencies
	(usesdevice+
	)>

<!ELEMENT usesdevice
	( propertyref
	  | simpleref
	  | simplesequenceref
	  | structref
	  | structsequenceref
	)+ >
<!ATTLIST usesdevice
	id			CDATA	#REQUIRED
	type		CDATA	#IMPLIED>

<!ELEMENT propertyref EMPTY>
<!ATTLIST propertyref
	refid		CDATA	#REQUIRED
	value		CDATA	#REQUIRED>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dom/waveforms/cpp_comp_aware_w/cpp_comp_aware_w.sad.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
This file is protected by Copyright. Please refer to the COPYRIGHT file
distributed with this source distribution.

This file is part of REDHAWK core.

REDHAWK core is free software: you can redistribute it and/or modify it under
the terms of the GNU Lesser General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version.

REDHAWK core is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more
details.

You should have received a copy of the GNU Lesser General Public License along
with this program.  If not, see http://www.gnu.org/licenses/.
-->
<!DOCTYPE softwareassembly PUBLIC "-//JTRS//DTD SCA V2.2.2 SAD//EN" "softwareassembly.dtd">
<softwareassembly id="DCE:6774de87-310e-4b3e-b151-6e2ea0e8e9c2" name="cpp_comp_w">
  <componentfiles>
    <componentfile id="cpp_comp_e9451062-d2ea-4b33-9366-00fdcd1df5cd" type="SPD">
      <localfile name="/components/cpp_comp/cpp_comp.spd.xml"/>
    </componentfile>
  </componentfiles>
  <partitioning>
    <componentplacement>
      <componentfileref refid="cpp_comp_e9451062-d2ea-4b33-9366-00fdcd1df5cd"/>
      <componentinstantiation id="cpp_comp_1" startorder="0">
        <usagename>cpp_comp_1</usagename>
        <findcomponent>
          <namingservice name="cpp_comp_1"/>
        </findcomponent>
      </componentinstantiation>
    </componentplacement>
  </partitioning>
  <assemblycontroller>
    <componentinstantiationref refid="cpp_comp_1"/>
  </assemblycontroller>
  <options>
      <option name="AWARE_APPLICATION" value="false"/>
  </options>
</softwareassembly>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dom/waveforms/newtime_w/newtime_w.sad.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE softwareassembly PUBLIC "-//JTRS//DTD SCA V2.2.2 SAD//EN" "softwareassembly.dtd">
<softwareassembly id="DCE:243d883a-0123-4c94-94dc-5c129537f63d" name="newtime_w">
  <componentfiles>
    <componentfile id="newtime_b17cd7cc-aaa8-4cc6-b962-e9afd20840b3" type="SPD">
      <localfile name="/components/newtime/newtime.spd.xml"/>
    </componentfile>
  </componentfiles>
  <partitioning>
    <componentplacement>
      <componentfileref refid="newtime_b17cd7cc-aaa8-4cc6-b962-e9afd20840b3"/>
      <componentinstantiation id="newtime_1" startorder="0">
        <usagename>newtime_1</usagename>
        <componentproperties>
          <simpleref refid="rightnow" value="now"/>
        </componentproperties>
        <findcomponent>
          <namingservice name="newtime_1"/>
        </findcomponent>
      </componentinstantiation>
    </componentplacement>
  </partitioning>
  <assemblycontroller>
    <componentinstantiationref refid="newtime_1"/>
  </assemblycontroller>
</softwareassembly>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dom/waveforms/logger_overload_w/logger_overload_w.sad.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE softwareassembly PUBLIC "-//JTRS//DTD SCA V2.2.2 SAD//EN" "softwareassembly.dtd">
<softwareassembly id="DCE:1f44ec52-bcfb-4ea3-ac6f-dc316b308a00" name="logger_overload_w">
  <componentfiles>
    <componentfile id="logger_dd4afdb2-7405-4d7a-8fd1-cf54668b6c14" type="SPD">
      <localfile name="/components/logger/logger.spd.xml"/>
    </componentfile>
  </componentfiles>
  <partitioning>
    <componentplacement>
      <componentfileref refid="logger_dd4afdb2-7405-4d7a-8fd1-cf54668b6c14"/>
      <componentinstantiation id="logger_1" startorder="0">
        <usagename>logger_1</usagename>
        <findcomponent>
          <namingservice name="logger_1"/>
        </findcomponent>
      </componentinstantiation>
    </componentplacement>
    <componentplacement>
      <componentfileref refid="logger_dd4afdb2-7405-4d7a-8fd1-cf54668b6c14"/>
      <componentinstantiation id="logger_2" startorder="1">
        <usagename>logger_2</usagename>
        <componentproperties>
          <simpleref refid="LOGGING_CONFIG_URI" value='file:///@@@CWD@@@/high_thresh.cfg'/>
        </componentproperties>
        <findcomponent>
          <namingservice name="logger_2"/>
        </findcomponent>
      </componentinstantiation>
    </componentplacement>
  </partitioning>
  <assemblycontroller>
    <componentinstantiationref refid="logger_1"/>
  </assemblycontroller>
</softwareassembly>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dom/waveforms/MessageTestCpp/MessageTestCpp.sad.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
This file is protected by Copyright. Please refer to the COPYRIGHT file 
distributed with this source distribution.

This file is part of REDHAWK core.

REDHAWK core is free software: you can redistribute it and/or modify it under 
the terms of the GNU Lesser General Public License as published by the Free 
Software Foundation, either version 3 of the License, or (at your option) any 
later version.

REDHAWK core is distributed in the hope that it will be useful, but WITHOUT ANY 
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR 
A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more 
details.

You should have received a copy of the GNU Lesser General Public License along 
with this program.  If not, see http://www.gnu.org/licenses/.
-->

<!DOCTYPE softwareassembly PUBLIC '-//JTRS//DTD SCA V2.2.2 SAD//EN' 'softwareassembly.dtd'>
<softwareassembly id="DCE:2370aeff-05f1-4dff-9744-2812de0baf84" name="MessageTestCpp">
    <componentfiles>
        <componentfile id="MessageReceiverCppFile" type="SPD">
            <localfile name="/components/MessageReceiverCpp/MessageReceiverCpp.spd.xml"/>
        </componentfile>
        <componentfile id="MessageSenderCppFile" type="SPD">
            <localfile name="/components/MessageSenderCpp/MessageSenderCpp.spd.xml"/>
        </componentfile>
    </componentfiles>
  <partitioning>
    <componentplacement>
        <componentfileref refid="MessageReceiverCppFile"/>
        <componentinstantiation id="MessageReceiverCpp_1">
            <usagename>MessageReceiverCpp_1</usagename>
            <findcomponent>
                <namingservice name="MessageReceiverCpp_1"/>
            </findcomponent>
        </componentinstantiation>
    </componentplacement>
    <componentplacement>
        <componentfileref refid="MessageSenderCppFile"/>
        <componentinstantiation id="MessageSenderCpp_1">
            <usagename>MessageSenderCpp_1</usagename>
            <findcomponent>
                <namingservice name="MessageSenderCpp_1"/>
            </findcomponent>
        </componentinstantiation>
    </componentplacement>
  </partitioning>
  <assemblycontroller>
      <componentinstantiationref refid="MessageSenderCpp_1"/>
  </assemblycontroller>
  <connections>
      <connectinterface id="direct">
          <usesport>
              <usesidentifier>message_out</usesidentifier>
              <componentinstantiationref refid="MessageSenderCpp_1"/>
          </usesport>
          <providesport>
              <providesidentifier>message_in</providesidentifier>
              <componentinstantiationref refid="MessageReceiverCpp_1"/>
          </providesport>
      </connectinterface>
      <connectinterface id="channel_receiver">
          <usesport>
              <usesidentifier>message_in</usesidentifier>
              <componentinstantiationref refid="MessageReceiverCpp_1"/>
          </usesport>
          <findby>
              <domainfinder type="eventchannel" name="message_two"/>
          </findby>
      </connectinterface>
      <connectinterface id="channel_sender">
          <usesport>
              <usesidentifier>message_out</usesidentifier>
              <componentinstantiationref refid="MessageSenderCpp_1"/>
          </usesport>
          <findby>
              <domainfinder type="eventchannel" name="message_two"/>
          </findby>
      </connectinterface>
  </connections>
</softwareassembly>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dom/waveforms/CppsoftpkgDep/CppsoftpkgDep.sad.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
This file is protected by Copyright. Please refer to the COPYRIGHT file 
distributed with this source distribution.

This file is part of REDHAWK core.

REDHAWK core is free software: you can redistribute it and/or modify it under 
the terms of the GNU Lesser General Public License as published by the Free 
Software Foundation, either version 3 of the License, or (at your option) any 
later version.

REDHAWK core is distributed in the hope that it will be useful, but WITHOUT ANY 
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR 
A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more 
details.

You should have received a copy of the GNU Lesser General Public License along 
with this program.  If not, see http://www.gnu.org/licenses/.
-->

<!DOCTYPE softwareassembly PUBLIC '-//JTRS//DTD SCA V2.2.2 SAD//EN' 'softwareassembly.dtd'>
<softwareassembly id="DCE:78e6f0ae-2f20-4345-8ac8-6b2f5120588c" name="TestCppsoftpkgDep">
    <componentfiles>
        <componentfile id="TestCppsoftpkgDep_592b8bd6-b011-4468-9417-705af45e907b" type="SPD">
            <localfile name="/components/TestCppsoftpkgDeps/TestCppsoftpkgDeps.spd.xml"/>
        </componentfile>
    </componentfiles>
    <partitioning>
        <componentplacement>
            <componentfileref refid="TestCppsoftpkgDep_592b8bd6-b011-4468-9417-705af45e907b"/>
            <componentinstantiation id="DCE:d87a0d0d-8808-45fc-ad6a-44c276aa1e18">
                <usagename>CommandWrapperSPDDep1</usagename> 
                <findcomponent>
                    <namingservice name="TestCppsoftpkgDep1"/>
                </findcomponent>
            </componentinstantiation>
        </componentplacement>
    </partitioning>
    <assemblycontroller>
        <componentinstantiationref refid="DCE:d87a0d0d-8808-45fc-ad6a-44c276aa1e18"/>
    </assemblycontroller>
    <connections>
    </connections>
</softwareassembly>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dom/waveforms/NicAllocWave/NicAllocWaveJava.sad.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
This file is protected by Copyright. Please refer to the COPYRIGHT file
distributed with this source distribution.

This file is part of REDHAWK core.

REDHAWK core is free software: you can redistribute it and/or modify it under
the terms of the GNU Lesser General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version.

REDHAWK core is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more
details.

You should have received a copy of the GNU Lesser General Public License along
with this program.  If not, see http://www.gnu.org/licenses/.
-->
<!DOCTYPE softwareassembly PUBLIC "-//JTRS//DTD SCA V2.2.2 SAD//EN" "softwareassembly.dtd">
<softwareassembly id="DCE:8ced184a-0b38-4876-a7e7-0e63c9872487" name="NicAllocWaveJava">
  <componentfiles>
    <componentfile id="NicAllocJava_c786630d-8b61-45c3-a96f-fb45b2204a41" type="SPD">
      <localfile name="/components/NicAlloc/NicAllocJava.spd.xml"/>
    </componentfile>
  </componentfiles>
  <partitioning>
    <componentplacement>
      <componentfileref refid="NicAllocJava_c786630d-8b61-45c3-a96f-fb45b2204a41"/>
      <componentinstantiation id="NicAllocJava_1" startorder="0">
        <usagename>NicAllocJava_1</usagename>
        <findcomponent>
          <namingservice name="NicAllocJava_1"/>
        </findcomponent>
      </componentinstantiation>
    </componentplacement>
  </partitioning>
  <assemblycontroller>
    <componentinstantiationref refid="NicAllocJava_1"/>
  </assemblycontroller>
</softwareassembly>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dom/waveforms/time_py_now_w/time_py_now_w.sad.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE softwareassembly PUBLIC "-//JTRS//DTD SCA V2.2.2 SAD//EN" "softwareassembly.dtd">
<softwareassembly id="DCE:66829720-bd70-4b86-a061-7add0656513d" name="time_py_now_w">
  <componentfiles>
    <componentfile id="time_py_now_aa8ef331-00c6-45da-b4ad-402f3279af62" type="SPD">
      <localfile name="/components/time_py_now/time_py_now.spd.xml"/>
    </componentfile>
  </componentfiles>
  <partitioning>
    <componentplacement>
      <componentfileref refid="time_py_now_aa8ef331-00c6-45da-b4ad-402f3279af62"/>
      <componentinstantiation id="time_py_now_1" startorder="0">
        <usagename>time_py_now_1</usagename>
        <findcomponent>
          <namingservice name="time_py_now_1"/>
        </findcomponent>
      </componentinstantiation>
    </componentplacement>
  </partitioning>
  <assemblycontroller>
    <componentinstantiationref refid="time_py_now_1"/>
  </assemblycontroller>
</softwareassembly>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dom/waveforms/test_collocation_single/test_collocation_single.sad.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
This file is protected by Copyright. Please refer to the COPYRIGHT file 
distributed with this source distribution.

This file is part of REDHAWK core.

REDHAWK core is free software: you can redistribute it and/or modify it under 
the terms of the GNU Lesser General Public License as published by the Free 
Software Foundation, either version 3 of the License, or (at your option) any 
later version.

REDHAWK core is distributed in the hope that it will be useful, but WITHOUT ANY 
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR 
A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more 
details.

You should have received a copy of the GNU Lesser General Public License along 
with this program.  If not, see http://www.gnu.org/licenses/.
-->

<!DOCTYPE softwareassembly PUBLIC "-//JTRS//DTD SCA V2.2.2 SAD//EN" "softwareassembly.dtd">
<softwareassembly id="DCE:88c7f77d-54be-406b-a716-50babf48beca" name="test_collocation_single">
  <componentfiles>
    <componentfile id="NOOP_CAP_87d4ee48-2e3b-4a3e-9f6f-69746e2af2a4" type="SPD">
      <localfile name="/components/NOOP_CAP/NOOP_CAP.spd.xml"/>
    </componentfile>
  </componentfiles>
  <partitioning>
    <hostcollocation id="ID_COLLECT1" name="COLLOC_SET1">
      <componentplacement>
        <componentfileref refid="NOOP_CAP_87d4ee48-2e3b-4a3e-9f6f-69746e2af2a4"/>
        <componentinstantiation id="NOOP_CAP_1" startorder="0">
          <usagename>NOOP_CAP_1</usagename>
          <findcomponent>
            <namingservice name="NOOP_CAP_1"/>
          </findcomponent>
        </componentinstantiation>
      </componentplacement>
      <componentplacement>
        <componentfileref refid="NOOP_CAP_87d4ee48-2e3b-4a3e-9f6f-69746e2af2a4"/>
        <componentinstantiation id="NOOP_CAP_2" startorder="1">
          <usagename>NOOP_CAP_2</usagename>
          <findcomponent>
            <namingservice name="NOOP_CAP_2"/>
          </findcomponent>
        </componentinstantiation>
      </componentplacement>
    </hostcollocation>
  </partitioning>
  <assemblycontroller>
    <componentinstantiationref refid="NOOP_CAP_1"/>
  </assemblycontroller>
</softwareassembly>
