=== RedhawkSDR/core-framework/redhawk/src/xml/dtd/softwareassembly.dtd
<!--
This file is protected by Copyright. Please refer to the COPYRIGHT file 
distributed with this source distribution.

This file is part of REDHAWK core.

REDHAWK core is free software: you can redistribute it and/or modify it under 
the terms of the GNU Lesser General Public License as published by the Free 
Software Foundation, either version 3 of the License, or (at your option) any 
later version.

REDHAWK core is distributed in the hope that it will be useful, but WITHOUT ANY 
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR 
A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more 
details.

You should have received a copy of the GNU Lesser General Public License along 
with this program.  If not, see http://www.gnu.org/licenses/.
-->

<!ELEMENT softwareassembly
	( description?
	, componentfiles
	, partitioning
	, assemblycontroller
	, connections?
	, externalports?
	, externalproperties?
	, options?
	, usesdevicedependencies?
	)>
<!ATTLIST softwareassembly
	id		ID	#REQUIRED
	name		CDATA	#IMPLIED
	version		CDATA	#IMPLIED>

<!ELEMENT description (#PCDATA)>

<!ELEMENT componentfiles 
	( componentfile+
	)>

<!ELEMENT componentfile
	( localfile 
	)>
<!ATTLIST componentfile
	id		ID	#REQUIRED
	type		CDATA	#IMPLIED>

<!ELEMENT localfile EMPTY>
<!ATTLIST localfile
	name		CDATA	#REQUIRED>

<!ELEMENT partitioning 
	( componentplacement
	|  hostcollocation
	)*>

<!ELEMENT componentplacement 
	( componentfileref
	, componentinstantiation+
	)>

<!ELEMENT componentfileref  EMPTY>
<!ATTLIST componentfileref
	refid		CDATA	#REQUIRED>

<!ELEMENT componentinstantiation
	( usagename?
	, componentproperties?
        , affinity?
        , loggingconfig?
	, findcomponent?
	, devicerequires?
	)>
<!ATTLIST componentinstantiation
	id		ID 	#REQUIRED
	startorder	CDATA	#IMPLIED>

<!ELEMENT usagename (#PCDATA)>

<!ELEMENT loggingconfig (#PCDATA)>
<!ATTLIST loggingconfig 
          level CDATA #IMPLIED >

<!ELEMENT affinity
	( simpleref
	| simplesequenceref
	| structref
	| structsequenceref
	)+ >

<!ELEMENT devicerequires
	( requires
	)+ >

<!ELEMENT componentproperties 
	( simpleref
	| simplesequenceref
	| structref
	| structsequenceref
	)+ >

<!ELEMENT findcomponent
	( componentresourcefactoryref
	| namingservice
	)>

<!ELEMENT componentresourcefactoryref
	( resourcefactoryproperties?
	)>
<!ATTLIST componentresourcefactoryref 
	refid		CDATA	#REQUIRED>

<!ELEMENT devicethatloadedthiscomponentref EMPTY>
<!ATTLIST devicethatloadedthiscomponentref 
	refid		CDATA	#REQUIRED>

<!ELEMENT deviceusedbythiscomponentref EMPTY>
<!ATTLIST deviceusedbythiscomponentref 
	refid		CDATA	#REQUIRED
	usesrefid	CDATA	#REQUIRED>

<!ELEMENT deviceusedbyapplication EMPTY>
<!ATTLIST deviceusedbyapplication
	usesrefid	CDATA	#REQUIRED>

<!ELEMENT resourcefactoryproperties 
	( simpleref
	| simplesequenceref
	| structref
	| structsequenceref
	)+ >

<!ELEMENT requires EMPTY>
<!ATTLIST requires
	id		CDATA	#REQUIRED
	value		CDATA	#REQUIRED>

<!ELEMENT simpleref EMPTY>
<!ATTLIST simpleref
	refid		CDATA	#REQUIRED
	value		CDATA	#REQUIRED>
		
<!ELEMENT simplesequenceref
	(values
	)>
<!ATTLIST simplesequenceref
	refid		CDATA	#REQUIRED>

<!ELEMENT structref
	( (simpleref | simplesequenceref)+       
	)>
<!ATTLIST structref
	refid		CDATA	#REQUIRED>

<!ELEMENT structsequenceref
	( structvalue+
	)>
<!ATTLIST structsequenceref
	refid		CDATA	#REQUIRED>

<!ELEMENT structvalue
	( (simpleref | simplesequenceref)+
	)>
		
<!ELEMENT values
	( value+ 
	)>
		
<!ELEMENT value (#PCDATA)>

<!ELEMENT componentinstantiationref EMPTY>
<!ATTLIST componentinstantiationref 
	refid		CDATA	#REQUIRED>

<!ELEMENT findby
	( namingservice
	| stringifiedobjectref
	| domainfinder
	)>

<!ELEMENT namingservice EMPTY>
<!ATTLIST namingservice
	name 		CDATA	#REQUIRED>

<!ELEMENT stringifiedobjectref (#PCDATA)>

<!ELEMENT domainfinder EMPTY>
<!ATTLIST domainfinder
	type		CDATA	#REQUIRED
	name		CDATA	#IMPLIED>

<!ELEMENT hostcollocation
	( componentplacement+
        , usesdeviceref*
        , reservation*
	)>

<!ATTLIST hostcollocation
	id		ID	#IMPLIED
	name		CDATA	#IMPLIED>

<!ELEMENT usesdeviceref EMPTY>
<!ATTLIST usesdeviceref
	refid		CDATA	#REQUIRED>

<!ELEMENT reservation EMPTY>
<!ATTLIST reservation
    kind        CDATA   #REQUIRED
    value       CDATA   #REQUIRED>

<!ELEMENT assemblycontroller
	( componentinstantiationref
	)>

<!ELEMENT connections
	( connectinterface*
	)>

<!ELEMENT connectinterface
	( usesport
	, ( providesport
	  | componentsupportedinterface
	  | findby
	  )
	)>
<!ATTLIST connectinterface
	id 		ID	#IMPLIED>

<!ELEMENT usesport
	( usesidentifier
	, (componentinstantiationref
	   | devicethatloadedthiscomponentref
	   | deviceusedbythiscomponentref
	   | deviceusedbyapplication
	   | findby
	   )
	)>

<!ELEMENT usesidentifier (#PCDATA)>

<!ELEMENT providesport
	( providesidentifier
	, ( componentinstantiationref
	  | devicethatloadedthiscomponentref
	  | deviceusedbythiscomponentref
	  | deviceusedbyapplication
	  | findby 
        )
	)>

<!ELEMENT providesidentifier (#PCDATA)>

<!ELEMENT componentsupportedinterface
	( supportedidentifier
	, ( componentinstantiationref
	  | devicethatloadedthiscomponentref
	  | deviceusedbythiscomponentref
	  | deviceusedbyapplication
	  | findby
	  )
	)>

<!ELEMENT supportedidentifier (#PCDATA)>

<!ELEMENT externalports 
	(port+
	)>

<!ELEMENT port
	( description?
	, (usesidentifier | providesidentifier | supportedidentifier)
	, componentinstantiationref
	)>
<!ATTLIST port
	externalname 		CDATA	#IMPLIED>

<!ELEMENT externalproperties
	(property+
	)>

<!ELEMENT property EMPTY>
<!ATTLIST property
	comprefid			CDATA	#REQUIRED
	propid				CDATA	#REQUIRED
	externalpropid		CDATA	#IMPLIED>

<!ELEMENT options
    (option+
    )>
<!ATTLIST option
    name                CDATA   #REQUIRED
    value               CDATA   #REQUIRED>

<!ELEMENT usesdevicedependencies
	(usesdevice+
	)>

<!ELEMENT usesdevice
	( propertyref
	  | simpleref
	  | simplesequenceref
	  | structref
	  | structsequenceref
	)+ >
<!ATTLIST usesdevice
	id			CDATA	#REQUIRED
	type		CDATA	#IMPLIED>

<!ELEMENT propertyref EMPTY>
<!ATTLIST propertyref
	refid		CDATA	#REQUIRED
	value		CDATA	#REQUIRED>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dom/waveforms/TestPythonProps/TestPythonProps.sad.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
This file is protected by Copyright. Please refer to the COPYRIGHT file 
distributed with this source distribution.

This file is part of REDHAWK core.

REDHAWK core is free software: you can redistribute it and/or modify it under 
the terms of the GNU Lesser General Public License as published by the Free 
Software Foundation, either version 3 of the License, or (at your option) any 
later version.

REDHAWK core is distributed in the hope that it will be useful, but WITHOUT ANY 
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR 
A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more 
details.

You should have received a copy of the GNU Lesser General Public License along 
with this program.  If not, see http://www.gnu.org/licenses/.
-->

<!DOCTYPE softwareassembly PUBLIC '-//JTRS//DTD SCA V2.2.2 SAD//EN' 'softwareassembly.dtd'>
<softwareassembly id="DCE:7d4ff6a8-afea-485b-a804-9f818062fcb1" name="TestPythonProps">
  <componentfiles>
    <componentfile id="TestPythonProps_c0c68899-dde6-4bfb-a80e-52fc1fb78fd4" type="SPD">
      <localfile name="/components/TestPythonProps/TestPythonProps.spd.xml"/>
    </componentfile>
  </componentfiles>
  <partitioning>
    <componentplacement>
      <componentfileref refid="TestPythonProps_c0c68899-dde6-4bfb-a80e-52fc1fb78fd4"/>
      <componentinstantiation id="DCE:f9d0fa95-4cf7-4ed1-a412-a7b9d2ab0ab1">
        <usagename>TestPythonProps1</usagename>
        <findcomponent>
          <namingservice name="TestPythonProps1"/>
        </findcomponent>
      </componentinstantiation>
    </componentplacement>
  </partitioning>
  <assemblycontroller>
    <componentinstantiationref refid="DCE:f9d0fa95-4cf7-4ed1-a412-a7b9d2ab0ab1"/>
  </assemblycontroller>
  <connections/>
</softwareassembly>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dom/waveforms/CommandWrapperSPDDep_collide/CommandWrapperSPDDep_collide.sad.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
This file is protected by Copyright. Please refer to the COPYRIGHT file 
distributed with this source distribution.

This file is part of REDHAWK core.

REDHAWK core is free software: you can redistribute it and/or modify it under 
the terms of the GNU Lesser General Public License as published by the Free 
Software Foundation, either version 3 of the License, or (at your option) any 
later version.

REDHAWK core is distributed in the hope that it will be useful, but WITHOUT ANY 
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR 
A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more 
details.

You should have received a copy of the GNU Lesser General Public License along 
with this program.  If not, see http://www.gnu.org/licenses/.
-->

<!DOCTYPE softwareassembly PUBLIC '-//JTRS//DTD SCA V2.2.2 SAD//EN' 'softwareassembly.dtd'>
<softwareassembly id="DCE:33057843-192e-47f3-8464-6ac5fa9d0962" name="CommandWrapperSPDDep_collide">
    <componentfiles>
        <componentfile id="CommandWrapperSPDDep_592b8bd6-b011-4468-9417-705af45e907b" type="SPD">
            <localfile name="/components/CommandWrapperSPDDep_collide/CommandWrapperSPDDep.spd.xml"/>
        </componentfile>
    </componentfiles>
    <partitioning>
        <componentplacement>
            <componentfileref refid="CommandWrapperSPDDep_592b8bd6-b011-4468-9417-705af45e907b"/>
            <componentinstantiation id="DCE:9c8c2367-22ad-499a-84a8-0a4a83aeb2ac">
                <usagename>CommandWrapperSPDDep1</usagename> 
                <findcomponent>
                    <namingservice name="CommandWrapperSPDDep1"/>
                </findcomponent>
            </componentinstantiation>
        </componentplacement>
    </partitioning>
    <assemblycontroller>
        <componentinstantiationref refid="DCE:9c8c2367-22ad-499a-84a8-0a4a83aeb2ac"/>
    </assemblycontroller>
    <connections>
    </connections>
</softwareassembly>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dom/waveforms/TestComplexPropsSADOverrides/TestComplexPropsSADOverrides.sad.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
This file is protected by Copyright. Please refer to the COPYRIGHT file
distributed with this source distribution.

This file is part of REDHAWK core.

REDHAWK core is free software: you can redistribute it and/or modify it under
the terms of the GNU Lesser General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version.

REDHAWK core is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more
details.

You should have received a copy of the GNU Lesser General Public License along
with this program.  If not, see http://www.gnu.org/licenses/.
-->
<!DOCTYPE softwareassembly PUBLIC "-//JTRS//DTD SCA V2.2.2 SAD//EN" "softwareassembly.dtd">
<softwareassembly id="DCE:a3d0c1c5-05fd-4c7d-beb5-38fdbd575b2d" name="TestComplexPropsSADOverrides">
  <componentfiles>
    <componentfile id="TestComplexProps_3345fe14-0f29-47d1-89db-b4aab87d9d1d" type="SPD">
      <localfile name="/components/TestComplexProps/TestComplexProps.spd.xml"/>
    </componentfile>
  </componentfiles>
  <partitioning>
    <componentplacement>
      <componentfileref refid="TestComplexProps_3345fe14-0f29-47d1-89db-b4aab87d9d1d"/>
      <componentinstantiation id="TestComplexProps_1" startorder="0">
        <usagename>TestComplexProps_1</usagename>
        <componentproperties>
          <simpleref refid="complexBooleanProp" value="1+j0"/>
          <simpleref refid="complexCharProp" value="2+j3"/>
          <simpleref refid="complexShortProp" value="2+j3"/>
          <simpleref refid="complexFloatProp" value="2+j3"/>
          <simpleref refid="complexUShort" value="2+j3"/>
          <simpleref refid="complexLongLong" value="2+j3"/>
          <simpleref refid="complexDouble" value="2+j3"/>
          <simpleref refid="complexOctetProp" value="2+j3"/>
          <simpleref refid="complexULongProp" value="2+j3"/>
          <simpleref refid="complexULongLong" value="2+j3"/>
          <simpleref refid="complexLong" value="2+j3"/>
          <structref refid="complexFloatStruct">
            <simplesequenceref refid="complexFloatStruct::complex_float_seq">
                <values>
                    <value>-5+j5</value>
                    <value>9-j8</value>
                    <value>-13-j24</value>
                    <value>21-j22</value>
                    <value>31</value>
                    <value>j431</value>
                    <value>-j567</value>
                    <value>-3567</value>
                    <value>-5.25+j5.25</value>
                    <value>9.25-j8.25</value>
                </values>
            </simplesequenceref>
          </structref>
          <simplesequenceref refid="complexFloatSequence">
              <values>
                  <value>1+j2</value>
                  <value>10+j20</value>
              </values>
          </simplesequenceref>
          <structsequenceref refid="complexFloatStructSequence">
              <structvalue>
                <simpleref refid="complexFloatStructSequenceMemberMemember" value="32+j33"/>
                <simplesequenceref refid="complexFloatStructSequence::complex_float_seq">
                    <values>
                        <value>45+j55</value>
                        <value>69+j78</value>
                    </values>
                </simplesequenceref>
              </structvalue>
              <structvalue>
                <simpleref refid="complexFloatStructSequenceMemberMemember" value="42+j43"/>
                <simplesequenceref refid="complexFloatStructSequence::complex_float_seq">
                    <values>
                        <value>145+j155</value>
                        <value>169+j178</value>
                        <value>279+j998</value>
                    </values>
                </simplesequenceref>
              </structvalue>
          </structsequenceref>
        </componentproperties>
        <findcomponent>
          <namingservice name="TestComplexProps_1"/>
        </findcomponent>
      </componentinstantiation>
    </componentplacement>
  </partitioning>
  <assemblycontroller>
    <componentinstantiationref refid="TestComplexProps_1"/>
  </assemblycontroller>
</softwareassembly>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dom/waveforms/ServiceConnection/ServiceConnection.sad.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
This file is protected by Copyright. Please refer to the COPYRIGHT file
distributed with this source distribution.

This file is part of REDHAWK core.

REDHAWK core is free software: you can redistribute it and/or modify it under
the terms of the GNU Lesser General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version.

REDHAWK core is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more
details.

You should have received a copy of the GNU Lesser General Public License along
with this program.  If not, see http://www.gnu.org/licenses/.
-->
<!DOCTYPE softwareassembly PUBLIC "-//JTRS//DTD SCA V2.2.2 SAD//EN" "softwareassembly.dtd">
<softwareassembly id="DCE:70eefaa2-ab8f-4e2b-9fff-0a53b21d8fe1" name="ServiceConnection">
  <componentfiles>
    <componentfile id="ServiceComponent_b9cc5ac4-85bc-453b-9a48-455091343eb4" type="SPD">
      <localfile name="/components/ServiceComponent/ServiceComponent.spd.xml"/>
    </componentfile>
  </componentfiles>
  <partitioning>
    <componentplacement>
      <componentfileref refid="ServiceComponent_b9cc5ac4-85bc-453b-9a48-455091343eb4"/>
      <componentinstantiation id="ServiceComponent_1" startorder="0">
        <usagename>ServiceComponent_1</usagename>
        <findcomponent>
          <namingservice name="ServiceComponent_1"/>
        </findcomponent>
      </componentinstantiation>
    </componentplacement>
  </partitioning>
  <assemblycontroller>
    <componentinstantiationref refid="ServiceComponent_1"/>
  </assemblycontroller>
  <connections>
    <connectinterface id="connection_1">
      <usesport>
        <usesidentifier>output</usesidentifier>
        <componentinstantiationref refid="ServiceComponent_1"/>
      </usesport>
      <findby>
        <namingservice name="BasicService10"/>
      </findby>
    </connectinterface>
  </connections>
</softwareassembly>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dom/waveforms/CommandWrapper/CommandWrapper.sad.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
This file is protected by Copyright. Please refer to the COPYRIGHT file 
distributed with this source distribution.

This file is part of REDHAWK core.

REDHAWK core is free software: you can redistribute it and/or modify it under 
the terms of the GNU Lesser General Public License as published by the Free 
Software Foundation, either version 3 of the License, or (at your option) any 
later version.

REDHAWK core is distributed in the hope that it will be useful, but WITHOUT ANY 
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR 
A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more 
details.

You should have received a copy of the GNU Lesser General Public License along 
with this program.  If not, see http://www.gnu.org/licenses/.
-->

<!DOCTYPE softwareassembly PUBLIC '-//JTRS//DTD SCA V2.2.2 SAD//EN' 'softwareassembly.dtd'>
<softwareassembly id="DCE:8ea0dcee-a953-11de-9d50-001cc4ed247c" name="CommandWrapper" version="1.0">
    <componentfiles>
        <componentfile id="CommandWrapper_592b8bd6-b011-4468-9417-705af45e907b" type="SPD">
            <localfile name="/components/CommandWrapper/CommandWrapper.spd.xml"/>
        </componentfile>
    </componentfiles>
    <partitioning>
        <componentplacement>
            <componentfileref refid="CommandWrapper_592b8bd6-b011-4468-9417-705af45e907b"/>
            <componentinstantiation id="DCE:a39e37bc-280e-406f-9952-5beee6575fb4">
                <usagename>CommandWrapper1</usagename>
		<componentproperties>
		    <simpleref refid="DCE:cf623573-a09d-4fb1-a2ae-24b0b507115d" value="2.0"/>
		    <simpleref refid="DCE:9ec6e2ff-6a4f-4452-8f38-4df47d6eebc1" value="22222222222"/>
		</componentproperties>
                <findcomponent>
                    <namingservice name="CommandWrapper1"/>
                </findcomponent>
            </componentinstantiation>
        </componentplacement>
    </partitioning>
    <assemblycontroller>
        <componentinstantiationref refid="DCE:a39e37bc-280e-406f-9952-5beee6575fb4"/>
    </assemblycontroller>
    <connections>
    </connections>
</softwareassembly>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dom/waveforms/PortConnectDeviceUsedByComponent/PortConnectDeviceUsedByComponent.sad.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
This file is protected by Copyright. Please refer to the COPYRIGHT file 
distributed with this source distribution.

This file is part of REDHAWK core.

REDHAWK core is free software: you can redistribute it and/or modify it under 
the terms of the GNU Lesser General Public License as published by the Free 
Software Foundation, either version 3 of the License, or (at your option) any 
later version.

REDHAWK core is distributed in the hope that it will be useful, but WITHOUT ANY 
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR 
A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more 
details.

You should have received a copy of the GNU Lesser General Public License along 
with this program.  If not, see http://www.gnu.org/licenses/.
-->

<!DOCTYPE softwareassembly PUBLIC '-//JTRS//DTD SCA V2.2.2 SAD//EN' 'softwareassembly.dtd'>
<softwareassembly id="DCE:4e161c85-117e-4f59-b63d-bd25e7bfe770" name="PortConnectDeviceUsedByComponent">
  <componentfiles>
    <componentfile id="PortTest_74fce942-ce9d-48a0-bc18-47093ee04997" type="SPD">
      <localfile name="/components/PortTest/PortTest.spd.xml"/>
    </componentfile>
  </componentfiles>
  <partitioning>
    <componentplacement>
      <componentfileref refid="PortTest_74fce942-ce9d-48a0-bc18-47093ee04997"/>
      <componentinstantiation id="DCE:5faf296f-3193-49cc-8751-f8a64b315fdf">
        <usagename>PortTest1</usagename>
        <findcomponent>
          <namingservice name="PortTest1"/>
        </findcomponent>
      </componentinstantiation>
    </componentplacement>
  </partitioning>
  <assemblycontroller>
    <componentinstantiationref refid="DCE:5faf296f-3193-49cc-8751-f8a64b315fdf"/>
  </assemblycontroller>
  <connections>
    <connectinterface>
      <usesport>
        <usesidentifier>resource_out</usesidentifier>
        <componentinstantiationref refid="DCE:5faf296f-3193-49cc-8751-f8a64b315fdf"/>
      </usesport>
      <providesport>
        <providesidentifier>resource_in</providesidentifier>
        <deviceusedbythiscomponentref refid="DCE:5faf296f-3193-49cc-8751-f8a64b315fdf" usesrefid="DCE:1a02ef64-9fa7-48d3-b2df-67fc3f56f754"/>
      </providesport>
    </connectinterface>
  </connections>
</softwareassembly>

=== RedhawkSDR/core-framework/GPP/tests/sdr/dom/waveforms/wav_two_floor_w/wav_two_floor_w.sad.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
This file is protected by Copyright. Please refer to the COPYRIGHT file
distributed with this source distribution.

This file is part of REDHAWK GPP.

REDHAWK GPP is free software: you can redistribute it and/or modify it under
the terms of the GNU Lesser General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version.

REDHAWK GPP is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more
details.

You should have received a copy of the GNU Lesser General Public License along
with this program.  If not, see http://www.gnu.org/licenses/.
-->
<!DOCTYPE softwareassembly PUBLIC "-//JTRS//DTD SCA V2.2.2 SAD//EN" "softwareassembly.dtd">
<softwareassembly id="DCE:0508d592-25a2-4b05-9e2a-abc08b31b611" name="wav_two_floor_w">
  <componentfiles>
    <componentfile id="busy_comp_24f5c4f2-8d30-4906-beb6-af941498741f" type="SPD">
      <localfile name="/components/busy_comp/busy_comp.spd.xml"/>
    </componentfile>
  </componentfiles>
  <partitioning>
    <hostcollocation id="ID_TEST_SET1" name="COLLOC_SET1">
      <componentplacement>
        <componentfileref refid="busy_comp_24f5c4f2-8d30-4906-beb6-af941498741f"/>
        <componentinstantiation id="busy_comp_1" startorder="0">
          <usagename>busy_comp_1</usagename>
          <findcomponent>
            <namingservice name="busy_comp_1"/>
          </findcomponent>
        </componentinstantiation>
      </componentplacement>
      <reservation kind="cpucores" value="3"/>
    </hostcollocation>
    <hostcollocation id="ID_TEST_SET2" name="COLLOC_SET2">
      <componentplacement>
        <componentfileref refid="busy_comp_24f5c4f2-8d30-4906-beb6-af941498741f"/>
        <componentinstantiation id="busy_comp_2" startorder="1">
          <usagename>busy_comp_2</usagename>
          <findcomponent>
            <namingservice name="busy_comp_2"/>
          </findcomponent>
        </componentinstantiation>
      </componentplacement>
      <reservation kind="cpucores" value="3"/>
    </hostcollocation>
  </partitioning>
  <assemblycontroller>
    <componentinstantiationref refid="busy_comp_1"/>
  </assemblycontroller>
</softwareassembly>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/parser_tests/usesdeviceref.sad.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE softwareassembly PUBLIC "-//JTRS//DTD SCA V2.2.2 SAD//EN" "softwareassembly.dtd">
<softwareassembly id="colloc_usesdev_1" name="colloc_usesdev">
  <componentfiles>
    <componentfile id="P1_file_1" type="SPD">
      <localfile name="/components/P1/P1.spd.xml"/>
    </componentfile>
  </componentfiles>
  <partitioning>
    <hostcollocation name="collocation_1">
      <componentplacement>
        <componentfileref refid="P1_file_1"/>
        <componentinstantiation id="P1_1" startorder="0">
          <usagename>P1_1</usagename>
          <findcomponent>
            <namingservice name="P1_1"/>
          </findcomponent>
        </componentinstantiation>
      </componentplacement>
      <usesdeviceref refid="FrontEndTuner_1"/>
    </hostcollocation>
  </partitioning>
  <assemblycontroller>
    <componentinstantiationref refid="P1_1"/>
  </assemblycontroller>
  <usesdevicedependencies>
    <usesdevice id="FrontEndTuner_1">
      <propertyref refid="DCE:cdc5ee18-7ceb-4ae6-bf4c-31f983179b4d" value="FRONTEND::TUNER"/>
      <structref refid="FRONTEND::tuner_allocation">
        <simpleref refid="FRONTEND::tuner_allocation::tuner_type" value="RX_DIGITIZER"/>
        <simpleref refid="FRONTEND::tuner_allocation::allocation_id" value="8530:25bf3e22-9361-4a69-975b-3bb4363ad214"/>
        <simpleref refid="FRONTEND::tuner_allocation::center_frequency" value="1000000.0"/>
        <simpleref refid="FRONTEND::tuner_allocation::bandwidth" value="1000000.0"/>
        <simpleref refid="FRONTEND::tuner_allocation::bandwidth_tolerance" value="20.0"/>
        <simpleref refid="FRONTEND::tuner_allocation::sample_rate" value="2000000.0"/>
        <simpleref refid="FRONTEND::tuner_allocation::sample_rate_tolerance" value="20.0"/>
        <simpleref refid="FRONTEND::tuner_allocation::device_control" value="true"/>
        <simpleref refid="FRONTEND::tuner_allocation::group_id" value=""/>
        <simpleref refid="FRONTEND::tuner_allocation::rf_flow_id" value=""/>
      </structref>
    </usesdevice>
  </usesdevicedependencies>
</softwareassembly>
