=== RedhawkSDR/core-framework/redhawk/src/control/xml/dtd/softpkg.dtd
<!--
This file is protected by Copyright. Please refer to the COPYRIGHT file 
distributed with this source distribution.

This file is part of REDHAWK core.

REDHAWK core is free software: you can redistribute it and/or modify it under 
the terms of the GNU Lesser General Public License as published by the Free 
Software Foundation, either version 3 of the License, or (at your option) any 
later version.

REDHAWK core is distributed in the hope that it will be useful, but WITHOUT ANY 
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR 
A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more 
details.

You should have received a copy of the GNU Lesser General Public License along 
with this program.  If not, see http://www.gnu.org/licenses/.
-->

<!ELEMENT softpkg
      ( title?
	, author+
	, description?
	, propertyfile?
	, descriptor?
	, implementation+
	, usesdevice*
	)>
<!ATTLIST softpkg
	id		ID	#REQUIRED
	name		CDATA	#REQUIRED
	type		(sca_compliant | sca_non_compliant)  "sca_compliant"
	version	CDATA	#IMPLIED >

<!ELEMENT localfile EMPTY>
<!ATTLIST localfile
	name		CDATA	#REQUIRED>

<!ELEMENT propertyfile
	(localfile
	)>
<!ATTLIST propertyfile
	type		CDATA	#IMPLIED>

<!ELEMENT title (#PCDATA)>

<!ELEMENT pkgtype (#PCDATA)>

<!ELEMENT author 
	( name*
	, company?
	, webpage?
	)>

<!ELEMENT name (#PCDATA)>

<!ELEMENT company (#PCDATA)>

<!ELEMENT webpage (#PCDATA)>

<!ELEMENT description (#PCDATA)>

<!ELEMENT descriptor
	(localfile
	)>
<!ATTLIST descriptor
	name		CDATA	#IMPLIED>

<!ELEMENT implementation
	( description?
	, propertyfile?
	, code
	, compiler?
	, programminglanguage?
	, humanlanguage?
	, runtime?
	, ( os
	  | processor
	  | dependency
	  )+
	, usesdevice*
	)>

<!ATTLIST implementation
	id		ID	#REQUIRED
	aepcompliance (aep_compliant | aep_non_compliant) "aep_compliant">

<!ELEMENT code 
	( localfile
	, entrypoint?
	, stacksize?
	, priority?
	)>
<!ATTLIST code
	type		CDATA	#IMPLIED>

<!ELEMENT entrypoint (#PCDATA)>

<!ELEMENT stacksize (#PCDATA)>

<!ELEMENT priority (#PCDATA)>

<!ELEMENT compiler EMPTY>
<!ATTLIST compiler
	name		CDATA	#REQUIRED
	version 	CDATA	#IMPLIED>

<!ELEMENT programminglanguage EMPTY>
<!ATTLIST programminglanguage
	name		CDATA	#REQUIRED
	version	CDATA	#IMPLIED>

<!ELEMENT humanlanguage EMPTY>
<!ATTLIST humanlanguage
	name		CDATA	#REQUIRED >

<!ELEMENT os EMPTY>
<!ATTLIST os
	name		CDATA	#REQUIRED
	version	CDATA	#IMPLIED>

<!ELEMENT processor EMPTY>
<!ATTLIST processor
	name		CDATA	#REQUIRED>

<!ELEMENT dependency
	( softpkgref
	| propertyref
	| simpleref
	| simplesequenceref
	| structref
	| structsequenceref
	)>
<!ATTLIST dependency
	type		CDATA	#REQUIRED>

<!ELEMENT runtime EMPTY>
<!ATTLIST runtime
	name		CDATA	#REQUIRED
	version	CDATA	#IMPLIED>

<!ELEMENT propertyref EMPTY>
<!ATTLIST propertyref
	refid		CDATA	#REQUIRED
	value		CDATA	#REQUIRED>
	
<!ELEMENT softpkgref
	( localfile
	,  implref?
	)>

<!ELEMENT implref EMPTY>
<!ATTLIST implref 
	refid		CDATA	#REQUIRED>

<!ELEMENT  usesdevice
	( ( propertyref
	  | simpleref
	  | simplesequenceref
	  | structref
	  | structsequenceref
          )+
	)>
<!ATTLIST usesdevice
	id		ID	#REQUIRED
	type		CDATA	#REQUIRED>

<!ELEMENT simpleref EMPTY>
<!ATTLIST simpleref
	refid		CDATA	#REQUIRED
	value		CDATA	#REQUIRED>

<!-- REDHAWK extension: support any property type dependency -->		
<!ELEMENT simplesequenceref
	(values
	)>
<!ATTLIST simplesequenceref
	refid		CDATA	#REQUIRED>

<!ELEMENT structref
	(simpleref+        
	)>
<!ATTLIST structref
	refid		CDATA	#REQUIRED>

<!ELEMENT structsequenceref
	( structvalue+
	)>
<!ATTLIST structsequenceref
	refid		CDATA	#REQUIRED>

<!ELEMENT structvalue
	(simpleref+
	)>
		
<!ELEMENT values
	( value+ 
	)>
		
<!ELEMENT value (#PCDATA)>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dom/components/java_comp/java_comp.spd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
This file is protected by Copyright. Please refer to the COPYRIGHT file
distributed with this source distribution.

This file is part of REDHAWK core.

REDHAWK core is free software: you can redistribute it and/or modify it under
the terms of the GNU Lesser General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version.

REDHAWK core is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more
details.

You should have received a copy of the GNU Lesser General Public License along
with this program.  If not, see http://www.gnu.org/licenses/.
-->
<!DOCTYPE softpkg PUBLIC "-//JTRS//DTD SCA V2.2.2 SPD//EN" "softpkg.dtd">
<softpkg id="DCE:e5ab8d49-28a5-449a-9cbf-52f6286cf967" name="java_comp" type="sca_compliant">
  <title></title>
  <author>
    <name>null</name>
  </author>
  <propertyfile type="PRF">
    <localfile name="java_comp.prf.xml"/>
  </propertyfile>
  <descriptor>
    <localfile name="java_comp.scd.xml"/>
  </descriptor>
  <implementation id="java">
    <description>The implementation contains descriptive information about the template for a software component.</description>
    <code type="Executable">
      <localfile name="java"/>
      <entrypoint>java/startJava.sh</entrypoint>
    </code>
    <compiler name="/usr/bin/javac" version="1.5"/>
    <programminglanguage name="Java"/>
    <humanlanguage name="EN"/>
    <runtime name="/usr/bin/java" version="1.5"/>
    <os name="Linux"/>
    <dependency type="allocation">
      <structref refid="nic_allocation">
        <simpleref refid="nic_allocation::identifier" value="foo"/>
        <simpleref refid="nic_allocation::data_rate" value="1000000"/>
        <simpleref refid="nic_allocation::data_size" value="8"/>
        <simpleref refid="nic_allocation::multicast_support" value=""/>
        <simpleref refid="nic_allocation::ip_addressable" value=""/>
        <simpleref refid="nic_allocation::interface" value=""/>
      </structref>
    </dependency>
  </implementation>
</softpkg>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dev/services/BasicService_cpp/BasicService_cpp.spd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE softpkg PUBLIC "-//JTRS//DTD SCA V2.2.2 SPD//EN" "softpkg.dtd">
<softpkg id="DCE:a14ae592-e293-48a5-b14c-a13105df6f5e" name="BasicService_cpp" type="2.1.0">
  <title></title>
  <author>
    <name>null</name>
  </author>
  <descriptor>
    <localfile name="BasicService_cpp.scd.xml"/>
  </descriptor>
  <implementation id="cpp">
    <description>The implementation contains descriptive information about the template for a software resource.</description>
    <code type="Executable">
      <localfile name="cpp/BasicService_cpp"/>
      <entrypoint>cpp/BasicService_cpp</entrypoint>
    </code>
    <compiler name="/usr/bin/gcc" version="4.4.7"/>
    <programminglanguage name="C++"/>
    <humanlanguage name="EN"/>
    <os name="Linux"/>
    <processor name="x86"/>
    <processor name="x86_64"/>
  </implementation>
</softpkg>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dom/components/math_py/math_py.spd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE softpkg PUBLIC "-//JTRS//DTD SCA V2.2.2 SPD//EN" "softpkg.dtd">
<softpkg id="DCE:d7791487-0dd1-4dea-bd3e-6ae3ff1ec7b7" name="math_py" type="2.0.9">
  <title></title>
  <author>
    <name>null</name>
  </author>
  <propertyfile type="PRF">
    <localfile name="math_py.prf.xml"/>
  </propertyfile>
  <descriptor>
    <localfile name="math_py.scd.xml"/>
  </descriptor>
  <implementation id="python">
    <description>The implementation contains descriptive information about the template for a software resource.</description>
    <code type="Executable">
      <localfile name="python"/>
      <entrypoint>python/math_py.py</entrypoint>
    </code>
    <programminglanguage name="Python"/>
    <humanlanguage name="EN"/>
    <runtime name="python" version="2.6.6"/>
    <os name="Linux"/>
    <dependency type="allocation">
      <propertyref refid="DCE:8dcef419-b440-4bcf-b893-cab79b6024fb" value="__MATH__(0.002,prop1,*)"/>
    </dependency>
  </implementation>
</softpkg>

=== RedhawkSDR/core-framework/throughput/streams/bulkio/reader/reader.spd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
This file is protected by Copyright. Please refer to the COPYRIGHT file
distributed with this source distribution.

This file is part of REDHAWK throughput.

REDHAWK throughput is free software: you can redistribute it and/or modify it under
the terms of the GNU Lesser General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version.

REDHAWK throughput is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more
details.

You should have received a copy of the GNU Lesser General Public License along
with this program.  If not, see http://www.gnu.org/licenses/.
-->
<!DOCTYPE softpkg PUBLIC "-//JTRS//DTD SCA V2.2.2 SPD//EN" "softpkg.dtd">
<softpkg id="DCE:4fd84907-be91-4331-bed5-b54e8ef4d81e" name="reader" type="sca_compliant">
  <title></title>
  <author>
    <name>null</name>
  </author>
  <propertyfile type="PRF">
    <localfile name="reader.prf.xml"/>
  </propertyfile>
  <descriptor>
    <localfile name="reader.scd.xml"/>
  </descriptor>
  <implementation id="cpp">
    <description>The implementation contains descriptive information about the template for a software component.</description>
    <code type="SharedLibrary">
      <localfile name="cpp/reader.so"/>
      <entrypoint>cpp/reader.so</entrypoint>
    </code>
    <compiler name="/usr/bin/gcc" version="4.1.2"/>
    <programminglanguage name="C++"/>
    <humanlanguage name="EN"/>
    <os name="Linux"/>
    <processor name="x86"/>
    <processor name="x86_64"/>
  </implementation>
</softpkg>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dom/components/FailStartup/FailStartup.spd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
This file is protected by Copyright. Please refer to the COPYRIGHT file 
distributed with this source distribution.

This file is part of REDHAWK core.

REDHAWK core is free software: you can redistribute it and/or modify it under 
the terms of the GNU Lesser General Public License as published by the Free 
Software Foundation, either version 3 of the License, or (at your option) any 
later version.

REDHAWK core is distributed in the hope that it will be useful, but WITHOUT ANY 
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR 
A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more 
details.

You should have received a copy of the GNU Lesser General Public License along 
with this program.  If not, see http://www.gnu.org/licenses/.
-->

<!DOCTYPE softpkg PUBLIC "-//JTRS//DTD SCA SPD V2.2.2//EN" "softpkg.dtd">
<softpkg id="DCE:2ef301e1-6c72-4386-a6da-da3d78d45937" name="FailStartup" type="sca_compliant">
  <title></title>
  <author>
    <name></name>
  </author>
  <propertyfile type="PRF">
    <localfile name="FailStartup.prf.xml"/>
  </propertyfile>
  <descriptor>
    <localfile name="FailStartup.scd.xml"/>
  </descriptor>
  <implementation id="DCE:c43af4d8-2750-4cd9-87ec-ae507fc30b30">
    <description>The implementation contains descriptive information about the template for a software component.</description>
    <code type="Executable">
      <localfile name="FailStartup.py"/>
      <entrypoint>FailStartup.py</entrypoint>
    </code>
    <programminglanguage name="Python"/>
    <humanlanguage name="EN"/>
    <runtime name="python" version="2.4.4"/>
    <os name="Linux"/>
    <processor name="x86"/>
    <dependency type="runtime_requirements">
	<!-- Consume mem capacity -->
	<propertyref refid="DCE:8dcef419-b440-4bcf-b893-cab79b6024fb" 
		     value="5000"/>
    </dependency>
    <dependency type="runtime_requirements">
	<!-- BogoMips capacity -->
	<propertyref refid="DCE:5636c210-0346-4df7-a5a3-8fd34c5540a8" value="1000"/>
    </dependency>
  </implementation>
</softpkg>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dev/devices/writeonly_java/writeonly_java.spd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE softpkg PUBLIC "-//JTRS//DTD SCA V2.2.2 SPD//EN" "softpkg.dtd">
<softpkg id="DCE:a1b304c5-676f-4911-a042-f64105b58161" name="writeonly_java" type="2.1.2">
  <title></title>
  <author>
    <name>null</name>
  </author>
  <propertyfile type="PRF">
    <localfile name="writeonly_java.prf.xml"/>
  </propertyfile>
  <descriptor>
    <localfile name="writeonly_java.scd.xml"/>
  </descriptor>
  <implementation id="java">
    <description>The implementation contains descriptive information about the template for a software resource.</description>
    <code type="Executable">
      <localfile name="java"/>
      <entrypoint>java/startJava.sh</entrypoint>
    </code>
    <compiler name="/usr/bin/javac" version="1.7"/>
    <programminglanguage name="Java"/>
    <humanlanguage name="EN"/>
    <runtime name="/usr/bin/java" version="1.7"/>
    <os name="Linux"/>
  </implementation>
</softpkg>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dev/devices/BasicTestDevice_java/BasicTestDevice_java.spd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
This file is protected by Copyright. Please refer to the COPYRIGHT file 
distributed with this source distribution.

This file is part of REDHAWK core.

REDHAWK core is free software: you can redistribute it and/or modify it under 
the terms of the GNU Lesser General Public License as published by the Free 
Software Foundation, either version 3 of the License, or (at your option) any 
later version.

REDHAWK core is distributed in the hope that it will be useful, but WITHOUT ANY 
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR 
A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more 
details.

You should have received a copy of the GNU Lesser General Public License along 
with this program.  If not, see http://www.gnu.org/licenses/.
-->

<!DOCTYPE softpkg PUBLIC "-//JTRS//DTD SCA V2.2.2 SPD//EN" "softpkg.dtd">
<softpkg id="DCE:588b1c4b-8c5b-4f56-a6c4-56ad28e2e47c" name="BasicTestDevice_java" type="sca_compliant">
  <title></title>
  <author>
    <name>null</name>
  </author>
  <propertyfile type="PRF">
    <localfile name="BasicTestDevice_java.prf.xml"/>
  </propertyfile>
  <descriptor>
    <localfile name="BasicTestDevice_java.scd.xml"/>
  </descriptor>
  <implementation id="java">
    <description>The implementation contains descriptive information about the template for a software component.</description>
    <code type="Executable">
      <localfile name="java"/>
      <entrypoint>java/startJava.sh</entrypoint>
    </code>
    <compiler name="/usr/bin/javac" version="1.5"/>
    <programminglanguage name="Java"/>
    <humanlanguage name="EN"/>
    <runtime name="/usr/bin/java" version="1.5"/>
    <os name="Linux"/>
  </implementation>
</softpkg>

=== RedhawkSDR/core-framework/codegenTesting/sdr/dom/components/BasicShared/BasicShared.spd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE softpkg PUBLIC "-//JTRS//DTD SCA V2.2.2 SPD//EN" "softpkg.dtd">
<softpkg id="DCE:5042665c-5d33-40fe-a30f-f72d24dd56ba" name="BasicShared" type="sca_compliant">
  <title></title>
  <author>
    <name>null</name>
  </author>
  <propertyfile type="PRF">
    <localfile name="BasicShared.prf.xml"/>
  </propertyfile>
  <descriptor>
    <localfile name="BasicShared.scd.xml"/>
  </descriptor>
  <implementation id="cpp">
    <description>The implementation contains descriptive information about the template for a software resource.</description>
    <code type="SharedLibrary">
      <localfile name="cpp/BasicShared.so"/>
      <entrypoint>cpp/BasicShared.so</entrypoint>
    </code>
    <compiler name="/usr/bin/gcc" version="4.4.7"/>
    <programminglanguage name="C++"/>
    <humanlanguage name="EN"/>
    <os name="Linux"/>
    <processor name="x86"/>
    <processor name="x86_64"/>
  </implementation>
</softpkg>
