=== RedhawkSDR/core-framework/redhawk/src/control/xml/dtd/softpkg.dtd
<!--
This file is protected by Copyright. Please refer to the COPYRIGHT file 
distributed with this source distribution.

This file is part of REDHAWK core.

REDHAWK core is free software: you can redistribute it and/or modify it under 
the terms of the GNU Lesser General Public License as published by the Free 
Software Foundation, either version 3 of the License, or (at your option) any 
later version.

REDHAWK core is distributed in the hope that it will be useful, but WITHOUT ANY 
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR 
A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more 
details.

You should have received a copy of the GNU Lesser General Public License along 
with this program.  If not, see http://www.gnu.org/licenses/.
-->

<!ELEMENT softpkg
      ( title?
	, author+
	, description?
	, propertyfile?
	, descriptor?
	, implementation+
	, usesdevice*
	)>
<!ATTLIST softpkg
	id		ID	#REQUIRED
	name		CDATA	#REQUIRED
	type		(sca_compliant | sca_non_compliant)  "sca_compliant"
	version	CDATA	#IMPLIED >

<!ELEMENT localfile EMPTY>
<!ATTLIST localfile
	name		CDATA	#REQUIRED>

<!ELEMENT propertyfile
	(localfile
	)>
<!ATTLIST propertyfile
	type		CDATA	#IMPLIED>

<!ELEMENT title (#PCDATA)>

<!ELEMENT pkgtype (#PCDATA)>

<!ELEMENT author 
	( name*
	, company?
	, webpage?
	)>

<!ELEMENT name (#PCDATA)>

<!ELEMENT company (#PCDATA)>

<!ELEMENT webpage (#PCDATA)>

<!ELEMENT description (#PCDATA)>

<!ELEMENT descriptor
	(localfile
	)>
<!ATTLIST descriptor
	name		CDATA	#IMPLIED>

<!ELEMENT implementation
	( description?
	, propertyfile?
	, code
	, compiler?
	, programminglanguage?
	, humanlanguage?
	, runtime?
	, ( os
	  | processor
	  | dependency
	  )+
	, usesdevice*
	)>

<!ATTLIST implementation
	id		ID	#REQUIRED
	aepcompliance (aep_compliant | aep_non_compliant) "aep_compliant">

<!ELEMENT code 
	( localfile
	, entrypoint?
	, stacksize?
	, priority?
	)>
<!ATTLIST code
	type		CDATA	#IMPLIED>

<!ELEMENT entrypoint (#PCDATA)>

<!ELEMENT stacksize (#PCDATA)>

<!ELEMENT priority (#PCDATA)>

<!ELEMENT compiler EMPTY>
<!ATTLIST compiler
	name		CDATA	#REQUIRED
	version 	CDATA	#IMPLIED>

<!ELEMENT programminglanguage EMPTY>
<!ATTLIST programminglanguage
	name		CDATA	#REQUIRED
	version	CDATA	#IMPLIED>

<!ELEMENT humanlanguage EMPTY>
<!ATTLIST humanlanguage
	name		CDATA	#REQUIRED >

<!ELEMENT os EMPTY>
<!ATTLIST os
	name		CDATA	#REQUIRED
	version	CDATA	#IMPLIED>

<!ELEMENT processor EMPTY>
<!ATTLIST processor
	name		CDATA	#REQUIRED>

<!ELEMENT dependency
	( softpkgref
	| propertyref
	| simpleref
	| simplesequenceref
	| structref
	| structsequenceref
	)>
<!ATTLIST dependency
	type		CDATA	#REQUIRED>

<!ELEMENT runtime EMPTY>
<!ATTLIST runtime
	name		CDATA	#REQUIRED
	version	CDATA	#IMPLIED>

<!ELEMENT propertyref EMPTY>
<!ATTLIST propertyref
	refid		CDATA	#REQUIRED
	value		CDATA	#REQUIRED>
	
<!ELEMENT softpkgref
	( localfile
	,  implref?
	)>

<!ELEMENT implref EMPTY>
<!ATTLIST implref 
	refid		CDATA	#REQUIRED>

<!ELEMENT  usesdevice
	( ( propertyref
	  | simpleref
	  | simplesequenceref
	  | structref
	  | structsequenceref
          )+
	)>
<!ATTLIST usesdevice
	id		ID	#REQUIRED
	type		CDATA	#REQUIRED>

<!ELEMENT simpleref EMPTY>
<!ATTLIST simpleref
	refid		CDATA	#REQUIRED
	value		CDATA	#REQUIRED>

<!-- REDHAWK extension: support any property type dependency -->		
<!ELEMENT simplesequenceref
	(values
	)>
<!ATTLIST simplesequenceref
	refid		CDATA	#REQUIRED>

<!ELEMENT structref
	(simpleref+        
	)>
<!ATTLIST structref
	refid		CDATA	#REQUIRED>

<!ELEMENT structsequenceref
	( structvalue+
	)>
<!ATTLIST structsequenceref
	refid		CDATA	#REQUIRED>

<!ELEMENT structvalue
	(simpleref+
	)>
		
<!ELEMENT values
	( value+ 
	)>
		
<!ELEMENT value (#PCDATA)>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dom/components/TestAllPropTypes/CppAllPropTypes.spd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
This file is protected by Copyright. Please refer to the COPYRIGHT file 
distributed with this source distribution.

This file is part of REDHAWK core.

REDHAWK core is free software: you can redistribute it and/or modify it under 
the terms of the GNU Lesser General Public License as published by the Free 
Software Foundation, either version 3 of the License, or (at your option) any 
later version.

REDHAWK core is distributed in the hope that it will be useful, but WITHOUT ANY 
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR 
A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more 
details.

You should have received a copy of the GNU Lesser General Public License along 
with this program.  If not, see http://www.gnu.org/licenses/.
-->

<!DOCTYPE softpkg PUBLIC "-//JTRS//DTD SCA V2.2.2 SPD//EN" "softpkg.dtd">
<softpkg id="DCE:8e2aa59e-6071-44de-95c7-63c1e63ba273" name="TestAllPropTypes" type="sca_compliant">
  <title></title>
  <author>
    <name>null</name>
  </author>
  <propertyfile type="PRF">
    <localfile name="TestAllPropTypes.prf.xml"/>
  </propertyfile>
  <descriptor>
    <localfile name="TestAllPropTypes.scd.xml"/>
  </descriptor>
  <implementation id="cpp">
    <description>The implementation contains descriptive information about the template for a software component.</description>
    <code type="Executable">
      <localfile name="cpp/TestAllPropTypes"/>
      <entrypoint>cpp/TestAllPropTypes</entrypoint>
    </code>
    <compiler name="/usr/bin/gcc" version="4.1.2"/>
    <programminglanguage name="C++"/>
    <humanlanguage name="EN"/>
    <os name="Linux"/>
    <processor name="x86"/>
    <processor name="x86_64"/>
  </implementation>
</softpkg>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dev/devices/log_test_py/log_test_py.spd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE softpkg PUBLIC "-//JTRS//DTD SCA V2.2.2 SPD//EN" "softpkg.dtd">
<softpkg id="DCE:87ee8276-6814-4ebf-8f72-71bcf26baa10" name="log_test_py" type="2.1.3">
  <title></title>
  <author>
    <name>null</name>
  </author>
  <propertyfile type="PRF">
    <localfile name="log_test_py.prf.xml"/>
  </propertyfile>
  <descriptor>
    <localfile name="log_test_py.scd.xml"/>
  </descriptor>
  <implementation id="python">
    <description>The implementation contains descriptive information about the template for a software resource.</description>
    <code type="Executable">
      <localfile name="python"/>
      <entrypoint>python/log_test_py.py</entrypoint>
    </code>
    <programminglanguage name="Python"/>
    <humanlanguage name="EN"/>
    <runtime name="python" version="2.6.6"/>
    <os name="Linux"/>
  </implementation>
</softpkg>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dom/components/busycomp/busycomp.spd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE softpkg PUBLIC "-//JTRS//DTD SCA V2.2.2 SPD//EN" "softpkg.dtd">
<softpkg id="DCE:acae1b18-65c4-40ed-9534-caf5939b00a1" name="busycomp" type="2.1.1">
  <title></title>
  <author>
    <name>null</name>
  </author>
  <propertyfile type="PRF">
    <localfile name="busycomp.prf.xml"/>
  </propertyfile>
  <descriptor>
    <localfile name="busycomp.scd.xml"/>
  </descriptor>
  <implementation id="cpp">
    <description>The implementation contains descriptive information about the template for a software resource.</description>
    <code type="SharedLibrary">
      <localfile name="cpp/busycomp.so"/>
      <entrypoint>cpp/busycomp.so</entrypoint>
    </code>
    <compiler name="/usr/bin/gcc" version="4.4.7"/>
    <programminglanguage name="C++"/>
    <humanlanguage name="EN"/>
    <os name="Linux"/>
    <processor name="x86"/>
    <processor name="x86_64"/>
  </implementation>
</softpkg>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dom/components/alloc_shm/alloc_shm.spd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE softpkg PUBLIC "-//JTRS//DTD SCA V2.2.2 SPD//EN" "softpkg.dtd">
<softpkg id="DCE:6a3edaeb-7e2b-4438-b27e-ee7bf25b59f6" name="alloc_shm" type="2.1.3">
  <title></title>
  <author>
    <name>null</name>
  </author>
  <propertyfile type="PRF">
    <localfile name="alloc_shm.prf.xml"/>
  </propertyfile>
  <descriptor>
    <localfile name="alloc_shm.scd.xml"/>
  </descriptor>
  <implementation id="cpp">
    <description>The implementation contains descriptive information about the template for a software resource.</description>
    <code type="SharedLibrary">
      <localfile name="cpp/alloc_shm.so"/>
      <entrypoint>cpp/alloc_shm.so</entrypoint>
    </code>
    <compiler name="/usr/bin/gcc" version="4.4.7"/>
    <programminglanguage name="C++"/>
    <humanlanguage name="EN"/>
    <os name="Linux"/>
    <processor name="x86"/>
    <processor name="x86_64"/>
  </implementation>
</softpkg>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dom/components/noop_mix_one/noop_mix_one.spd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
This file is protected by Copyright. Please refer to the COPYRIGHT file
distributed with this source distribution.

This file is part of REDHAWK core.

REDHAWK core is free software: you can redistribute it and/or modify it under
the terms of the GNU Lesser General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version.

REDHAWK core is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more
details.

You should have received a copy of the GNU Lesser General Public License along
with this program.  If not, see http://www.gnu.org/licenses/.
-->
<!DOCTYPE softpkg PUBLIC "-//JTRS//DTD SCA V2.2.2 SPD//EN" "softpkg.dtd">
<softpkg id="DCE:db112b07-499f-4148-8768-934a6edec002" name="noop_mix_one" type="sca_compliant">
  <title></title>
  <author>
    <name>null</name>
  </author>
  <propertyfile type="PRF">
    <localfile name="noop_mix_one.prf.xml"/>
  </propertyfile>
  <descriptor>
    <localfile name="noop_mix_one.scd.xml"/>
  </descriptor>
  <implementation id="python">
    <description>The implementation contains descriptive information about the template for a software component.</description>
    <code type="Executable">
      <localfile name="python"/>
      <entrypoint>python/noop_mix_one.py</entrypoint>
    </code>
    <programminglanguage name="Python"/>
    <humanlanguage name="EN"/>
    <runtime name="python" version="2.4.4"/>
    <os name="Linux"/>
    <processor name="x86"/>
    <processor name="x86_64"/>
  </implementation>
</softpkg>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dom/components/ServiceComponent/ServiceComponent.spd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
This file is protected by Copyright. Please refer to the COPYRIGHT file 
distributed with this source distribution.

This file is part of REDHAWK core.

REDHAWK core is free software: you can redistribute it and/or modify it under 
the terms of the GNU Lesser General Public License as published by the Free 
Software Foundation, either version 3 of the License, or (at your option) any 
later version.

REDHAWK core is distributed in the hope that it will be useful, but WITHOUT ANY 
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR 
A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more 
details.

You should have received a copy of the GNU Lesser General Public License along 
with this program.  If not, see http://www.gnu.org/licenses/.
-->

<!DOCTYPE softpkg PUBLIC "-//JTRS//DTD SCA V2.2.2 SPD//EN" "softpkg.dtd">
<softpkg id="DCE:2d7109e7-2e81-4ff5-b139-b79076b1653e" name="ServiceComponent" type="sca_compliant">
  <title></title>
  <author>
    <name>null</name>
  </author>
  <propertyfile type="PRF">
    <localfile name="ServiceComponent.prf.xml"/>
  </propertyfile>
  <descriptor>
    <localfile name="ServiceComponent.scd.xml"/>
  </descriptor>
  <implementation id="python">
    <description>The implementation contains descriptive information about the template for a software component.</description>
    <code type="Executable">
      <localfile name="python"/>
      <entrypoint>python/ServiceComponent.py</entrypoint>
    </code>
    <programminglanguage name="Python"/>
    <humanlanguage name="EN"/>
    <runtime name="python" version="2.4.4"/>
    <os name="Linux"/>
  </implementation>
</softpkg>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dom/components/PropertyChangeEvents/PropertyChangeEvents.spd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
This file is protected by Copyright. Please refer to the COPYRIGHT file 
distributed with this source distribution.

This file is part of REDHAWK core.

REDHAWK core is free software: you can redistribute it and/or modify it under 
the terms of the GNU Lesser General Public License as published by the Free 
Software Foundation, either version 3 of the License, or (at your option) any 
later version.

REDHAWK core is distributed in the hope that it will be useful, but WITHOUT ANY 
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR 
A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more 
details.

You should have received a copy of the GNU Lesser General Public License along 
with this program.  If not, see http://www.gnu.org/licenses/.
-->

<!DOCTYPE softpkg PUBLIC '-//JTRS//DTD SCA V2.2.2 SPD//EN' 'softpkg.dtd'>
<softpkg id="DCE:21b76935-a386-433b-ab8d-c897d470c442" name="PropertyChangeEvents">
    <title/>
    <author>
    </author>
    <description>
        Example property change event port component
    </description>
    <propertyfile type="PRF">
        <localfile name="PropertyChangeEvents.prf.xml"/>
    </propertyfile>
    <descriptor>
        <localfile name="PropertyChangeEvents.scd.xml"/>
    </descriptor>
    <implementation id="DCE:7d8e00da-7948-4b51-b8b9-b9c4eb52426c">
        <description>Python implementation</description>
        <code type="Executable">
            <localfile name="PropertyChangeEvents.py"/>
            <entrypoint>PropertyChangeEvents.py</entrypoint>
        </code>
        <os name="Linux"/>
        <processor name="x86"/>
        <processor name="x86_64"/>
    </implementation>
</softpkg>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dev/devices/BasicTestDeviceNoAllocDeps/BasicTestDevice.spd.xml
<?xml version="1.0" encoding="us-ascii"?>
<!--
This file is protected by Copyright. Please refer to the COPYRIGHT file 
distributed with this source distribution.

This file is part of REDHAWK core.

REDHAWK core is free software: you can redistribute it and/or modify it under 
the terms of the GNU Lesser General Public License as published by the Free 
Software Foundation, either version 3 of the License, or (at your option) any 
later version.

REDHAWK core is distributed in the hope that it will be useful, but WITHOUT ANY 
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR 
A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more 
details.

You should have received a copy of the GNU Lesser General Public License along 
with this program.  If not, see http://www.gnu.org/licenses/.
-->

<!DOCTYPE softpkg PUBLIC '-//JTRS//DTD SCA V2.2.2 SPD//EN' 'softpkg.dtd'>
<softpkg id="DCE:e3d8cda4-441c-425c-9603-6598169866ff" name="BasicTestDeviceNoAllocDeps" type="sca_compliant" version="">
    <title />
    <author>
        <name>REDHAWK test author</name>
    </author>
    <propertyfile type="PRF">
        <localfile name="BasicTestDevice.prf.xml" />
    </propertyfile>
    <descriptor name="">
        <localfile name="BasicTestDevice.scd.xml" />
    </descriptor>
    <!-- Test two implementations, the first one shouldn't match anything 
         and therefore should never be used -->
    <implementation id="DCE:f7cd1dd5-ea37-4a56-9e68-bedd89acdff9" aepcompliance="aep_compliant">
        <code type="Executable">
            <localfile name="NonExistantTestDevice.py" />
            <entrypoint>NonExistantTestDevice.py</entrypoint>
        </code>
        <compiler name="gcc" version="3.4" />
        <humanlanguage name="english" />
        <os name="SCO ODT"/>
        <processor name="ADSP21xx" />
    </implementation>
    <implementation id="DCE:0ef71fab-731d-4ee1-a528-a6da2207e0c5" aepcompliance="aep_compliant">
        <propertyfile type="PRF">
            <localfile name="BasicTestDevice.Linux.x86.prf.xml" />
        </propertyfile>
        <code type="Executable">
            <localfile name="./" />
            <entrypoint>BasicTestDevice.py</entrypoint>
        </code>
        <compiler name="gcc" version="3.4" />
        <humanlanguage name="english" />
        <os name="Linux"/>
        <processor name="x86" />
        <processor name="x86_64" />
    </implementation>
</softpkg>
