=== RedhawkSDR/core-framework/redhawk/src/control/xml/dtd/softpkg.dtd
<!--
This file is protected by Copyright. Please refer to the COPYRIGHT file 
distributed with this source distribution.

This file is part of REDHAWK core.

REDHAWK core is free software: you can redistribute it and/or modify it under 
the terms of the GNU Lesser General Public License as published by the Free 
Software Foundation, either version 3 of the License, or (at your option) any 
later version.

REDHAWK core is distributed in the hope that it will be useful, but WITHOUT ANY 
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR 
A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more 
details.

You should have received a copy of the GNU Lesser General Public License along 
with this program.  If not, see http://www.gnu.org/licenses/.
-->

<!ELEMENT softpkg
      ( title?
	, author+
	, description?
	, propertyfile?
	, descriptor?
	, implementation+
	, usesdevice*
	)>
<!ATTLIST softpkg
	id		ID	#REQUIRED
	name		CDATA	#REQUIRED
	type		(sca_compliant | sca_non_compliant)  "sca_compliant"
	version	CDATA	#IMPLIED >

<!ELEMENT localfile EMPTY>
<!ATTLIST localfile
	name		CDATA	#REQUIRED>

<!ELEMENT propertyfile
	(localfile
	)>
<!ATTLIST propertyfile
	type		CDATA	#IMPLIED>

<!ELEMENT title (#PCDATA)>

<!ELEMENT pkgtype (#PCDATA)>

<!ELEMENT author 
	( name*
	, company?
	, webpage?
	)>

<!ELEMENT name (#PCDATA)>

<!ELEMENT company (#PCDATA)>

<!ELEMENT webpage (#PCDATA)>

<!ELEMENT description (#PCDATA)>

<!ELEMENT descriptor
	(localfile
	)>
<!ATTLIST descriptor
	name		CDATA	#IMPLIED>

<!ELEMENT implementation
	( description?
	, propertyfile?
	, code
	, compiler?
	, programminglanguage?
	, humanlanguage?
	, runtime?
	, ( os
	  | processor
	  | dependency
	  )+
	, usesdevice*
	)>

<!ATTLIST implementation
	id		ID	#REQUIRED
	aepcompliance (aep_compliant | aep_non_compliant) "aep_compliant">

<!ELEMENT code 
	( localfile
	, entrypoint?
	, stacksize?
	, priority?
	)>
<!ATTLIST code
	type		CDATA	#IMPLIED>

<!ELEMENT entrypoint (#PCDATA)>

<!ELEMENT stacksize (#PCDATA)>

<!ELEMENT priority (#PCDATA)>

<!ELEMENT compiler EMPTY>
<!ATTLIST compiler
	name		CDATA	#REQUIRED
	version 	CDATA	#IMPLIED>

<!ELEMENT programminglanguage EMPTY>
<!ATTLIST programminglanguage
	name		CDATA	#REQUIRED
	version	CDATA	#IMPLIED>

<!ELEMENT humanlanguage EMPTY>
<!ATTLIST humanlanguage
	name		CDATA	#REQUIRED >

<!ELEMENT os EMPTY>
<!ATTLIST os
	name		CDATA	#REQUIRED
	version	CDATA	#IMPLIED>

<!ELEMENT processor EMPTY>
<!ATTLIST processor
	name		CDATA	#REQUIRED>

<!ELEMENT dependency
	( softpkgref
	| propertyref
	| simpleref
	| simplesequenceref
	| structref
	| structsequenceref
	)>
<!ATTLIST dependency
	type		CDATA	#REQUIRED>

<!ELEMENT runtime EMPTY>
<!ATTLIST runtime
	name		CDATA	#REQUIRED
	version	CDATA	#IMPLIED>

<!ELEMENT propertyref EMPTY>
<!ATTLIST propertyref
	refid		CDATA	#REQUIRED
	value		CDATA	#REQUIRED>
	
<!ELEMENT softpkgref
	( localfile
	,  implref?
	)>

<!ELEMENT implref EMPTY>
<!ATTLIST implref 
	refid		CDATA	#REQUIRED>

<!ELEMENT  usesdevice
	( ( propertyref
	  | simpleref
	  | simplesequenceref
	  | structref
	  | structsequenceref
          )+
	)>
<!ATTLIST usesdevice
	id		ID	#REQUIRED
	type		CDATA	#REQUIRED>

<!ELEMENT simpleref EMPTY>
<!ATTLIST simpleref
	refid		CDATA	#REQUIRED
	value		CDATA	#REQUIRED>

<!-- REDHAWK extension: support any property type dependency -->		
<!ELEMENT simplesequenceref
	(values
	)>
<!ATTLIST simplesequenceref
	refid		CDATA	#REQUIRED>

<!ELEMENT structref
	(simpleref+        
	)>
<!ATTLIST structref
	refid		CDATA	#REQUIRED>

<!ELEMENT structsequenceref
	( structvalue+
	)>
<!ATTLIST structsequenceref
	refid		CDATA	#REQUIRED>

<!ELEMENT structvalue
	(simpleref+
	)>
		
<!ELEMENT values
	( value+ 
	)>
		
<!ELEMENT value (#PCDATA)>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dom/components/slow_stop_cpp/slow_stop_cpp.spd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE softpkg PUBLIC "-//JTRS//DTD SCA V2.2.2 SPD//EN" "softpkg.dtd">
<softpkg id="DCE:b1ee1f27-45bd-4733-9905-2cc622146167" name="slow_stop_cpp" type="2.0.9">
  <title></title>
  <author>
    <name>null</name>
  </author>
  <propertyfile type="PRF">
    <localfile name="slow_stop_cpp.prf.xml"/>
  </propertyfile>
  <descriptor>
    <localfile name="slow_stop_cpp.scd.xml"/>
  </descriptor>
  <implementation id="cpp">
    <description>The implementation contains descriptive information about the template for a software resource.</description>
    <code type="Executable">
      <localfile name="cpp/slow_stop_cpp"/>
      <entrypoint>cpp/slow_stop_cpp</entrypoint>
    </code>
    <compiler name="/usr/bin/gcc" version="4.4.7"/>
    <programminglanguage name="C++"/>
    <humanlanguage name="EN"/>
    <os name="Linux"/>
    <processor name="x86"/>
    <processor name="x86_64"/>
  </implementation>
</softpkg>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dev/devices/dev_alloc_cpp/dev_alloc_cpp.spd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE softpkg PUBLIC "-//JTRS//DTD SCA V2.2.2 SPD//EN" "softpkg.dtd">
<softpkg id="DCE:0224cbec-6433-418b-922e-580e81376da6" name="dev_alloc_cpp" type="2.1.0">
  <title></title>
  <author>
    <name>null</name>
  </author>
  <propertyfile type="PRF">
    <localfile name="dev_alloc_cpp.prf.xml"/>
  </propertyfile>
  <descriptor>
    <localfile name="dev_alloc_cpp.scd.xml"/>
  </descriptor>
  <implementation id="cpp">
    <description>The implementation contains descriptive information about the template for a software resource.</description>
    <code type="Executable">
      <localfile name="cpp/dev_alloc_cpp"/>
      <entrypoint>cpp/dev_alloc_cpp</entrypoint>
    </code>
    <compiler name="/usr/bin/gcc" version="4.4.7"/>
    <programminglanguage name="C++"/>
    <humanlanguage name="EN"/>
    <os name="Linux"/>
    <processor name="x86"/>
    <processor name="x86_64"/>
  </implementation>
</softpkg>

=== RedhawkSDR/core-framework/codegenTesting/sdr/dom/components/rf_ctrl/rf_ctrl.spd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE softpkg PUBLIC "-//JTRS//DTD SCA V2.2.2 SPD//EN" "softpkg.dtd">
<softpkg id="DCE:18d37976-41a1-45b6-88c3-aa412857dbc6" name="rf_ctrl" type="2.1.3">
  <title></title>
  <author>
    <name>null</name>
  </author>
  <propertyfile type="PRF">
    <localfile name="rf_ctrl.prf.xml"/>
  </propertyfile>
  <descriptor>
    <localfile name="rf_ctrl.scd.xml"/>
  </descriptor>
  <implementation id="cpp">
    <description>The implementation contains descriptive information about the template for a software resource.</description>
    <code type="SharedLibrary">
      <localfile name="cpp/rf_ctrl.so"/>
      <entrypoint>cpp/rf_ctrl.so</entrypoint>
    </code>
    <compiler name="/usr/bin/gcc" version="4.4.7"/>
    <programminglanguage name="C++"/>
    <humanlanguage name="EN"/>
    <os name="Linux"/>
    <processor name="x86"/>
    <processor name="x86_64"/>
  </implementation>
  <implementation id="java">
    <description>The implementation contains descriptive information about the template for a software resource.</description>
    <code type="Executable">
      <localfile name="java"/>
      <entrypoint>java/startJava.sh</entrypoint>
    </code>
    <compiler name="/usr/bin/javac" version="1.7"/>
    <programminglanguage name="Java"/>
    <humanlanguage name="EN"/>
    <runtime name="/usr/bin/java" version="1.7"/>
    <os name="Linux"/>
  </implementation>
  <implementation id="python">
    <description>The implementation contains descriptive information about the template for a software resource.</description>
    <code type="Executable">
      <localfile name="python"/>
      <entrypoint>python/rf_ctrl.py</entrypoint>
    </code>
    <programminglanguage name="Python"/>
    <humanlanguage name="EN"/>
    <runtime name="python" version="2.6.6"/>
    <os name="Linux"/>
  </implementation>
</softpkg>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dev/services/S2/S2.spd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE softpkg PUBLIC "-//JTRS//DTD SCA V2.2.2 SPD//EN" "softpkg.dtd">
<softpkg id="DCE:589206b6-6283-4088-8b40-50c5bd263650" name="S2" type="2.0.4">
  <title></title>
  <author>
    <name>null</name>
  </author>
  <propertyfile>
    <localfile name="S2.prf.xml"/>
  </propertyfile>
  <descriptor>
    <localfile name="S2.scd.xml"/>
  </descriptor>
  <implementation id="python">
    <description>The implementation contains descriptive information about the template for a software component.</description>
    <code type="Executable">
      <localfile name="python"/>
      <entrypoint>python/S2.py</entrypoint>
    </code>
    <programminglanguage name="Python"/>
    <humanlanguage name="EN"/>
    <runtime name="python" version="2.6.6"/>
    <os name="Linux"/>
  </implementation>
</softpkg>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dom/components/cpp_with_deps/cpp_with_deps.spd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE softpkg PUBLIC "-//JTRS//DTD SCA V2.2.2 SPD//EN" "softpkg.dtd">
<softpkg id="DCE:52155a6d-0693-49fe-81cf-4e39db4722aa" name="cpp_with_deps" type="2.0.0">
  <title></title>
  <author>
    <name>null</name>
  </author>
  <propertyfile type="PRF">
    <localfile name="cpp_with_deps.prf.xml"/>
  </propertyfile>
  <descriptor>
    <localfile name="cpp_with_deps.scd.xml"/>
  </descriptor>
  <implementation id="cpp">
    <description>The implementation contains descriptive information about the template for a software component.</description>
    <code type="Executable">
      <localfile name="cpp/cpp_with_deps"/>
      <entrypoint>cpp/cpp_with_deps</entrypoint>
    </code>
    <compiler name="/usr/bin/gcc" version="4.4.7"/>
    <programminglanguage name="C++"/>
    <humanlanguage name="EN"/>
    <os name="Linux"/>
    <processor name="x86"/>
    <processor name="x86_64"/>
    <dependency type="required">
      <softpkgref>
        <localfile name="/deps/cpp_dep1/cpp_dep1.spd.xml"/>
      </softpkgref>
    </dependency>
  </implementation>
</softpkg>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dom/components/default_kinds/default_kinds.spd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
This file is protected by Copyright. Please refer to the COPYRIGHT file
distributed with this source distribution.

This file is part of REDHAWK core.

REDHAWK core is free software: you can redistribute it and/or modify it under
the terms of the GNU Lesser General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version.

REDHAWK core is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more
details.

You should have received a copy of the GNU Lesser General Public License along
with this program.  If not, see http://www.gnu.org/licenses/.
-->
<!DOCTYPE softpkg PUBLIC "-//JTRS//DTD SCA V2.2.2 SPD//EN" "softpkg.dtd">
<softpkg id="DCE:1b8b193b-bb30-443d-b8af-e5c7951d7e29" name="default_kinds" type="sca_compliant">
  <title></title>
  <author>
    <name>null</name>
  </author>
  <propertyfile type="PRF">
    <localfile name="default_kinds.prf.xml"/>
  </propertyfile>
  <descriptor>
    <localfile name="default_kinds.scd.xml"/>
  </descriptor>
  <implementation id="python">
    <description>The implementation contains descriptive information about the template for a software component.</description>
    <code type="Executable">
      <localfile name="python"/>
      <entrypoint>python/default_kinds.py</entrypoint>
    </code>
    <programminglanguage name="Python"/>
    <humanlanguage name="EN"/>
    <runtime name="python" version="2.4.4"/>
    <os name="Linux"/>
  </implementation>
</softpkg>

=== RedhawkSDR/core-framework/throughput/streams/bulkio/writer/writer.spd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
This file is protected by Copyright. Please refer to the COPYRIGHT file
distributed with this source distribution.

This file is part of REDHAWK throughput.

REDHAWK throughput is free software: you can redistribute it and/or modify it under
the terms of the GNU Lesser General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version.

REDHAWK throughput is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more
details.

You should have received a copy of the GNU Lesser General Public License along
with this program.  If not, see http://www.gnu.org/licenses/.
-->
<!DOCTYPE softpkg PUBLIC "-//JTRS//DTD SCA V2.2.2 SPD//EN" "softpkg.dtd">
<softpkg id="DCE:7f2f2ba0-005c-499c-99f0-517a9fbed76b" name="writer" type="sca_compliant">
  <title></title>
  <author>
    <name>null</name>
  </author>
  <propertyfile type="PRF">
    <localfile name="writer.prf.xml"/>
  </propertyfile>
  <descriptor>
    <localfile name="writer.scd.xml"/>
  </descriptor>
  <implementation id="cpp">
    <description>The implementation contains descriptive information about the template for a software component.</description>
    <code type="SharedLibrary">
      <localfile name="cpp/writer.so"/>
      <entrypoint>cpp/writer.so</entrypoint>
    </code>
    <compiler name="/usr/bin/gcc" version="4.1.2"/>
    <programminglanguage name="C++"/>
    <humanlanguage name="EN"/>
    <os name="Linux"/>
    <processor name="x86"/>
    <processor name="x86_64"/>
  </implementation>
</softpkg>

=== RedhawkSDR/core-framework/redhawk/src/testing/sdr/dom/components/time_py_now/time_py_now.spd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE softpkg PUBLIC "-//JTRS//DTD SCA V2.2.2 SPD//EN" "softpkg.dtd">
<softpkg id="DCE:8e079bfe-9c3e-48cc-b5e4-dc74f7461171" name="time_py_now" type="sca_compliant">
  <title></title>
  <author>
    <name>null</name>
  </author>
  <propertyfile type="PRF">
    <localfile name="time_py_now.prf.xml"/>
  </propertyfile>
  <descriptor>
    <localfile name="time_py_now.scd.xml"/>
  </descriptor>
  <implementation id="python">
    <description>The implementation contains descriptive information about the template for a software resource.</description>
    <code type="Executable">
      <localfile name="python"/>
      <entrypoint>python/time_py_now.py</entrypoint>
    </code>
    <programminglanguage name="Python"/>
    <humanlanguage name="EN"/>
    <runtime name="python" version="2.6.6"/>
    <os name="Linux"/>
  </implementation>
</softpkg>
